// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_CrossAppShareMissionConst, clz_Torappu_CrossAppShareMissionConstT } from './clz-torappu-cross-app-share-mission-const.js';
import { clz_Torappu_DailyMissionGroupInfo, clz_Torappu_DailyMissionGroupInfoT } from './clz-torappu-daily-mission-group-info.js';
import { clz_Torappu_MainlineMissionEndImageData, clz_Torappu_MainlineMissionEndImageDataT } from './clz-torappu-mainline-mission-end-image-data.js';
import { dict__string__clz_Torappu_CrossAppShareMission, dict__string__clz_Torappu_CrossAppShareMissionT } from './dict--string--clz-torappu-cross-app-share-mission.js';
import { dict__string__clz_Torappu_DailyMissionGroupInfo, dict__string__clz_Torappu_DailyMissionGroupInfoT } from './dict--string--clz-torappu-daily-mission-group-info.js';
import { dict__string__clz_Torappu_GuideMissionGroupInfo, dict__string__clz_Torappu_GuideMissionGroupInfoT } from './dict--string--clz-torappu-guide-mission-group-info.js';
import { dict__string__clz_Torappu_MissionDailyRewardConf, dict__string__clz_Torappu_MissionDailyRewardConfT } from './dict--string--clz-torappu-mission-daily-reward-conf.js';
import { dict__string__clz_Torappu_MissionData, dict__string__clz_Torappu_MissionDataT } from './dict--string--clz-torappu-mission-data.js';
import { dict__string__clz_Torappu_MissionGroup, dict__string__clz_Torappu_MissionGroupT } from './dict--string--clz-torappu-mission-group.js';
import { dict__string__clz_Torappu_MissionWeeklyRewardConf, dict__string__clz_Torappu_MissionWeeklyRewardConfT } from './dict--string--clz-torappu-mission-weekly-reward-conf.js';
import { dict__string__clz_Torappu_SOCharMissionGroup, dict__string__clz_Torappu_SOCharMissionGroupT } from './dict--string--clz-torappu-sochar-mission-group.js';


export class clz_Torappu_MissionTable implements flatbuffers.IUnpackableObject<clz_Torappu_MissionTableT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_MissionTable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_MissionTable(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MissionTable):clz_Torappu_MissionTable {
  return (obj || new clz_Torappu_MissionTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_MissionTable(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MissionTable):clz_Torappu_MissionTable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_MissionTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

missions(index: number, obj?:dict__string__clz_Torappu_MissionData):dict__string__clz_Torappu_MissionData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__string__clz_Torappu_MissionData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

missionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

missionGroups(index: number, obj?:dict__string__clz_Torappu_MissionGroup):dict__string__clz_Torappu_MissionGroup|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new dict__string__clz_Torappu_MissionGroup()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

missionGroupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

periodicalRewards(index: number, obj?:dict__string__clz_Torappu_MissionDailyRewardConf):dict__string__clz_Torappu_MissionDailyRewardConf|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new dict__string__clz_Torappu_MissionDailyRewardConf()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

periodicalRewardsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

weeklyRewards(index: number, obj?:dict__string__clz_Torappu_MissionWeeklyRewardConf):dict__string__clz_Torappu_MissionWeeklyRewardConf|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new dict__string__clz_Torappu_MissionWeeklyRewardConf()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

weeklyRewardsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

soCharMissionGroupInfo(index: number, obj?:dict__string__clz_Torappu_SOCharMissionGroup):dict__string__clz_Torappu_SOCharMissionGroup|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new dict__string__clz_Torappu_SOCharMissionGroup()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

soCharMissionGroupInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dailyMissionGroupInfo(index: number, obj?:dict__string__clz_Torappu_DailyMissionGroupInfo):dict__string__clz_Torappu_DailyMissionGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new dict__string__clz_Torappu_DailyMissionGroupInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dailyMissionGroupInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dailyMissionPeriodInfo(index: number, obj?:clz_Torappu_DailyMissionGroupInfo):clz_Torappu_DailyMissionGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new clz_Torappu_DailyMissionGroupInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

dailyMissionPeriodInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

mainlineMissionEndImageDataList(index: number, obj?:clz_Torappu_MainlineMissionEndImageData):clz_Torappu_MainlineMissionEndImageData|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new clz_Torappu_MainlineMissionEndImageData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

mainlineMissionEndImageDataListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

crossAppShareMissions(index: number, obj?:dict__string__clz_Torappu_CrossAppShareMission):dict__string__clz_Torappu_CrossAppShareMission|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new dict__string__clz_Torappu_CrossAppShareMission()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

crossAppShareMissionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

crossAppShareMissionConst(obj?:clz_Torappu_CrossAppShareMissionConst):clz_Torappu_CrossAppShareMissionConst|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new clz_Torappu_CrossAppShareMissionConst()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

guideMissionGroupInfo(index: number, obj?:dict__string__clz_Torappu_GuideMissionGroupInfo):dict__string__clz_Torappu_GuideMissionGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new dict__string__clz_Torappu_GuideMissionGroupInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

guideMissionGroupInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_MissionTable(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addMissions(builder:flatbuffers.Builder, missionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, missionsOffset, 0);
}

static createMissionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMissionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMissionGroups(builder:flatbuffers.Builder, missionGroupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, missionGroupsOffset, 0);
}

static createMissionGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMissionGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPeriodicalRewards(builder:flatbuffers.Builder, periodicalRewardsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, periodicalRewardsOffset, 0);
}

static createPeriodicalRewardsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPeriodicalRewardsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addWeeklyRewards(builder:flatbuffers.Builder, weeklyRewardsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, weeklyRewardsOffset, 0);
}

static createWeeklyRewardsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startWeeklyRewardsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSoCharMissionGroupInfo(builder:flatbuffers.Builder, soCharMissionGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, soCharMissionGroupInfoOffset, 0);
}

static createSoCharMissionGroupInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSoCharMissionGroupInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDailyMissionGroupInfo(builder:flatbuffers.Builder, dailyMissionGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, dailyMissionGroupInfoOffset, 0);
}

static createDailyMissionGroupInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDailyMissionGroupInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDailyMissionPeriodInfo(builder:flatbuffers.Builder, dailyMissionPeriodInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, dailyMissionPeriodInfoOffset, 0);
}

static createDailyMissionPeriodInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDailyMissionPeriodInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMainlineMissionEndImageDataList(builder:flatbuffers.Builder, mainlineMissionEndImageDataListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, mainlineMissionEndImageDataListOffset, 0);
}

static createMainlineMissionEndImageDataListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMainlineMissionEndImageDataListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCrossAppShareMissions(builder:flatbuffers.Builder, crossAppShareMissionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, crossAppShareMissionsOffset, 0);
}

static createCrossAppShareMissionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCrossAppShareMissionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCrossAppShareMissionConst(builder:flatbuffers.Builder, crossAppShareMissionConstOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, crossAppShareMissionConstOffset, 0);
}

static addGuideMissionGroupInfo(builder:flatbuffers.Builder, guideMissionGroupInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, guideMissionGroupInfoOffset, 0);
}

static createGuideMissionGroupInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGuideMissionGroupInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_MissionTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishclz_Torappu_MissionTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedclz_Torappu_MissionTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}


unpack(): clz_Torappu_MissionTableT {
  return new clz_Torappu_MissionTableT(
    this.bb!.createObjList<dict__string__clz_Torappu_MissionData, dict__string__clz_Torappu_MissionDataT>(this.missions.bind(this), this.missionsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_MissionGroup, dict__string__clz_Torappu_MissionGroupT>(this.missionGroups.bind(this), this.missionGroupsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_MissionDailyRewardConf, dict__string__clz_Torappu_MissionDailyRewardConfT>(this.periodicalRewards.bind(this), this.periodicalRewardsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_MissionWeeklyRewardConf, dict__string__clz_Torappu_MissionWeeklyRewardConfT>(this.weeklyRewards.bind(this), this.weeklyRewardsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_SOCharMissionGroup, dict__string__clz_Torappu_SOCharMissionGroupT>(this.soCharMissionGroupInfo.bind(this), this.soCharMissionGroupInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_DailyMissionGroupInfo, dict__string__clz_Torappu_DailyMissionGroupInfoT>(this.dailyMissionGroupInfo.bind(this), this.dailyMissionGroupInfoLength()),
    this.bb!.createObjList<clz_Torappu_DailyMissionGroupInfo, clz_Torappu_DailyMissionGroupInfoT>(this.dailyMissionPeriodInfo.bind(this), this.dailyMissionPeriodInfoLength()),
    this.bb!.createObjList<clz_Torappu_MainlineMissionEndImageData, clz_Torappu_MainlineMissionEndImageDataT>(this.mainlineMissionEndImageDataList.bind(this), this.mainlineMissionEndImageDataListLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_CrossAppShareMission, dict__string__clz_Torappu_CrossAppShareMissionT>(this.crossAppShareMissions.bind(this), this.crossAppShareMissionsLength()),
    (this.crossAppShareMissionConst() !== null ? this.crossAppShareMissionConst()!.unpack() : null),
    this.bb!.createObjList<dict__string__clz_Torappu_GuideMissionGroupInfo, dict__string__clz_Torappu_GuideMissionGroupInfoT>(this.guideMissionGroupInfo.bind(this), this.guideMissionGroupInfoLength())
  );
}


unpackTo(_o: clz_Torappu_MissionTableT): void {
  _o.missions = this.bb!.createObjList<dict__string__clz_Torappu_MissionData, dict__string__clz_Torappu_MissionDataT>(this.missions.bind(this), this.missionsLength());
  _o.missionGroups = this.bb!.createObjList<dict__string__clz_Torappu_MissionGroup, dict__string__clz_Torappu_MissionGroupT>(this.missionGroups.bind(this), this.missionGroupsLength());
  _o.periodicalRewards = this.bb!.createObjList<dict__string__clz_Torappu_MissionDailyRewardConf, dict__string__clz_Torappu_MissionDailyRewardConfT>(this.periodicalRewards.bind(this), this.periodicalRewardsLength());
  _o.weeklyRewards = this.bb!.createObjList<dict__string__clz_Torappu_MissionWeeklyRewardConf, dict__string__clz_Torappu_MissionWeeklyRewardConfT>(this.weeklyRewards.bind(this), this.weeklyRewardsLength());
  _o.soCharMissionGroupInfo = this.bb!.createObjList<dict__string__clz_Torappu_SOCharMissionGroup, dict__string__clz_Torappu_SOCharMissionGroupT>(this.soCharMissionGroupInfo.bind(this), this.soCharMissionGroupInfoLength());
  _o.dailyMissionGroupInfo = this.bb!.createObjList<dict__string__clz_Torappu_DailyMissionGroupInfo, dict__string__clz_Torappu_DailyMissionGroupInfoT>(this.dailyMissionGroupInfo.bind(this), this.dailyMissionGroupInfoLength());
  _o.dailyMissionPeriodInfo = this.bb!.createObjList<clz_Torappu_DailyMissionGroupInfo, clz_Torappu_DailyMissionGroupInfoT>(this.dailyMissionPeriodInfo.bind(this), this.dailyMissionPeriodInfoLength());
  _o.mainlineMissionEndImageDataList = this.bb!.createObjList<clz_Torappu_MainlineMissionEndImageData, clz_Torappu_MainlineMissionEndImageDataT>(this.mainlineMissionEndImageDataList.bind(this), this.mainlineMissionEndImageDataListLength());
  _o.crossAppShareMissions = this.bb!.createObjList<dict__string__clz_Torappu_CrossAppShareMission, dict__string__clz_Torappu_CrossAppShareMissionT>(this.crossAppShareMissions.bind(this), this.crossAppShareMissionsLength());
  _o.crossAppShareMissionConst = (this.crossAppShareMissionConst() !== null ? this.crossAppShareMissionConst()!.unpack() : null);
  _o.guideMissionGroupInfo = this.bb!.createObjList<dict__string__clz_Torappu_GuideMissionGroupInfo, dict__string__clz_Torappu_GuideMissionGroupInfoT>(this.guideMissionGroupInfo.bind(this), this.guideMissionGroupInfoLength());
}
}

export class clz_Torappu_MissionTableT implements flatbuffers.IGeneratedObject {
constructor(
  public missions: (dict__string__clz_Torappu_MissionDataT)[] = [],
  public missionGroups: (dict__string__clz_Torappu_MissionGroupT)[] = [],
  public periodicalRewards: (dict__string__clz_Torappu_MissionDailyRewardConfT)[] = [],
  public weeklyRewards: (dict__string__clz_Torappu_MissionWeeklyRewardConfT)[] = [],
  public soCharMissionGroupInfo: (dict__string__clz_Torappu_SOCharMissionGroupT)[] = [],
  public dailyMissionGroupInfo: (dict__string__clz_Torappu_DailyMissionGroupInfoT)[] = [],
  public dailyMissionPeriodInfo: (clz_Torappu_DailyMissionGroupInfoT)[] = [],
  public mainlineMissionEndImageDataList: (clz_Torappu_MainlineMissionEndImageDataT)[] = [],
  public crossAppShareMissions: (dict__string__clz_Torappu_CrossAppShareMissionT)[] = [],
  public crossAppShareMissionConst: clz_Torappu_CrossAppShareMissionConstT|null = null,
  public guideMissionGroupInfo: (dict__string__clz_Torappu_GuideMissionGroupInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const missions = clz_Torappu_MissionTable.createMissionsVector(builder, builder.createObjectOffsetList(this.missions));
  const missionGroups = clz_Torappu_MissionTable.createMissionGroupsVector(builder, builder.createObjectOffsetList(this.missionGroups));
  const periodicalRewards = clz_Torappu_MissionTable.createPeriodicalRewardsVector(builder, builder.createObjectOffsetList(this.periodicalRewards));
  const weeklyRewards = clz_Torappu_MissionTable.createWeeklyRewardsVector(builder, builder.createObjectOffsetList(this.weeklyRewards));
  const soCharMissionGroupInfo = clz_Torappu_MissionTable.createSoCharMissionGroupInfoVector(builder, builder.createObjectOffsetList(this.soCharMissionGroupInfo));
  const dailyMissionGroupInfo = clz_Torappu_MissionTable.createDailyMissionGroupInfoVector(builder, builder.createObjectOffsetList(this.dailyMissionGroupInfo));
  const dailyMissionPeriodInfo = clz_Torappu_MissionTable.createDailyMissionPeriodInfoVector(builder, builder.createObjectOffsetList(this.dailyMissionPeriodInfo));
  const mainlineMissionEndImageDataList = clz_Torappu_MissionTable.createMainlineMissionEndImageDataListVector(builder, builder.createObjectOffsetList(this.mainlineMissionEndImageDataList));
  const crossAppShareMissions = clz_Torappu_MissionTable.createCrossAppShareMissionsVector(builder, builder.createObjectOffsetList(this.crossAppShareMissions));
  const crossAppShareMissionConst = (this.crossAppShareMissionConst !== null ? this.crossAppShareMissionConst!.pack(builder) : 0);
  const guideMissionGroupInfo = clz_Torappu_MissionTable.createGuideMissionGroupInfoVector(builder, builder.createObjectOffsetList(this.guideMissionGroupInfo));

  clz_Torappu_MissionTable.startclz_Torappu_MissionTable(builder);
  clz_Torappu_MissionTable.addMissions(builder, missions);
  clz_Torappu_MissionTable.addMissionGroups(builder, missionGroups);
  clz_Torappu_MissionTable.addPeriodicalRewards(builder, periodicalRewards);
  clz_Torappu_MissionTable.addWeeklyRewards(builder, weeklyRewards);
  clz_Torappu_MissionTable.addSoCharMissionGroupInfo(builder, soCharMissionGroupInfo);
  clz_Torappu_MissionTable.addDailyMissionGroupInfo(builder, dailyMissionGroupInfo);
  clz_Torappu_MissionTable.addDailyMissionPeriodInfo(builder, dailyMissionPeriodInfo);
  clz_Torappu_MissionTable.addMainlineMissionEndImageDataList(builder, mainlineMissionEndImageDataList);
  clz_Torappu_MissionTable.addCrossAppShareMissions(builder, crossAppShareMissions);
  clz_Torappu_MissionTable.addCrossAppShareMissionConst(builder, crossAppShareMissionConst);
  clz_Torappu_MissionTable.addGuideMissionGroupInfo(builder, guideMissionGroupInfo);

  return clz_Torappu_MissionTable.endclz_Torappu_MissionTable(builder);
}
}
