// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_SandboxV2DialogData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxV2DialogDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxV2DialogData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxV2DialogData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2DialogData):clz_Torappu_SandboxV2DialogData {
  return (obj || new clz_Torappu_SandboxV2DialogData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxV2DialogData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2DialogData):clz_Torappu_SandboxV2DialogData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxV2DialogData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

dialogId():string|null
dialogId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
dialogId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

avgId():string|null
avgId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
avgId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_SandboxV2DialogData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addDialogId(builder:flatbuffers.Builder, dialogIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dialogIdOffset, 0);
}

static addAvgId(builder:flatbuffers.Builder, avgIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, avgIdOffset, 0);
}

static endclz_Torappu_SandboxV2DialogData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxV2DialogData(builder:flatbuffers.Builder, dialogIdOffset:flatbuffers.Offset, avgIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_SandboxV2DialogData.startclz_Torappu_SandboxV2DialogData(builder);
  clz_Torappu_SandboxV2DialogData.addDialogId(builder, dialogIdOffset);
  clz_Torappu_SandboxV2DialogData.addAvgId(builder, avgIdOffset);
  return clz_Torappu_SandboxV2DialogData.endclz_Torappu_SandboxV2DialogData(builder);
}

unpack(): clz_Torappu_SandboxV2DialogDataT {
  return new clz_Torappu_SandboxV2DialogDataT(
    this.dialogId(),
    this.avgId()
  );
}


unpackTo(_o: clz_Torappu_SandboxV2DialogDataT): void {
  _o.dialogId = this.dialogId();
  _o.avgId = this.avgId();
}
}

export class clz_Torappu_SandboxV2DialogDataT implements flatbuffers.IGeneratedObject {
constructor(
  public dialogId: string|Uint8Array|null = null,
  public avgId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const dialogId = (this.dialogId !== null ? builder.createString(this.dialogId!) : 0);
  const avgId = (this.avgId !== null ? builder.createString(this.avgId!) : 0);

  return clz_Torappu_SandboxV2DialogData.createclz_Torappu_SandboxV2DialogData(builder,
    dialogId,
    avgId
  );
}
}
