// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_BuildingData_CharStationFilterType } from './enum--torappu-building-data-char-station-filter-type.js';


export class clz_Torappu_BuildingData_StationManageFilterInfo implements flatbuffers.IUnpackableObject<clz_Torappu_BuildingData_StationManageFilterInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_BuildingData_StationManageFilterInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_BuildingData_StationManageFilterInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_StationManageFilterInfo):clz_Torappu_BuildingData_StationManageFilterInfo {
  return (obj || new clz_Torappu_BuildingData_StationManageFilterInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_BuildingData_StationManageFilterInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_StationManageFilterInfo):clz_Torappu_BuildingData_StationManageFilterInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_BuildingData_StationManageFilterInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

charStationFilterType():enum__Torappu_BuildingData_CharStationFilterType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_BuildingData_CharStationFilterType.All;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_BuildingData_StationManageFilterInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCharStationFilterType(builder:flatbuffers.Builder, charStationFilterType:enum__Torappu_BuildingData_CharStationFilterType) {
  builder.addFieldInt32(0, charStationFilterType, enum__Torappu_BuildingData_CharStationFilterType.All);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static endclz_Torappu_BuildingData_StationManageFilterInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_BuildingData_StationManageFilterInfo(builder:flatbuffers.Builder, charStationFilterType:enum__Torappu_BuildingData_CharStationFilterType, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_BuildingData_StationManageFilterInfo.startclz_Torappu_BuildingData_StationManageFilterInfo(builder);
  clz_Torappu_BuildingData_StationManageFilterInfo.addCharStationFilterType(builder, charStationFilterType);
  clz_Torappu_BuildingData_StationManageFilterInfo.addName(builder, nameOffset);
  return clz_Torappu_BuildingData_StationManageFilterInfo.endclz_Torappu_BuildingData_StationManageFilterInfo(builder);
}

unpack(): clz_Torappu_BuildingData_StationManageFilterInfoT {
  return new clz_Torappu_BuildingData_StationManageFilterInfoT(
    this.charStationFilterType(),
    this.name()
  );
}


unpackTo(_o: clz_Torappu_BuildingData_StationManageFilterInfoT): void {
  _o.charStationFilterType = this.charStationFilterType();
  _o.name = this.name();
}
}

export class clz_Torappu_BuildingData_StationManageFilterInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public charStationFilterType: enum__Torappu_BuildingData_CharStationFilterType = enum__Torappu_BuildingData_CharStationFilterType.All,
  public name: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);

  return clz_Torappu_BuildingData_StationManageFilterInfo.createclz_Torappu_BuildingData_StationManageFilterInfo(builder,
    this.charStationFilterType,
    name
  );
}
}
