// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_RuneData, clz_Torappu_RuneDataT } from './clz-torappu-rune-data.js';


export class clz_Torappu_RuneTable_PackedRuneData implements flatbuffers.IUnpackableObject<clz_Torappu_RuneTable_PackedRuneDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RuneTable_PackedRuneData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RuneTable_PackedRuneData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RuneTable_PackedRuneData):clz_Torappu_RuneTable_PackedRuneData {
  return (obj || new clz_Torappu_RuneTable_PackedRuneData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RuneTable_PackedRuneData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RuneTable_PackedRuneData):clz_Torappu_RuneTable_PackedRuneData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RuneTable_PackedRuneData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

points():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

mutexGroupKey():string|null
mutexGroupKey(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mutexGroupKey(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

description():string|null
description(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
description(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

runes(index: number, obj?:clz_Torappu_RuneData):clz_Torappu_RuneData|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new clz_Torappu_RuneData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

runesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_RuneTable_PackedRuneData(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addPoints(builder:flatbuffers.Builder, points:number) {
  builder.addFieldFloat32(1, points, 0.0);
}

static addMutexGroupKey(builder:flatbuffers.Builder, mutexGroupKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, mutexGroupKeyOffset, 0);
}

static addDescription(builder:flatbuffers.Builder, descriptionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, descriptionOffset, 0);
}

static addRunes(builder:flatbuffers.Builder, runesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, runesOffset, 0);
}

static createRunesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRunesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_RuneTable_PackedRuneData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_RuneTable_PackedRuneData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, points:number, mutexGroupKeyOffset:flatbuffers.Offset, descriptionOffset:flatbuffers.Offset, runesOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_RuneTable_PackedRuneData.startclz_Torappu_RuneTable_PackedRuneData(builder);
  clz_Torappu_RuneTable_PackedRuneData.addId(builder, idOffset);
  clz_Torappu_RuneTable_PackedRuneData.addPoints(builder, points);
  clz_Torappu_RuneTable_PackedRuneData.addMutexGroupKey(builder, mutexGroupKeyOffset);
  clz_Torappu_RuneTable_PackedRuneData.addDescription(builder, descriptionOffset);
  clz_Torappu_RuneTable_PackedRuneData.addRunes(builder, runesOffset);
  return clz_Torappu_RuneTable_PackedRuneData.endclz_Torappu_RuneTable_PackedRuneData(builder);
}

unpack(): clz_Torappu_RuneTable_PackedRuneDataT {
  return new clz_Torappu_RuneTable_PackedRuneDataT(
    this.id(),
    this.points(),
    this.mutexGroupKey(),
    this.description(),
    this.bb!.createObjList<clz_Torappu_RuneData, clz_Torappu_RuneDataT>(this.runes.bind(this), this.runesLength())
  );
}


unpackTo(_o: clz_Torappu_RuneTable_PackedRuneDataT): void {
  _o.id = this.id();
  _o.points = this.points();
  _o.mutexGroupKey = this.mutexGroupKey();
  _o.description = this.description();
  _o.runes = this.bb!.createObjList<clz_Torappu_RuneData, clz_Torappu_RuneDataT>(this.runes.bind(this), this.runesLength());
}
}

export class clz_Torappu_RuneTable_PackedRuneDataT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public points: number = 0.0,
  public mutexGroupKey: string|Uint8Array|null = null,
  public description: string|Uint8Array|null = null,
  public runes: (clz_Torappu_RuneDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const mutexGroupKey = (this.mutexGroupKey !== null ? builder.createString(this.mutexGroupKey!) : 0);
  const description = (this.description !== null ? builder.createString(this.description!) : 0);
  const runes = clz_Torappu_RuneTable_PackedRuneData.createRunesVector(builder, builder.createObjectOffsetList(this.runes));

  return clz_Torappu_RuneTable_PackedRuneData.createclz_Torappu_RuneTable_PackedRuneData(builder,
    id,
    this.points,
    mutexGroupKey,
    description,
    runes
  );
}
}
