// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_ItemData_BuildingProductInfo, clz_Torappu_ItemData_BuildingProductInfoT } from './clz-torappu-item-data-building-product-info.js';
import { clz_Torappu_ItemData_ShopRelateInfo, clz_Torappu_ItemData_ShopRelateInfoT } from './clz-torappu-item-data-shop-relate-info.js';
import { clz_Torappu_ItemData_StageDropInfo, clz_Torappu_ItemData_StageDropInfoT } from './clz-torappu-item-data-stage-drop-info.js';
import { clz_Torappu_ItemData_VoucherRelateInfo, clz_Torappu_ItemData_VoucherRelateInfoT } from './clz-torappu-item-data-voucher-relate-info.js';
import { enum__Torappu_ItemClassifyType } from './enum--torappu-item-classify-type.js';
import { enum__Torappu_ItemRarity } from './enum--torappu-item-rarity.js';
import { enum__Torappu_ItemType } from './enum--torappu-item-type.js';


export class clz_Torappu_ItemData implements flatbuffers.IUnpackableObject<clz_Torappu_ItemDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ItemData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ItemData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ItemData):clz_Torappu_ItemData {
  return (obj || new clz_Torappu_ItemData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ItemData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ItemData):clz_Torappu_ItemData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ItemData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

itemId():string|null
itemId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
itemId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

description():string|null
description(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
description(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

rarity():enum__Torappu_ItemRarity {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_ItemRarity.TIER_1;
}

iconId():string|null
iconId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
iconId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

overrideBkg():string|null
overrideBkg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
overrideBkg(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

stackIconId():string|null
stackIconId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stackIconId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sortId():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

usage():string|null
usage(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
usage(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

obtainApproach():string|null
obtainApproach(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
obtainApproach(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

hideInItemGet():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

classifyType():enum__Torappu_ItemClassifyType {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_ItemClassifyType.NONE;
}

itemType():enum__Torappu_ItemType {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_ItemType.NONE;
}

stageDropList(index: number, obj?:clz_Torappu_ItemData_StageDropInfo):clz_Torappu_ItemData_StageDropInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new clz_Torappu_ItemData_StageDropInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stageDropListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

buildingProductList(index: number, obj?:clz_Torappu_ItemData_BuildingProductInfo):clz_Torappu_ItemData_BuildingProductInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new clz_Torappu_ItemData_BuildingProductInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

buildingProductListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

voucherRelateList(index: number, obj?:clz_Torappu_ItemData_VoucherRelateInfo):clz_Torappu_ItemData_VoucherRelateInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new clz_Torappu_ItemData_VoucherRelateInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

voucherRelateListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

shopRelateInfoList(index: number, obj?:clz_Torappu_ItemData_ShopRelateInfo):clz_Torappu_ItemData_ShopRelateInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? (obj || new clz_Torappu_ItemData_ShopRelateInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

shopRelateInfoListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ItemData(builder:flatbuffers.Builder) {
  builder.startObject(17);
}

static addItemId(builder:flatbuffers.Builder, itemIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemIdOffset, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addDescription(builder:flatbuffers.Builder, descriptionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, descriptionOffset, 0);
}

static addRarity(builder:flatbuffers.Builder, rarity:enum__Torappu_ItemRarity) {
  builder.addFieldInt32(3, rarity, enum__Torappu_ItemRarity.TIER_1);
}

static addIconId(builder:flatbuffers.Builder, iconIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, iconIdOffset, 0);
}

static addOverrideBkg(builder:flatbuffers.Builder, overrideBkgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, overrideBkgOffset, 0);
}

static addStackIconId(builder:flatbuffers.Builder, stackIconIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, stackIconIdOffset, 0);
}

static addSortId(builder:flatbuffers.Builder, sortId:number) {
  builder.addFieldInt32(7, sortId, 0);
}

static addUsage(builder:flatbuffers.Builder, usageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, usageOffset, 0);
}

static addObtainApproach(builder:flatbuffers.Builder, obtainApproachOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, obtainApproachOffset, 0);
}

static addHideInItemGet(builder:flatbuffers.Builder, hideInItemGet:boolean) {
  builder.addFieldInt8(10, +hideInItemGet, +false);
}

static addClassifyType(builder:flatbuffers.Builder, classifyType:enum__Torappu_ItemClassifyType) {
  builder.addFieldInt32(11, classifyType, enum__Torappu_ItemClassifyType.NONE);
}

static addItemType(builder:flatbuffers.Builder, itemType:enum__Torappu_ItemType) {
  builder.addFieldInt32(12, itemType, enum__Torappu_ItemType.NONE);
}

static addStageDropList(builder:flatbuffers.Builder, stageDropListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, stageDropListOffset, 0);
}

static createStageDropListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageDropListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBuildingProductList(builder:flatbuffers.Builder, buildingProductListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, buildingProductListOffset, 0);
}

static createBuildingProductListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBuildingProductListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addVoucherRelateList(builder:flatbuffers.Builder, voucherRelateListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, voucherRelateListOffset, 0);
}

static createVoucherRelateListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startVoucherRelateListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addShopRelateInfoList(builder:flatbuffers.Builder, shopRelateInfoListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(16, shopRelateInfoListOffset, 0);
}

static createShopRelateInfoListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startShopRelateInfoListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_ItemData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ItemData(builder:flatbuffers.Builder, itemIdOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, descriptionOffset:flatbuffers.Offset, rarity:enum__Torappu_ItemRarity, iconIdOffset:flatbuffers.Offset, overrideBkgOffset:flatbuffers.Offset, stackIconIdOffset:flatbuffers.Offset, sortId:number, usageOffset:flatbuffers.Offset, obtainApproachOffset:flatbuffers.Offset, hideInItemGet:boolean, classifyType:enum__Torappu_ItemClassifyType, itemType:enum__Torappu_ItemType, stageDropListOffset:flatbuffers.Offset, buildingProductListOffset:flatbuffers.Offset, voucherRelateListOffset:flatbuffers.Offset, shopRelateInfoListOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ItemData.startclz_Torappu_ItemData(builder);
  clz_Torappu_ItemData.addItemId(builder, itemIdOffset);
  clz_Torappu_ItemData.addName(builder, nameOffset);
  clz_Torappu_ItemData.addDescription(builder, descriptionOffset);
  clz_Torappu_ItemData.addRarity(builder, rarity);
  clz_Torappu_ItemData.addIconId(builder, iconIdOffset);
  clz_Torappu_ItemData.addOverrideBkg(builder, overrideBkgOffset);
  clz_Torappu_ItemData.addStackIconId(builder, stackIconIdOffset);
  clz_Torappu_ItemData.addSortId(builder, sortId);
  clz_Torappu_ItemData.addUsage(builder, usageOffset);
  clz_Torappu_ItemData.addObtainApproach(builder, obtainApproachOffset);
  clz_Torappu_ItemData.addHideInItemGet(builder, hideInItemGet);
  clz_Torappu_ItemData.addClassifyType(builder, classifyType);
  clz_Torappu_ItemData.addItemType(builder, itemType);
  clz_Torappu_ItemData.addStageDropList(builder, stageDropListOffset);
  clz_Torappu_ItemData.addBuildingProductList(builder, buildingProductListOffset);
  clz_Torappu_ItemData.addVoucherRelateList(builder, voucherRelateListOffset);
  clz_Torappu_ItemData.addShopRelateInfoList(builder, shopRelateInfoListOffset);
  return clz_Torappu_ItemData.endclz_Torappu_ItemData(builder);
}

unpack(): clz_Torappu_ItemDataT {
  return new clz_Torappu_ItemDataT(
    this.itemId(),
    this.name(),
    this.description(),
    this.rarity(),
    this.iconId(),
    this.overrideBkg(),
    this.stackIconId(),
    this.sortId(),
    this.usage(),
    this.obtainApproach(),
    this.hideInItemGet(),
    this.classifyType(),
    this.itemType(),
    this.bb!.createObjList<clz_Torappu_ItemData_StageDropInfo, clz_Torappu_ItemData_StageDropInfoT>(this.stageDropList.bind(this), this.stageDropListLength()),
    this.bb!.createObjList<clz_Torappu_ItemData_BuildingProductInfo, clz_Torappu_ItemData_BuildingProductInfoT>(this.buildingProductList.bind(this), this.buildingProductListLength()),
    this.bb!.createObjList<clz_Torappu_ItemData_VoucherRelateInfo, clz_Torappu_ItemData_VoucherRelateInfoT>(this.voucherRelateList.bind(this), this.voucherRelateListLength()),
    this.bb!.createObjList<clz_Torappu_ItemData_ShopRelateInfo, clz_Torappu_ItemData_ShopRelateInfoT>(this.shopRelateInfoList.bind(this), this.shopRelateInfoListLength())
  );
}


unpackTo(_o: clz_Torappu_ItemDataT): void {
  _o.itemId = this.itemId();
  _o.name = this.name();
  _o.description = this.description();
  _o.rarity = this.rarity();
  _o.iconId = this.iconId();
  _o.overrideBkg = this.overrideBkg();
  _o.stackIconId = this.stackIconId();
  _o.sortId = this.sortId();
  _o.usage = this.usage();
  _o.obtainApproach = this.obtainApproach();
  _o.hideInItemGet = this.hideInItemGet();
  _o.classifyType = this.classifyType();
  _o.itemType = this.itemType();
  _o.stageDropList = this.bb!.createObjList<clz_Torappu_ItemData_StageDropInfo, clz_Torappu_ItemData_StageDropInfoT>(this.stageDropList.bind(this), this.stageDropListLength());
  _o.buildingProductList = this.bb!.createObjList<clz_Torappu_ItemData_BuildingProductInfo, clz_Torappu_ItemData_BuildingProductInfoT>(this.buildingProductList.bind(this), this.buildingProductListLength());
  _o.voucherRelateList = this.bb!.createObjList<clz_Torappu_ItemData_VoucherRelateInfo, clz_Torappu_ItemData_VoucherRelateInfoT>(this.voucherRelateList.bind(this), this.voucherRelateListLength());
  _o.shopRelateInfoList = this.bb!.createObjList<clz_Torappu_ItemData_ShopRelateInfo, clz_Torappu_ItemData_ShopRelateInfoT>(this.shopRelateInfoList.bind(this), this.shopRelateInfoListLength());
}
}

export class clz_Torappu_ItemDataT implements flatbuffers.IGeneratedObject {
constructor(
  public itemId: string|Uint8Array|null = null,
  public name: string|Uint8Array|null = null,
  public description: string|Uint8Array|null = null,
  public rarity: enum__Torappu_ItemRarity = enum__Torappu_ItemRarity.TIER_1,
  public iconId: string|Uint8Array|null = null,
  public overrideBkg: string|Uint8Array|null = null,
  public stackIconId: string|Uint8Array|null = null,
  public sortId: number = 0,
  public usage: string|Uint8Array|null = null,
  public obtainApproach: string|Uint8Array|null = null,
  public hideInItemGet: boolean = false,
  public classifyType: enum__Torappu_ItemClassifyType = enum__Torappu_ItemClassifyType.NONE,
  public itemType: enum__Torappu_ItemType = enum__Torappu_ItemType.NONE,
  public stageDropList: (clz_Torappu_ItemData_StageDropInfoT)[] = [],
  public buildingProductList: (clz_Torappu_ItemData_BuildingProductInfoT)[] = [],
  public voucherRelateList: (clz_Torappu_ItemData_VoucherRelateInfoT)[] = [],
  public shopRelateInfoList: (clz_Torappu_ItemData_ShopRelateInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const itemId = (this.itemId !== null ? builder.createString(this.itemId!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const description = (this.description !== null ? builder.createString(this.description!) : 0);
  const iconId = (this.iconId !== null ? builder.createString(this.iconId!) : 0);
  const overrideBkg = (this.overrideBkg !== null ? builder.createString(this.overrideBkg!) : 0);
  const stackIconId = (this.stackIconId !== null ? builder.createString(this.stackIconId!) : 0);
  const usage = (this.usage !== null ? builder.createString(this.usage!) : 0);
  const obtainApproach = (this.obtainApproach !== null ? builder.createString(this.obtainApproach!) : 0);
  const stageDropList = clz_Torappu_ItemData.createStageDropListVector(builder, builder.createObjectOffsetList(this.stageDropList));
  const buildingProductList = clz_Torappu_ItemData.createBuildingProductListVector(builder, builder.createObjectOffsetList(this.buildingProductList));
  const voucherRelateList = clz_Torappu_ItemData.createVoucherRelateListVector(builder, builder.createObjectOffsetList(this.voucherRelateList));
  const shopRelateInfoList = clz_Torappu_ItemData.createShopRelateInfoListVector(builder, builder.createObjectOffsetList(this.shopRelateInfoList));

  return clz_Torappu_ItemData.createclz_Torappu_ItemData(builder,
    itemId,
    name,
    description,
    this.rarity,
    iconId,
    overrideBkg,
    stackIconId,
    this.sortId,
    usage,
    obtainApproach,
    this.hideInItemGet,
    this.classifyType,
    this.itemType,
    stageDropList,
    buildingProductList,
    voucherRelateList,
    shopRelateInfoList
  );
}
}
