// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem implements flatbuffers.IUnpackableObject<clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItemT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem):clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem {
  return (obj || new clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem):clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

furnitureId():string|null
furnitureId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
furnitureId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

pos0():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

pos1():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

dir():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addFurnitureId(builder:flatbuffers.Builder, furnitureIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, furnitureIdOffset, 0);
}

static addPos0(builder:flatbuffers.Builder, pos0:number) {
  builder.addFieldInt32(1, pos0, 0);
}

static addPos1(builder:flatbuffers.Builder, pos1:number) {
  builder.addFieldInt32(2, pos1, 0);
}

static addDir(builder:flatbuffers.Builder, dir:number) {
  builder.addFieldInt32(3, dir, 0);
}

static endclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder:flatbuffers.Builder, furnitureIdOffset:flatbuffers.Offset, pos0:number, pos1:number, dir:number):flatbuffers.Offset {
  clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.startclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder);
  clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.addFurnitureId(builder, furnitureIdOffset);
  clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.addPos0(builder, pos0);
  clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.addPos1(builder, pos1);
  clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.addDir(builder, dir);
  return clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.endclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder);
}

unpack(): clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItemT {
  return new clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItemT(
    this.furnitureId(),
    this.pos0(),
    this.pos1(),
    this.dir()
  );
}


unpackTo(_o: clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItemT): void {
  _o.furnitureId = this.furnitureId();
  _o.pos0 = this.pos0();
  _o.pos1 = this.pos1();
  _o.dir = this.dir();
}
}

export class clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItemT implements flatbuffers.IGeneratedObject {
constructor(
  public furnitureId: string|Uint8Array|null = null,
  public pos0: number = 0,
  public pos1: number = 0,
  public dir: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const furnitureId = (this.furnitureId !== null ? builder.createString(this.furnitureId!) : 0);

  return clz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem.createclz_Torappu_BuildingData_CustomData_ThemeQuickSetupItem(builder,
    furnitureId,
    this.pos0,
    this.pos1,
    this.dir
  );
}
}
