// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_BuildingData_RecycleRoomConsts implements flatbuffers.IUnpackableObject<clz_Torappu_BuildingData_RecycleRoomConstsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_BuildingData_RecycleRoomConsts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_BuildingData_RecycleRoomConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_RecycleRoomConsts):clz_Torappu_BuildingData_RecycleRoomConsts {
  return (obj || new clz_Torappu_BuildingData_RecycleRoomConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_BuildingData_RecycleRoomConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_BuildingData_RecycleRoomConsts):clz_Torappu_BuildingData_RecycleRoomConsts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_BuildingData_RecycleRoomConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

recycleTimeRequirement():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

recycleBaseCapacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

recycleBoostSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

recycleBoostLimit():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

recycleBoostLimitProtect():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

recycleSpeedUpUnlockLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

recycleTwoPersonUnlockLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_BuildingData_RecycleRoomConsts(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addRecycleTimeRequirement(builder:flatbuffers.Builder, recycleTimeRequirement:bigint) {
  builder.addFieldInt64(0, recycleTimeRequirement, BigInt('0'));
}

static addRecycleBaseCapacity(builder:flatbuffers.Builder, recycleBaseCapacity:number) {
  builder.addFieldInt32(1, recycleBaseCapacity, 0);
}

static addRecycleBoostSpeed(builder:flatbuffers.Builder, recycleBoostSpeed:number) {
  builder.addFieldFloat32(2, recycleBoostSpeed, 0.0);
}

static addRecycleBoostLimit(builder:flatbuffers.Builder, recycleBoostLimit:bigint) {
  builder.addFieldInt64(3, recycleBoostLimit, BigInt('0'));
}

static addRecycleBoostLimitProtect(builder:flatbuffers.Builder, recycleBoostLimitProtect:bigint) {
  builder.addFieldInt64(4, recycleBoostLimitProtect, BigInt('0'));
}

static addRecycleSpeedUpUnlockLevel(builder:flatbuffers.Builder, recycleSpeedUpUnlockLevel:number) {
  builder.addFieldInt32(5, recycleSpeedUpUnlockLevel, 0);
}

static addRecycleTwoPersonUnlockLevel(builder:flatbuffers.Builder, recycleTwoPersonUnlockLevel:number) {
  builder.addFieldInt32(6, recycleTwoPersonUnlockLevel, 0);
}

static endclz_Torappu_BuildingData_RecycleRoomConsts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_BuildingData_RecycleRoomConsts(builder:flatbuffers.Builder, recycleTimeRequirement:bigint, recycleBaseCapacity:number, recycleBoostSpeed:number, recycleBoostLimit:bigint, recycleBoostLimitProtect:bigint, recycleSpeedUpUnlockLevel:number, recycleTwoPersonUnlockLevel:number):flatbuffers.Offset {
  clz_Torappu_BuildingData_RecycleRoomConsts.startclz_Torappu_BuildingData_RecycleRoomConsts(builder);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleTimeRequirement(builder, recycleTimeRequirement);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleBaseCapacity(builder, recycleBaseCapacity);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleBoostSpeed(builder, recycleBoostSpeed);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleBoostLimit(builder, recycleBoostLimit);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleBoostLimitProtect(builder, recycleBoostLimitProtect);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleSpeedUpUnlockLevel(builder, recycleSpeedUpUnlockLevel);
  clz_Torappu_BuildingData_RecycleRoomConsts.addRecycleTwoPersonUnlockLevel(builder, recycleTwoPersonUnlockLevel);
  return clz_Torappu_BuildingData_RecycleRoomConsts.endclz_Torappu_BuildingData_RecycleRoomConsts(builder);
}

unpack(): clz_Torappu_BuildingData_RecycleRoomConstsT {
  return new clz_Torappu_BuildingData_RecycleRoomConstsT(
    this.recycleTimeRequirement(),
    this.recycleBaseCapacity(),
    this.recycleBoostSpeed(),
    this.recycleBoostLimit(),
    this.recycleBoostLimitProtect(),
    this.recycleSpeedUpUnlockLevel(),
    this.recycleTwoPersonUnlockLevel()
  );
}


unpackTo(_o: clz_Torappu_BuildingData_RecycleRoomConstsT): void {
  _o.recycleTimeRequirement = this.recycleTimeRequirement();
  _o.recycleBaseCapacity = this.recycleBaseCapacity();
  _o.recycleBoostSpeed = this.recycleBoostSpeed();
  _o.recycleBoostLimit = this.recycleBoostLimit();
  _o.recycleBoostLimitProtect = this.recycleBoostLimitProtect();
  _o.recycleSpeedUpUnlockLevel = this.recycleSpeedUpUnlockLevel();
  _o.recycleTwoPersonUnlockLevel = this.recycleTwoPersonUnlockLevel();
}
}

export class clz_Torappu_BuildingData_RecycleRoomConstsT implements flatbuffers.IGeneratedObject {
constructor(
  public recycleTimeRequirement: bigint = BigInt('0'),
  public recycleBaseCapacity: number = 0,
  public recycleBoostSpeed: number = 0.0,
  public recycleBoostLimit: bigint = BigInt('0'),
  public recycleBoostLimitProtect: bigint = BigInt('0'),
  public recycleSpeedUpUnlockLevel: number = 0,
  public recycleTwoPersonUnlockLevel: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return clz_Torappu_BuildingData_RecycleRoomConsts.createclz_Torappu_BuildingData_RecycleRoomConsts(builder,
    this.recycleTimeRequirement,
    this.recycleBaseCapacity,
    this.recycleBoostSpeed,
    this.recycleBoostLimit,
    this.recycleBoostLimitProtect,
    this.recycleSpeedUpUnlockLevel,
    this.recycleTwoPersonUnlockLevel
  );
}
}
