// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_ShopRouteTarget } from './enum--torappu-shop-route-target.js';


export class clz_Torappu_ShopRecommendData implements flatbuffers.IUnpackableObject<clz_Torappu_ShopRecommendDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ShopRecommendData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ShopRecommendData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ShopRecommendData):clz_Torappu_ShopRecommendData {
  return (obj || new clz_Torappu_ShopRecommendData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ShopRecommendData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ShopRecommendData):clz_Torappu_ShopRecommendData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ShopRecommendData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

imgId():string|null
imgId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
imgId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

slotIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

cmd():enum__Torappu_ShopRouteTarget {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_ShopRouteTarget.RECOMMENDSHOP;
}

param1():string|null
param1(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
param1(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

param2():string|null
param2(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
param2(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

skinId():string|null
skinId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
skinId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_ShopRecommendData(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addImgId(builder:flatbuffers.Builder, imgIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, imgIdOffset, 0);
}

static addSlotIndex(builder:flatbuffers.Builder, slotIndex:number) {
  builder.addFieldInt32(1, slotIndex, 0);
}

static addCmd(builder:flatbuffers.Builder, cmd:enum__Torappu_ShopRouteTarget) {
  builder.addFieldInt32(2, cmd, enum__Torappu_ShopRouteTarget.RECOMMENDSHOP);
}

static addParam1(builder:flatbuffers.Builder, param1Offset:flatbuffers.Offset) {
  builder.addFieldOffset(3, param1Offset, 0);
}

static addParam2(builder:flatbuffers.Builder, param2Offset:flatbuffers.Offset) {
  builder.addFieldOffset(4, param2Offset, 0);
}

static addSkinId(builder:flatbuffers.Builder, skinIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, skinIdOffset, 0);
}

static endclz_Torappu_ShopRecommendData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ShopRecommendData(builder:flatbuffers.Builder, imgIdOffset:flatbuffers.Offset, slotIndex:number, cmd:enum__Torappu_ShopRouteTarget, param1Offset:flatbuffers.Offset, param2Offset:flatbuffers.Offset, skinIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ShopRecommendData.startclz_Torappu_ShopRecommendData(builder);
  clz_Torappu_ShopRecommendData.addImgId(builder, imgIdOffset);
  clz_Torappu_ShopRecommendData.addSlotIndex(builder, slotIndex);
  clz_Torappu_ShopRecommendData.addCmd(builder, cmd);
  clz_Torappu_ShopRecommendData.addParam1(builder, param1Offset);
  clz_Torappu_ShopRecommendData.addParam2(builder, param2Offset);
  clz_Torappu_ShopRecommendData.addSkinId(builder, skinIdOffset);
  return clz_Torappu_ShopRecommendData.endclz_Torappu_ShopRecommendData(builder);
}

unpack(): clz_Torappu_ShopRecommendDataT {
  return new clz_Torappu_ShopRecommendDataT(
    this.imgId(),
    this.slotIndex(),
    this.cmd(),
    this.param1(),
    this.param2(),
    this.skinId()
  );
}


unpackTo(_o: clz_Torappu_ShopRecommendDataT): void {
  _o.imgId = this.imgId();
  _o.slotIndex = this.slotIndex();
  _o.cmd = this.cmd();
  _o.param1 = this.param1();
  _o.param2 = this.param2();
  _o.skinId = this.skinId();
}
}

export class clz_Torappu_ShopRecommendDataT implements flatbuffers.IGeneratedObject {
constructor(
  public imgId: string|Uint8Array|null = null,
  public slotIndex: number = 0,
  public cmd: enum__Torappu_ShopRouteTarget = enum__Torappu_ShopRouteTarget.RECOMMENDSHOP,
  public param1: string|Uint8Array|null = null,
  public param2: string|Uint8Array|null = null,
  public skinId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const imgId = (this.imgId !== null ? builder.createString(this.imgId!) : 0);
  const param1 = (this.param1 !== null ? builder.createString(this.param1!) : 0);
  const param2 = (this.param2 !== null ? builder.createString(this.param2!) : 0);
  const skinId = (this.skinId !== null ? builder.createString(this.skinId!) : 0);

  return clz_Torappu_ShopRecommendData.createclz_Torappu_ShopRecommendData(builder,
    imgId,
    this.slotIndex,
    this.cmd,
    param1,
    param2,
    skinId
  );
}
}
