// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData implements flatbuffers.IUnpackableObject<clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData):clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData {
  return (obj || new clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData):clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stageId():string|null
stageId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stageId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mode(index: number):string
mode(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
mode(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

modeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

weight():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStageId(builder:flatbuffers.Builder, stageIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stageIdOffset, 0);
}

static addMode(builder:flatbuffers.Builder, modeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, modeOffset, 0);
}

static createModeVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startModeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addWeight(builder:flatbuffers.Builder, weight:number) {
  builder.addFieldInt32(2, weight, 0);
}

static endclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder:flatbuffers.Builder, stageIdOffset:flatbuffers.Offset, modeOffset:flatbuffers.Offset, weight:number):flatbuffers.Offset {
  clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.startclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder);
  clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.addStageId(builder, stageIdOffset);
  clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.addMode(builder, modeOffset);
  clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.addWeight(builder, weight);
  return clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.endclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder);
}

unpack(): clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageDataT {
  return new clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageDataT(
    this.stageId(),
    this.bb!.createScalarList<string>(this.mode.bind(this), this.modeLength()),
    this.weight()
  );
}


unpackTo(_o: clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageDataT): void {
  _o.stageId = this.stageId();
  _o.mode = this.bb!.createScalarList<string>(this.mode.bind(this), this.modeLength());
  _o.weight = this.weight();
}
}

export class clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageDataT implements flatbuffers.IGeneratedObject {
constructor(
  public stageId: string|Uint8Array|null = null,
  public mode: (string)[] = [],
  public weight: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const stageId = (this.stageId !== null ? builder.createString(this.stageId!) : 0);
  const mode = clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.createModeVector(builder, builder.createObjectOffsetList(this.mode));

  return clz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData.createclz_Torappu_ActivityAutoChessVerify1Data_Act1VAutoChessStageData(builder,
    stageId,
    mode,
    this.weight
  );
}
}
