// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { dict__string__clz_Torappu_ActArchiveFragmentItemData, dict__string__clz_Torappu_ActArchiveFragmentItemDataT } from './dict--string--clz-torappu-act-archive-fragment-item-data.js';


export class clz_Torappu_ActArchiveFragmentData implements flatbuffers.IUnpackableObject<clz_Torappu_ActArchiveFragmentDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ActArchiveFragmentData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ActArchiveFragmentData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActArchiveFragmentData):clz_Torappu_ActArchiveFragmentData {
  return (obj || new clz_Torappu_ActArchiveFragmentData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ActArchiveFragmentData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActArchiveFragmentData):clz_Torappu_ActArchiveFragmentData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ActArchiveFragmentData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fragment(index: number, obj?:dict__string__clz_Torappu_ActArchiveFragmentItemData):dict__string__clz_Torappu_ActArchiveFragmentItemData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__string__clz_Torappu_ActArchiveFragmentItemData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

fragmentLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ActArchiveFragmentData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addFragment(builder:flatbuffers.Builder, fragmentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fragmentOffset, 0);
}

static createFragmentVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFragmentVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_ActArchiveFragmentData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ActArchiveFragmentData(builder:flatbuffers.Builder, fragmentOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ActArchiveFragmentData.startclz_Torappu_ActArchiveFragmentData(builder);
  clz_Torappu_ActArchiveFragmentData.addFragment(builder, fragmentOffset);
  return clz_Torappu_ActArchiveFragmentData.endclz_Torappu_ActArchiveFragmentData(builder);
}

unpack(): clz_Torappu_ActArchiveFragmentDataT {
  return new clz_Torappu_ActArchiveFragmentDataT(
    this.bb!.createObjList<dict__string__clz_Torappu_ActArchiveFragmentItemData, dict__string__clz_Torappu_ActArchiveFragmentItemDataT>(this.fragment.bind(this), this.fragmentLength())
  );
}


unpackTo(_o: clz_Torappu_ActArchiveFragmentDataT): void {
  _o.fragment = this.bb!.createObjList<dict__string__clz_Torappu_ActArchiveFragmentItemData, dict__string__clz_Torappu_ActArchiveFragmentItemDataT>(this.fragment.bind(this), this.fragmentLength());
}
}

export class clz_Torappu_ActArchiveFragmentDataT implements flatbuffers.IGeneratedObject {
constructor(
  public fragment: (dict__string__clz_Torappu_ActArchiveFragmentItemDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const fragment = clz_Torappu_ActArchiveFragmentData.createFragmentVector(builder, builder.createObjectOffsetList(this.fragment));

  return clz_Torappu_ActArchiveFragmentData.createclz_Torappu_ActArchiveFragmentData(builder,
    fragment
  );
}
}
