// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_MedalExpireType } from './enum--torappu-medal-expire-type.js';


export class clz_Torappu_MedalExpireTime implements flatbuffers.IUnpackableObject<clz_Torappu_MedalExpireTimeT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_MedalExpireTime {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_MedalExpireTime(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MedalExpireTime):clz_Torappu_MedalExpireTime {
  return (obj || new clz_Torappu_MedalExpireTime()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_MedalExpireTime(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MedalExpireTime):clz_Torappu_MedalExpireTime {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_MedalExpireTime()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

start():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

end():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

type():enum__Torappu_MedalExpireType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_MedalExpireType.NONE;
}

static startclz_Torappu_MedalExpireTime(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addStart(builder:flatbuffers.Builder, start:bigint) {
  builder.addFieldInt64(0, start, BigInt('0'));
}

static addEnd(builder:flatbuffers.Builder, end:bigint) {
  builder.addFieldInt64(1, end, BigInt('0'));
}

static addType(builder:flatbuffers.Builder, type:enum__Torappu_MedalExpireType) {
  builder.addFieldInt32(2, type, enum__Torappu_MedalExpireType.NONE);
}

static endclz_Torappu_MedalExpireTime(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_MedalExpireTime(builder:flatbuffers.Builder, start:bigint, end:bigint, type:enum__Torappu_MedalExpireType):flatbuffers.Offset {
  clz_Torappu_MedalExpireTime.startclz_Torappu_MedalExpireTime(builder);
  clz_Torappu_MedalExpireTime.addStart(builder, start);
  clz_Torappu_MedalExpireTime.addEnd(builder, end);
  clz_Torappu_MedalExpireTime.addType(builder, type);
  return clz_Torappu_MedalExpireTime.endclz_Torappu_MedalExpireTime(builder);
}

unpack(): clz_Torappu_MedalExpireTimeT {
  return new clz_Torappu_MedalExpireTimeT(
    this.start(),
    this.end(),
    this.type()
  );
}


unpackTo(_o: clz_Torappu_MedalExpireTimeT): void {
  _o.start = this.start();
  _o.end = this.end();
  _o.type = this.type();
}
}

export class clz_Torappu_MedalExpireTimeT implements flatbuffers.IGeneratedObject {
constructor(
  public start: bigint = BigInt('0'),
  public end: bigint = BigInt('0'),
  public type: enum__Torappu_MedalExpireType = enum__Torappu_MedalExpireType.NONE
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return clz_Torappu_MedalExpireTime.createclz_Torappu_MedalExpireTime(builder,
    this.start,
    this.end,
    this.type
  );
}
}
