// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData, dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelDataT } from './dict--int--clz-torappu-roguelike-topic-detail-const-player-level-data.js';


export class clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData implements flatbuffers.IUnpackableObject<clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData):clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData {
  return (obj || new clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData):clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

levels(index: number, obj?:dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData):dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

levelsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLevels(builder:flatbuffers.Builder, levelsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, levelsOffset, 0);
}

static createLevelsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startLevelsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder:flatbuffers.Builder, levelsOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData.startclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder);
  clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData.addLevels(builder, levelsOffset);
  return clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData.endclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder);
}

unpack(): clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelDataT {
  return new clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelDataT(
    this.bb!.createObjList<dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData, dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelDataT>(this.levels.bind(this), this.levelsLength())
  );
}


unpackTo(_o: clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelDataT): void {
  _o.levels = this.bb!.createObjList<dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelData, dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelDataT>(this.levels.bind(this), this.levelsLength());
}
}

export class clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelDataT implements flatbuffers.IGeneratedObject {
constructor(
  public levels: (dict__int__clz_Torappu_RoguelikeTopicDetailConst_PlayerLevelDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const levels = clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData.createLevelsVector(builder, builder.createObjectOffsetList(this.levels));

  return clz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData.createclz_Torappu_RoguelikeTopicDetailConst_PredefinedPlayerLevelData(builder,
    levels
  );
}
}
