// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_RoguelikeGridZoneModuleConsts, clz_Torappu_RoguelikeGridZoneModuleConstsT } from './clz-torappu-roguelike-grid-zone-module-consts.js';
import { dict__string__clz_Torappu_RoguelikeBuoyItemData, dict__string__clz_Torappu_RoguelikeBuoyItemDataT } from './dict--string--clz-torappu-roguelike-buoy-item-data.js';
import { dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData, dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintDataT } from './dict--string--clz-torappu-roguelike-grid-zone-focus-view-hint-data.js';
import { dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData, dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerDataT } from './dict--string--clz-torappu-roguelike-grid-zone-mission-banner-data.js';


export class clz_Torappu_RoguelikeGridZoneModuleData implements flatbuffers.IUnpackableObject<clz_Torappu_RoguelikeGridZoneModuleDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RoguelikeGridZoneModuleData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RoguelikeGridZoneModuleData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeGridZoneModuleData):clz_Torappu_RoguelikeGridZoneModuleData {
  return (obj || new clz_Torappu_RoguelikeGridZoneModuleData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RoguelikeGridZoneModuleData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeGridZoneModuleData):clz_Torappu_RoguelikeGridZoneModuleData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RoguelikeGridZoneModuleData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

zoneMissionBannerData(index: number, obj?:dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData):dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

zoneMissionBannerDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

scrapSideBarStepZeroHintBannerData(index: number, obj?:dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData):dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

scrapSideBarStepZeroHintBannerDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

buoyItemDatas(index: number, obj?:dict__string__clz_Torappu_RoguelikeBuoyItemData):dict__string__clz_Torappu_RoguelikeBuoyItemData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new dict__string__clz_Torappu_RoguelikeBuoyItemData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

buoyItemDatasLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

moduleConsts(obj?:clz_Torappu_RoguelikeGridZoneModuleConsts):clz_Torappu_RoguelikeGridZoneModuleConsts|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new clz_Torappu_RoguelikeGridZoneModuleConsts()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startclz_Torappu_RoguelikeGridZoneModuleData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addZoneMissionBannerData(builder:flatbuffers.Builder, zoneMissionBannerDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, zoneMissionBannerDataOffset, 0);
}

static createZoneMissionBannerDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startZoneMissionBannerDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addScrapSideBarStepZeroHintBannerData(builder:flatbuffers.Builder, scrapSideBarStepZeroHintBannerDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, scrapSideBarStepZeroHintBannerDataOffset, 0);
}

static createScrapSideBarStepZeroHintBannerDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startScrapSideBarStepZeroHintBannerDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addBuoyItemDatas(builder:flatbuffers.Builder, buoyItemDatasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, buoyItemDatasOffset, 0);
}

static createBuoyItemDatasVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBuoyItemDatasVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addModuleConsts(builder:flatbuffers.Builder, moduleConstsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, moduleConstsOffset, 0);
}

static endclz_Torappu_RoguelikeGridZoneModuleData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): clz_Torappu_RoguelikeGridZoneModuleDataT {
  return new clz_Torappu_RoguelikeGridZoneModuleDataT(
    this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData, dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerDataT>(this.zoneMissionBannerData.bind(this), this.zoneMissionBannerDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData, dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintDataT>(this.scrapSideBarStepZeroHintBannerData.bind(this), this.scrapSideBarStepZeroHintBannerDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeBuoyItemData, dict__string__clz_Torappu_RoguelikeBuoyItemDataT>(this.buoyItemDatas.bind(this), this.buoyItemDatasLength()),
    (this.moduleConsts() !== null ? this.moduleConsts()!.unpack() : null)
  );
}


unpackTo(_o: clz_Torappu_RoguelikeGridZoneModuleDataT): void {
  _o.zoneMissionBannerData = this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerData, dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerDataT>(this.zoneMissionBannerData.bind(this), this.zoneMissionBannerDataLength());
  _o.scrapSideBarStepZeroHintBannerData = this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintData, dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintDataT>(this.scrapSideBarStepZeroHintBannerData.bind(this), this.scrapSideBarStepZeroHintBannerDataLength());
  _o.buoyItemDatas = this.bb!.createObjList<dict__string__clz_Torappu_RoguelikeBuoyItemData, dict__string__clz_Torappu_RoguelikeBuoyItemDataT>(this.buoyItemDatas.bind(this), this.buoyItemDatasLength());
  _o.moduleConsts = (this.moduleConsts() !== null ? this.moduleConsts()!.unpack() : null);
}
}

export class clz_Torappu_RoguelikeGridZoneModuleDataT implements flatbuffers.IGeneratedObject {
constructor(
  public zoneMissionBannerData: (dict__string__clz_Torappu_RoguelikeGridZoneMissionBannerDataT)[] = [],
  public scrapSideBarStepZeroHintBannerData: (dict__string__clz_Torappu_RoguelikeGridZoneFocusViewHintDataT)[] = [],
  public buoyItemDatas: (dict__string__clz_Torappu_RoguelikeBuoyItemDataT)[] = [],
  public moduleConsts: clz_Torappu_RoguelikeGridZoneModuleConstsT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const zoneMissionBannerData = clz_Torappu_RoguelikeGridZoneModuleData.createZoneMissionBannerDataVector(builder, builder.createObjectOffsetList(this.zoneMissionBannerData));
  const scrapSideBarStepZeroHintBannerData = clz_Torappu_RoguelikeGridZoneModuleData.createScrapSideBarStepZeroHintBannerDataVector(builder, builder.createObjectOffsetList(this.scrapSideBarStepZeroHintBannerData));
  const buoyItemDatas = clz_Torappu_RoguelikeGridZoneModuleData.createBuoyItemDatasVector(builder, builder.createObjectOffsetList(this.buoyItemDatas));
  const moduleConsts = (this.moduleConsts !== null ? this.moduleConsts!.pack(builder) : 0);

  clz_Torappu_RoguelikeGridZoneModuleData.startclz_Torappu_RoguelikeGridZoneModuleData(builder);
  clz_Torappu_RoguelikeGridZoneModuleData.addZoneMissionBannerData(builder, zoneMissionBannerData);
  clz_Torappu_RoguelikeGridZoneModuleData.addScrapSideBarStepZeroHintBannerData(builder, scrapSideBarStepZeroHintBannerData);
  clz_Torappu_RoguelikeGridZoneModuleData.addBuoyItemDatas(builder, buoyItemDatas);
  clz_Torappu_RoguelikeGridZoneModuleData.addModuleConsts(builder, moduleConsts);

  return clz_Torappu_RoguelikeGridZoneModuleData.endclz_Torappu_RoguelikeGridZoneModuleData(builder);
}
}
