// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act4funEndingInfo implements flatbuffers.IUnpackableObject<clz_Torappu_Act4funEndingInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act4funEndingInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act4funEndingInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act4funEndingInfo):clz_Torappu_Act4funEndingInfo {
  return (obj || new clz_Torappu_Act4funEndingInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act4funEndingInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act4funEndingInfo):clz_Torappu_Act4funEndingInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act4funEndingInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

endingId():string|null
endingId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
endingId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

endingAvg():string|null
endingAvg(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
endingAvg(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

endingDesc():string|null
endingDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
endingDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

stageId():string|null
stageId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
stageId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isGoodEnding():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startclz_Torappu_Act4funEndingInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addEndingId(builder:flatbuffers.Builder, endingIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, endingIdOffset, 0);
}

static addEndingAvg(builder:flatbuffers.Builder, endingAvgOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, endingAvgOffset, 0);
}

static addEndingDesc(builder:flatbuffers.Builder, endingDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, endingDescOffset, 0);
}

static addStageId(builder:flatbuffers.Builder, stageIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, stageIdOffset, 0);
}

static addIsGoodEnding(builder:flatbuffers.Builder, isGoodEnding:boolean) {
  builder.addFieldInt8(4, +isGoodEnding, +false);
}

static endclz_Torappu_Act4funEndingInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act4funEndingInfo(builder:flatbuffers.Builder, endingIdOffset:flatbuffers.Offset, endingAvgOffset:flatbuffers.Offset, endingDescOffset:flatbuffers.Offset, stageIdOffset:flatbuffers.Offset, isGoodEnding:boolean):flatbuffers.Offset {
  clz_Torappu_Act4funEndingInfo.startclz_Torappu_Act4funEndingInfo(builder);
  clz_Torappu_Act4funEndingInfo.addEndingId(builder, endingIdOffset);
  clz_Torappu_Act4funEndingInfo.addEndingAvg(builder, endingAvgOffset);
  clz_Torappu_Act4funEndingInfo.addEndingDesc(builder, endingDescOffset);
  clz_Torappu_Act4funEndingInfo.addStageId(builder, stageIdOffset);
  clz_Torappu_Act4funEndingInfo.addIsGoodEnding(builder, isGoodEnding);
  return clz_Torappu_Act4funEndingInfo.endclz_Torappu_Act4funEndingInfo(builder);
}

unpack(): clz_Torappu_Act4funEndingInfoT {
  return new clz_Torappu_Act4funEndingInfoT(
    this.endingId(),
    this.endingAvg(),
    this.endingDesc(),
    this.stageId(),
    this.isGoodEnding()
  );
}


unpackTo(_o: clz_Torappu_Act4funEndingInfoT): void {
  _o.endingId = this.endingId();
  _o.endingAvg = this.endingAvg();
  _o.endingDesc = this.endingDesc();
  _o.stageId = this.stageId();
  _o.isGoodEnding = this.isGoodEnding();
}
}

export class clz_Torappu_Act4funEndingInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public endingId: string|Uint8Array|null = null,
  public endingAvg: string|Uint8Array|null = null,
  public endingDesc: string|Uint8Array|null = null,
  public stageId: string|Uint8Array|null = null,
  public isGoodEnding: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const endingId = (this.endingId !== null ? builder.createString(this.endingId!) : 0);
  const endingAvg = (this.endingAvg !== null ? builder.createString(this.endingAvg!) : 0);
  const endingDesc = (this.endingDesc !== null ? builder.createString(this.endingDesc!) : 0);
  const stageId = (this.stageId !== null ? builder.createString(this.stageId!) : 0);

  return clz_Torappu_Act4funEndingInfo.createclz_Torappu_Act4funEndingInfo(builder,
    endingId,
    endingAvg,
    endingDesc,
    stageId,
    this.isGoodEnding
  );
}
}
