// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData, dict__string__clz_Torappu_ArkOdcTaskTrackingEntryDataT } from './dict--string--clz-torappu-ark-odc-task-tracking-entry-data.js';


export class clz_Torappu_ArkOdcTaskTrackingMainData implements flatbuffers.IUnpackableObject<clz_Torappu_ArkOdcTaskTrackingMainDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ArkOdcTaskTrackingMainData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ArkOdcTaskTrackingMainData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ArkOdcTaskTrackingMainData):clz_Torappu_ArkOdcTaskTrackingMainData {
  return (obj || new clz_Torappu_ArkOdcTaskTrackingMainData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ArkOdcTaskTrackingMainData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ArkOdcTaskTrackingMainData):clz_Torappu_ArkOdcTaskTrackingMainData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ArkOdcTaskTrackingMainData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

questId():string|null
questId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

priority():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

startBannerDesc():string|null
startBannerDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
startBannerDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

completeBannerDesc():string|null
completeBannerDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
completeBannerDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

entryDict(index: number, obj?:dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData):dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

entryDictLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ArkOdcTaskTrackingMainData(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addQuestId(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, questIdOffset, 0);
}

static addPriority(builder:flatbuffers.Builder, priority:number) {
  builder.addFieldInt32(1, priority, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, titleOffset, 0);
}

static addStartBannerDesc(builder:flatbuffers.Builder, startBannerDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, startBannerDescOffset, 0);
}

static addCompleteBannerDesc(builder:flatbuffers.Builder, completeBannerDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, completeBannerDescOffset, 0);
}

static addEntryDict(builder:flatbuffers.Builder, entryDictOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, entryDictOffset, 0);
}

static createEntryDictVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEntryDictVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_ArkOdcTaskTrackingMainData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ArkOdcTaskTrackingMainData(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset, priority:number, titleOffset:flatbuffers.Offset, startBannerDescOffset:flatbuffers.Offset, completeBannerDescOffset:flatbuffers.Offset, entryDictOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ArkOdcTaskTrackingMainData.startclz_Torappu_ArkOdcTaskTrackingMainData(builder);
  clz_Torappu_ArkOdcTaskTrackingMainData.addQuestId(builder, questIdOffset);
  clz_Torappu_ArkOdcTaskTrackingMainData.addPriority(builder, priority);
  clz_Torappu_ArkOdcTaskTrackingMainData.addTitle(builder, titleOffset);
  clz_Torappu_ArkOdcTaskTrackingMainData.addStartBannerDesc(builder, startBannerDescOffset);
  clz_Torappu_ArkOdcTaskTrackingMainData.addCompleteBannerDesc(builder, completeBannerDescOffset);
  clz_Torappu_ArkOdcTaskTrackingMainData.addEntryDict(builder, entryDictOffset);
  return clz_Torappu_ArkOdcTaskTrackingMainData.endclz_Torappu_ArkOdcTaskTrackingMainData(builder);
}

unpack(): clz_Torappu_ArkOdcTaskTrackingMainDataT {
  return new clz_Torappu_ArkOdcTaskTrackingMainDataT(
    this.questId(),
    this.priority(),
    this.title(),
    this.startBannerDesc(),
    this.completeBannerDesc(),
    this.bb!.createObjList<dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData, dict__string__clz_Torappu_ArkOdcTaskTrackingEntryDataT>(this.entryDict.bind(this), this.entryDictLength())
  );
}


unpackTo(_o: clz_Torappu_ArkOdcTaskTrackingMainDataT): void {
  _o.questId = this.questId();
  _o.priority = this.priority();
  _o.title = this.title();
  _o.startBannerDesc = this.startBannerDesc();
  _o.completeBannerDesc = this.completeBannerDesc();
  _o.entryDict = this.bb!.createObjList<dict__string__clz_Torappu_ArkOdcTaskTrackingEntryData, dict__string__clz_Torappu_ArkOdcTaskTrackingEntryDataT>(this.entryDict.bind(this), this.entryDictLength());
}
}

export class clz_Torappu_ArkOdcTaskTrackingMainDataT implements flatbuffers.IGeneratedObject {
constructor(
  public questId: string|Uint8Array|null = null,
  public priority: number = 0,
  public title: string|Uint8Array|null = null,
  public startBannerDesc: string|Uint8Array|null = null,
  public completeBannerDesc: string|Uint8Array|null = null,
  public entryDict: (dict__string__clz_Torappu_ArkOdcTaskTrackingEntryDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const questId = (this.questId !== null ? builder.createString(this.questId!) : 0);
  const title = (this.title !== null ? builder.createString(this.title!) : 0);
  const startBannerDesc = (this.startBannerDesc !== null ? builder.createString(this.startBannerDesc!) : 0);
  const completeBannerDesc = (this.completeBannerDesc !== null ? builder.createString(this.completeBannerDesc!) : 0);
  const entryDict = clz_Torappu_ArkOdcTaskTrackingMainData.createEntryDictVector(builder, builder.createObjectOffsetList(this.entryDict));

  return clz_Torappu_ArkOdcTaskTrackingMainData.createclz_Torappu_ArkOdcTaskTrackingMainData(builder,
    questId,
    this.priority,
    title,
    startBannerDesc,
    completeBannerDesc,
    entryDict
  );
}
}
