// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_MagazineLeafTypeData implements flatbuffers.IUnpackableObject<clz_Torappu_MagazineLeafTypeDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_MagazineLeafTypeData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_MagazineLeafTypeData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MagazineLeafTypeData):clz_Torappu_MagazineLeafTypeData {
  return (obj || new clz_Torappu_MagazineLeafTypeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_MagazineLeafTypeData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MagazineLeafTypeData):clz_Torappu_MagazineLeafTypeData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_MagazineLeafTypeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

engName():string|null
engName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
engName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

typeIconId():string|null
typeIconId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
typeIconId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_MagazineLeafTypeData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEngName(builder:flatbuffers.Builder, engNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, engNameOffset, 0);
}

static addTypeIconId(builder:flatbuffers.Builder, typeIconIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, typeIconIdOffset, 0);
}

static endclz_Torappu_MagazineLeafTypeData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_MagazineLeafTypeData(builder:flatbuffers.Builder, engNameOffset:flatbuffers.Offset, typeIconIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_MagazineLeafTypeData.startclz_Torappu_MagazineLeafTypeData(builder);
  clz_Torappu_MagazineLeafTypeData.addEngName(builder, engNameOffset);
  clz_Torappu_MagazineLeafTypeData.addTypeIconId(builder, typeIconIdOffset);
  return clz_Torappu_MagazineLeafTypeData.endclz_Torappu_MagazineLeafTypeData(builder);
}

unpack(): clz_Torappu_MagazineLeafTypeDataT {
  return new clz_Torappu_MagazineLeafTypeDataT(
    this.engName(),
    this.typeIconId()
  );
}


unpackTo(_o: clz_Torappu_MagazineLeafTypeDataT): void {
  _o.engName = this.engName();
  _o.typeIconId = this.typeIconId();
}
}

export class clz_Torappu_MagazineLeafTypeDataT implements flatbuffers.IGeneratedObject {
constructor(
  public engName: string|Uint8Array|null = null,
  public typeIconId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const engName = (this.engName !== null ? builder.createString(this.engName!) : 0);
  const typeIconId = (this.typeIconId !== null ? builder.createString(this.typeIconId!) : 0);

  return clz_Torappu_MagazineLeafTypeData.createclz_Torappu_MagazineLeafTypeData(builder,
    engName,
    typeIconId
  );
}
}
