// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_ItemBundle, clz_Torappu_ItemBundleT } from './clz-torappu-item-bundle.js';
import { enum__Torappu_MileStoneInfo_GoodType } from './enum--torappu-mile-stone-info-good-type.js';


export class clz_Torappu_MileStoneInfo implements flatbuffers.IUnpackableObject<clz_Torappu_MileStoneInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_MileStoneInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_MileStoneInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MileStoneInfo):clz_Torappu_MileStoneInfo {
  return (obj || new clz_Torappu_MileStoneInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_MileStoneInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_MileStoneInfo):clz_Torappu_MileStoneInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_MileStoneInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mileStoneId():string|null
mileStoneId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mileStoneId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

orderId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

tokenNum():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mileStoneType():enum__Torappu_MileStoneInfo_GoodType {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_MileStoneInfo_GoodType.NORMAL;
}

normalItem(obj?:clz_Torappu_ItemBundle):clz_Torappu_ItemBundle|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new clz_Torappu_ItemBundle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

isBonus():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_MileStoneInfo(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addMileStoneId(builder:flatbuffers.Builder, mileStoneIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, mileStoneIdOffset, 0);
}

static addOrderId(builder:flatbuffers.Builder, orderId:number) {
  builder.addFieldInt32(1, orderId, 0);
}

static addTokenNum(builder:flatbuffers.Builder, tokenNum:number) {
  builder.addFieldInt32(2, tokenNum, 0);
}

static addMileStoneType(builder:flatbuffers.Builder, mileStoneType:enum__Torappu_MileStoneInfo_GoodType) {
  builder.addFieldInt32(3, mileStoneType, enum__Torappu_MileStoneInfo_GoodType.NORMAL);
}

static addNormalItem(builder:flatbuffers.Builder, normalItemOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, normalItemOffset, 0);
}

static addIsBonus(builder:flatbuffers.Builder, isBonus:number) {
  builder.addFieldInt32(5, isBonus, 0);
}

static endclz_Torappu_MileStoneInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): clz_Torappu_MileStoneInfoT {
  return new clz_Torappu_MileStoneInfoT(
    this.mileStoneId(),
    this.orderId(),
    this.tokenNum(),
    this.mileStoneType(),
    (this.normalItem() !== null ? this.normalItem()!.unpack() : null),
    this.isBonus()
  );
}


unpackTo(_o: clz_Torappu_MileStoneInfoT): void {
  _o.mileStoneId = this.mileStoneId();
  _o.orderId = this.orderId();
  _o.tokenNum = this.tokenNum();
  _o.mileStoneType = this.mileStoneType();
  _o.normalItem = (this.normalItem() !== null ? this.normalItem()!.unpack() : null);
  _o.isBonus = this.isBonus();
}
}

export class clz_Torappu_MileStoneInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public mileStoneId: string|Uint8Array|null = null,
  public orderId: number = 0,
  public tokenNum: number = 0,
  public mileStoneType: enum__Torappu_MileStoneInfo_GoodType = enum__Torappu_MileStoneInfo_GoodType.NORMAL,
  public normalItem: clz_Torappu_ItemBundleT|null = null,
  public isBonus: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const mileStoneId = (this.mileStoneId !== null ? builder.createString(this.mileStoneId!) : 0);
  const normalItem = (this.normalItem !== null ? this.normalItem!.pack(builder) : 0);

  clz_Torappu_MileStoneInfo.startclz_Torappu_MileStoneInfo(builder);
  clz_Torappu_MileStoneInfo.addMileStoneId(builder, mileStoneId);
  clz_Torappu_MileStoneInfo.addOrderId(builder, this.orderId);
  clz_Torappu_MileStoneInfo.addTokenNum(builder, this.tokenNum);
  clz_Torappu_MileStoneInfo.addMileStoneType(builder, this.mileStoneType);
  clz_Torappu_MileStoneInfo.addNormalItem(builder, normalItem);
  clz_Torappu_MileStoneInfo.addIsBonus(builder, this.isBonus);

  return clz_Torappu_MileStoneInfo.endclz_Torappu_MileStoneInfo(builder);
}
}
