// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_SandboxV2ArchiveAchievementData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxV2ArchiveAchievementDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxV2ArchiveAchievementData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxV2ArchiveAchievementData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2ArchiveAchievementData):clz_Torappu_SandboxV2ArchiveAchievementData {
  return (obj || new clz_Torappu_SandboxV2ArchiveAchievementData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxV2ArchiveAchievementData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2ArchiveAchievementData):clz_Torappu_SandboxV2ArchiveAchievementData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxV2ArchiveAchievementData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

achievementType(index: number):string
achievementType(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
achievementType(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

achievementTypeLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

raritySortId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

sortId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

desc():string|null
desc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
desc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_SandboxV2ArchiveAchievementData(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addAchievementType(builder:flatbuffers.Builder, achievementTypeOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, achievementTypeOffset, 0);
}

static createAchievementTypeVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAchievementTypeVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRaritySortId(builder:flatbuffers.Builder, raritySortId:number) {
  builder.addFieldInt32(2, raritySortId, 0);
}

static addSortId(builder:flatbuffers.Builder, sortId:number) {
  builder.addFieldInt32(3, sortId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, nameOffset, 0);
}

static addDesc(builder:flatbuffers.Builder, descOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, descOffset, 0);
}

static endclz_Torappu_SandboxV2ArchiveAchievementData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxV2ArchiveAchievementData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, achievementTypeOffset:flatbuffers.Offset, raritySortId:number, sortId:number, nameOffset:flatbuffers.Offset, descOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_SandboxV2ArchiveAchievementData.startclz_Torappu_SandboxV2ArchiveAchievementData(builder);
  clz_Torappu_SandboxV2ArchiveAchievementData.addId(builder, idOffset);
  clz_Torappu_SandboxV2ArchiveAchievementData.addAchievementType(builder, achievementTypeOffset);
  clz_Torappu_SandboxV2ArchiveAchievementData.addRaritySortId(builder, raritySortId);
  clz_Torappu_SandboxV2ArchiveAchievementData.addSortId(builder, sortId);
  clz_Torappu_SandboxV2ArchiveAchievementData.addName(builder, nameOffset);
  clz_Torappu_SandboxV2ArchiveAchievementData.addDesc(builder, descOffset);
  return clz_Torappu_SandboxV2ArchiveAchievementData.endclz_Torappu_SandboxV2ArchiveAchievementData(builder);
}

unpack(): clz_Torappu_SandboxV2ArchiveAchievementDataT {
  return new clz_Torappu_SandboxV2ArchiveAchievementDataT(
    this.id(),
    this.bb!.createScalarList<string>(this.achievementType.bind(this), this.achievementTypeLength()),
    this.raritySortId(),
    this.sortId(),
    this.name(),
    this.desc()
  );
}


unpackTo(_o: clz_Torappu_SandboxV2ArchiveAchievementDataT): void {
  _o.id = this.id();
  _o.achievementType = this.bb!.createScalarList<string>(this.achievementType.bind(this), this.achievementTypeLength());
  _o.raritySortId = this.raritySortId();
  _o.sortId = this.sortId();
  _o.name = this.name();
  _o.desc = this.desc();
}
}

export class clz_Torappu_SandboxV2ArchiveAchievementDataT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public achievementType: (string)[] = [],
  public raritySortId: number = 0,
  public sortId: number = 0,
  public name: string|Uint8Array|null = null,
  public desc: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const achievementType = clz_Torappu_SandboxV2ArchiveAchievementData.createAchievementTypeVector(builder, builder.createObjectOffsetList(this.achievementType));
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const desc = (this.desc !== null ? builder.createString(this.desc!) : 0);

  return clz_Torappu_SandboxV2ArchiveAchievementData.createclz_Torappu_SandboxV2ArchiveAchievementData(builder,
    id,
    achievementType,
    this.raritySortId,
    this.sortId,
    name,
    desc
  );
}
}
