// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act25SideData_KeyData implements flatbuffers.IUnpackableObject<clz_Torappu_Act25SideData_KeyDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act25SideData_KeyData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act25SideData_KeyData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act25SideData_KeyData):clz_Torappu_Act25SideData_KeyData {
  return (obj || new clz_Torappu_Act25SideData_KeyData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act25SideData_KeyData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act25SideData_KeyData):clz_Torappu_Act25SideData_KeyData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act25SideData_KeyData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

keyId():string|null
keyId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
keyId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

keyName():string|null
keyName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
keyName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

keyIcon():string|null
keyIcon(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
keyIcon(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

toastText():string|null
toastText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
toastText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_Act25SideData_KeyData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addKeyId(builder:flatbuffers.Builder, keyIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyIdOffset, 0);
}

static addKeyName(builder:flatbuffers.Builder, keyNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyNameOffset, 0);
}

static addKeyIcon(builder:flatbuffers.Builder, keyIconOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, keyIconOffset, 0);
}

static addToastText(builder:flatbuffers.Builder, toastTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, toastTextOffset, 0);
}

static endclz_Torappu_Act25SideData_KeyData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act25SideData_KeyData(builder:flatbuffers.Builder, keyIdOffset:flatbuffers.Offset, keyNameOffset:flatbuffers.Offset, keyIconOffset:flatbuffers.Offset, toastTextOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_Act25SideData_KeyData.startclz_Torappu_Act25SideData_KeyData(builder);
  clz_Torappu_Act25SideData_KeyData.addKeyId(builder, keyIdOffset);
  clz_Torappu_Act25SideData_KeyData.addKeyName(builder, keyNameOffset);
  clz_Torappu_Act25SideData_KeyData.addKeyIcon(builder, keyIconOffset);
  clz_Torappu_Act25SideData_KeyData.addToastText(builder, toastTextOffset);
  return clz_Torappu_Act25SideData_KeyData.endclz_Torappu_Act25SideData_KeyData(builder);
}

unpack(): clz_Torappu_Act25SideData_KeyDataT {
  return new clz_Torappu_Act25SideData_KeyDataT(
    this.keyId(),
    this.keyName(),
    this.keyIcon(),
    this.toastText()
  );
}


unpackTo(_o: clz_Torappu_Act25SideData_KeyDataT): void {
  _o.keyId = this.keyId();
  _o.keyName = this.keyName();
  _o.keyIcon = this.keyIcon();
  _o.toastText = this.toastText();
}
}

export class clz_Torappu_Act25SideData_KeyDataT implements flatbuffers.IGeneratedObject {
constructor(
  public keyId: string|Uint8Array|null = null,
  public keyName: string|Uint8Array|null = null,
  public keyIcon: string|Uint8Array|null = null,
  public toastText: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const keyId = (this.keyId !== null ? builder.createString(this.keyId!) : 0);
  const keyName = (this.keyName !== null ? builder.createString(this.keyName!) : 0);
  const keyIcon = (this.keyIcon !== null ? builder.createString(this.keyIcon!) : 0);
  const toastText = (this.toastText !== null ? builder.createString(this.toastText!) : 0);

  return clz_Torappu_Act25SideData_KeyData.createclz_Torappu_Act25SideData_KeyData(builder,
    keyId,
    keyName,
    keyIcon,
    toastText
  );
}
}
