// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_ActArkHubRewardItem, clz_Torappu_ActArkHubRewardItemT } from './clz-torappu-act-ark-hub-reward-item.js';


export class clz_Torappu_ActArkHubRewardData implements flatbuffers.IUnpackableObject<clz_Torappu_ActArkHubRewardDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ActArkHubRewardData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ActArkHubRewardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActArkHubRewardData):clz_Torappu_ActArkHubRewardData {
  return (obj || new clz_Torappu_ActArkHubRewardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ActArkHubRewardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActArkHubRewardData):clz_Torappu_ActArkHubRewardData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ActArkHubRewardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rewardId():string|null
rewardId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rewardId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

itemList(index: number, obj?:clz_Torappu_ActArkHubRewardItem):clz_Torappu_ActArkHubRewardItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_ActArkHubRewardItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

itemListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ActArkHubRewardData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRewardId(builder:flatbuffers.Builder, rewardIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, rewardIdOffset, 0);
}

static addItemList(builder:flatbuffers.Builder, itemListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, itemListOffset, 0);
}

static createItemListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startItemListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_ActArkHubRewardData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ActArkHubRewardData(builder:flatbuffers.Builder, rewardIdOffset:flatbuffers.Offset, itemListOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ActArkHubRewardData.startclz_Torappu_ActArkHubRewardData(builder);
  clz_Torappu_ActArkHubRewardData.addRewardId(builder, rewardIdOffset);
  clz_Torappu_ActArkHubRewardData.addItemList(builder, itemListOffset);
  return clz_Torappu_ActArkHubRewardData.endclz_Torappu_ActArkHubRewardData(builder);
}

unpack(): clz_Torappu_ActArkHubRewardDataT {
  return new clz_Torappu_ActArkHubRewardDataT(
    this.rewardId(),
    this.bb!.createObjList<clz_Torappu_ActArkHubRewardItem, clz_Torappu_ActArkHubRewardItemT>(this.itemList.bind(this), this.itemListLength())
  );
}


unpackTo(_o: clz_Torappu_ActArkHubRewardDataT): void {
  _o.rewardId = this.rewardId();
  _o.itemList = this.bb!.createObjList<clz_Torappu_ActArkHubRewardItem, clz_Torappu_ActArkHubRewardItemT>(this.itemList.bind(this), this.itemListLength());
}
}

export class clz_Torappu_ActArkHubRewardDataT implements flatbuffers.IGeneratedObject {
constructor(
  public rewardId: string|Uint8Array|null = null,
  public itemList: (clz_Torappu_ActArkHubRewardItemT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const rewardId = (this.rewardId !== null ? builder.createString(this.rewardId!) : 0);
  const itemList = clz_Torappu_ActArkHubRewardData.createItemListVector(builder, builder.createObjectOffsetList(this.itemList));

  return clz_Torappu_ActArkHubRewardData.createclz_Torappu_ActArkHubRewardData(builder,
    rewardId,
    itemList
  );
}
}
