// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act54SideData_Act54SideCardData implements flatbuffers.IUnpackableObject<clz_Torappu_Act54SideData_Act54SideCardDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act54SideData_Act54SideCardData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act54SideData_Act54SideCardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act54SideData_Act54SideCardData):clz_Torappu_Act54SideData_Act54SideCardData {
  return (obj || new clz_Torappu_Act54SideData_Act54SideCardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act54SideData_Act54SideCardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act54SideData_Act54SideCardData):clz_Torappu_Act54SideData_Act54SideCardData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act54SideData_Act54SideCardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

cardId():string|null
cardId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
cardId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

sortId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

charName():string|null
charName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
charName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

descUpright():string|null
descUpright(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
descUpright(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

descReverse():string|null
descReverse(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
descReverse(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

unlockStageId():string|null
unlockStageId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
unlockStageId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_Act54SideData_Act54SideCardData(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addCardId(builder:flatbuffers.Builder, cardIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, cardIdOffset, 0);
}

static addSortId(builder:flatbuffers.Builder, sortId:number) {
  builder.addFieldInt32(1, sortId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addCharName(builder:flatbuffers.Builder, charNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, charNameOffset, 0);
}

static addDescUpright(builder:flatbuffers.Builder, descUprightOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, descUprightOffset, 0);
}

static addDescReverse(builder:flatbuffers.Builder, descReverseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, descReverseOffset, 0);
}

static addUnlockStageId(builder:flatbuffers.Builder, unlockStageIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, unlockStageIdOffset, 0);
}

static endclz_Torappu_Act54SideData_Act54SideCardData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act54SideData_Act54SideCardData(builder:flatbuffers.Builder, cardIdOffset:flatbuffers.Offset, sortId:number, nameOffset:flatbuffers.Offset, charNameOffset:flatbuffers.Offset, descUprightOffset:flatbuffers.Offset, descReverseOffset:flatbuffers.Offset, unlockStageIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_Act54SideData_Act54SideCardData.startclz_Torappu_Act54SideData_Act54SideCardData(builder);
  clz_Torappu_Act54SideData_Act54SideCardData.addCardId(builder, cardIdOffset);
  clz_Torappu_Act54SideData_Act54SideCardData.addSortId(builder, sortId);
  clz_Torappu_Act54SideData_Act54SideCardData.addName(builder, nameOffset);
  clz_Torappu_Act54SideData_Act54SideCardData.addCharName(builder, charNameOffset);
  clz_Torappu_Act54SideData_Act54SideCardData.addDescUpright(builder, descUprightOffset);
  clz_Torappu_Act54SideData_Act54SideCardData.addDescReverse(builder, descReverseOffset);
  clz_Torappu_Act54SideData_Act54SideCardData.addUnlockStageId(builder, unlockStageIdOffset);
  return clz_Torappu_Act54SideData_Act54SideCardData.endclz_Torappu_Act54SideData_Act54SideCardData(builder);
}

unpack(): clz_Torappu_Act54SideData_Act54SideCardDataT {
  return new clz_Torappu_Act54SideData_Act54SideCardDataT(
    this.cardId(),
    this.sortId(),
    this.name(),
    this.charName(),
    this.descUpright(),
    this.descReverse(),
    this.unlockStageId()
  );
}


unpackTo(_o: clz_Torappu_Act54SideData_Act54SideCardDataT): void {
  _o.cardId = this.cardId();
  _o.sortId = this.sortId();
  _o.name = this.name();
  _o.charName = this.charName();
  _o.descUpright = this.descUpright();
  _o.descReverse = this.descReverse();
  _o.unlockStageId = this.unlockStageId();
}
}

export class clz_Torappu_Act54SideData_Act54SideCardDataT implements flatbuffers.IGeneratedObject {
constructor(
  public cardId: string|Uint8Array|null = null,
  public sortId: number = 0,
  public name: string|Uint8Array|null = null,
  public charName: string|Uint8Array|null = null,
  public descUpright: string|Uint8Array|null = null,
  public descReverse: string|Uint8Array|null = null,
  public unlockStageId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const cardId = (this.cardId !== null ? builder.createString(this.cardId!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const charName = (this.charName !== null ? builder.createString(this.charName!) : 0);
  const descUpright = (this.descUpright !== null ? builder.createString(this.descUpright!) : 0);
  const descReverse = (this.descReverse !== null ? builder.createString(this.descReverse!) : 0);
  const unlockStageId = (this.unlockStageId !== null ? builder.createString(this.unlockStageId!) : 0);

  return clz_Torappu_Act54SideData_Act54SideCardData.createclz_Torappu_Act54SideData_Act54SideCardData(builder,
    cardId,
    this.sortId,
    name,
    charName,
    descUpright,
    descReverse,
    unlockStageId
  );
}
}
