// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act12SideData_PhotoInfo implements flatbuffers.IUnpackableObject<clz_Torappu_Act12SideData_PhotoInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act12SideData_PhotoInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act12SideData_PhotoInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act12SideData_PhotoInfo):clz_Torappu_Act12SideData_PhotoInfo {
  return (obj || new clz_Torappu_Act12SideData_PhotoInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act12SideData_PhotoInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act12SideData_PhotoInfo):clz_Torappu_Act12SideData_PhotoInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act12SideData_PhotoInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

picId():string|null
picId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
picId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

picName():string|null
picName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
picName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mileStoneId():string|null
mileStoneId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mileStoneId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

picDesc():string|null
picDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
picDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

jumpStageId():string|null
jumpStageId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
jumpStageId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_Act12SideData_PhotoInfo(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addPicId(builder:flatbuffers.Builder, picIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, picIdOffset, 0);
}

static addPicName(builder:flatbuffers.Builder, picNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, picNameOffset, 0);
}

static addMileStoneId(builder:flatbuffers.Builder, mileStoneIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, mileStoneIdOffset, 0);
}

static addPicDesc(builder:flatbuffers.Builder, picDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, picDescOffset, 0);
}

static addJumpStageId(builder:flatbuffers.Builder, jumpStageIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, jumpStageIdOffset, 0);
}

static endclz_Torappu_Act12SideData_PhotoInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act12SideData_PhotoInfo(builder:flatbuffers.Builder, picIdOffset:flatbuffers.Offset, picNameOffset:flatbuffers.Offset, mileStoneIdOffset:flatbuffers.Offset, picDescOffset:flatbuffers.Offset, jumpStageIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_Act12SideData_PhotoInfo.startclz_Torappu_Act12SideData_PhotoInfo(builder);
  clz_Torappu_Act12SideData_PhotoInfo.addPicId(builder, picIdOffset);
  clz_Torappu_Act12SideData_PhotoInfo.addPicName(builder, picNameOffset);
  clz_Torappu_Act12SideData_PhotoInfo.addMileStoneId(builder, mileStoneIdOffset);
  clz_Torappu_Act12SideData_PhotoInfo.addPicDesc(builder, picDescOffset);
  clz_Torappu_Act12SideData_PhotoInfo.addJumpStageId(builder, jumpStageIdOffset);
  return clz_Torappu_Act12SideData_PhotoInfo.endclz_Torappu_Act12SideData_PhotoInfo(builder);
}

unpack(): clz_Torappu_Act12SideData_PhotoInfoT {
  return new clz_Torappu_Act12SideData_PhotoInfoT(
    this.picId(),
    this.picName(),
    this.mileStoneId(),
    this.picDesc(),
    this.jumpStageId()
  );
}


unpackTo(_o: clz_Torappu_Act12SideData_PhotoInfoT): void {
  _o.picId = this.picId();
  _o.picName = this.picName();
  _o.mileStoneId = this.mileStoneId();
  _o.picDesc = this.picDesc();
  _o.jumpStageId = this.jumpStageId();
}
}

export class clz_Torappu_Act12SideData_PhotoInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public picId: string|Uint8Array|null = null,
  public picName: string|Uint8Array|null = null,
  public mileStoneId: string|Uint8Array|null = null,
  public picDesc: string|Uint8Array|null = null,
  public jumpStageId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const picId = (this.picId !== null ? builder.createString(this.picId!) : 0);
  const picName = (this.picName !== null ? builder.createString(this.picName!) : 0);
  const mileStoneId = (this.mileStoneId !== null ? builder.createString(this.mileStoneId!) : 0);
  const picDesc = (this.picDesc !== null ? builder.createString(this.picDesc!) : 0);
  const jumpStageId = (this.jumpStageId !== null ? builder.createString(this.jumpStageId!) : 0);

  return clz_Torappu_Act12SideData_PhotoInfo.createclz_Torappu_Act12SideData_PhotoInfo(builder,
    picId,
    picName,
    mileStoneId,
    picDesc,
    jumpStageId
  );
}
}
