// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta implements flatbuffers.IUnpackableObject<clz_Torappu_Resource_ResourceManifest_AssetToBundleMetaT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta):clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta {
  return (obj || new clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta):clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

assetName():string|null
assetName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
assetName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

bundleIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

path():string|null
path(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
path(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAssetName(builder:flatbuffers.Builder, assetNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, assetNameOffset, 0);
}

static addBundleIndex(builder:flatbuffers.Builder, bundleIndex:number) {
  builder.addFieldInt32(1, bundleIndex, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addPath(builder:flatbuffers.Builder, pathOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, pathOffset, 0);
}

static endclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder:flatbuffers.Builder, assetNameOffset:flatbuffers.Offset, bundleIndex:number, nameOffset:flatbuffers.Offset, pathOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.startclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder);
  clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.addAssetName(builder, assetNameOffset);
  clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.addBundleIndex(builder, bundleIndex);
  clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.addName(builder, nameOffset);
  clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.addPath(builder, pathOffset);
  return clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.endclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder);
}

unpack(): clz_Torappu_Resource_ResourceManifest_AssetToBundleMetaT {
  return new clz_Torappu_Resource_ResourceManifest_AssetToBundleMetaT(
    this.assetName(),
    this.bundleIndex(),
    this.name(),
    this.path()
  );
}


unpackTo(_o: clz_Torappu_Resource_ResourceManifest_AssetToBundleMetaT): void {
  _o.assetName = this.assetName();
  _o.bundleIndex = this.bundleIndex();
  _o.name = this.name();
  _o.path = this.path();
}
}

export class clz_Torappu_Resource_ResourceManifest_AssetToBundleMetaT implements flatbuffers.IGeneratedObject {
constructor(
  public assetName: string|Uint8Array|null = null,
  public bundleIndex: number = 0,
  public name: string|Uint8Array|null = null,
  public path: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const assetName = (this.assetName !== null ? builder.createString(this.assetName!) : 0);
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const path = (this.path !== null ? builder.createString(this.path!) : 0);

  return clz_Torappu_Resource_ResourceManifest_AssetToBundleMeta.createclz_Torappu_Resource_ResourceManifest_AssetToBundleMeta(builder,
    assetName,
    this.bundleIndex,
    name,
    path
  );
}
}
