// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_RoguelikeFragmentModuleConsts implements flatbuffers.IUnpackableObject<clz_Torappu_RoguelikeFragmentModuleConstsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RoguelikeFragmentModuleConsts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RoguelikeFragmentModuleConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeFragmentModuleConsts):clz_Torappu_RoguelikeFragmentModuleConsts {
  return (obj || new clz_Torappu_RoguelikeFragmentModuleConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RoguelikeFragmentModuleConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeFragmentModuleConsts):clz_Torappu_RoguelikeFragmentModuleConsts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RoguelikeFragmentModuleConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

weightStatusSafeDesc():string|null
weightStatusSafeDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weightStatusSafeDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weightStatusLimitDesc():string|null
weightStatusLimitDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weightStatusLimitDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weightStatusOverweightDesc():string|null
weightStatusOverweightDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weightStatusOverweightDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

charWeightSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

limitWeightThresholdValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

overWeightThresholdValue():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

maxAlchemyField():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

maxAlchemyCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

fragmentBagWeightLimitTips():string|null
fragmentBagWeightLimitTips(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fragmentBagWeightLimitTips(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

fragmentBagWeightOverWeightTips():string|null
fragmentBagWeightOverWeightTips(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
fragmentBagWeightOverWeightTips(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

weightUpgradeToastFormat():string|null
weightUpgradeToastFormat(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
weightUpgradeToastFormat(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_RoguelikeFragmentModuleConsts(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addWeightStatusSafeDesc(builder:flatbuffers.Builder, weightStatusSafeDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, weightStatusSafeDescOffset, 0);
}

static addWeightStatusLimitDesc(builder:flatbuffers.Builder, weightStatusLimitDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, weightStatusLimitDescOffset, 0);
}

static addWeightStatusOverweightDesc(builder:flatbuffers.Builder, weightStatusOverweightDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, weightStatusOverweightDescOffset, 0);
}

static addCharWeightSlot(builder:flatbuffers.Builder, charWeightSlot:number) {
  builder.addFieldInt32(3, charWeightSlot, 0);
}

static addLimitWeightThresholdValue(builder:flatbuffers.Builder, limitWeightThresholdValue:number) {
  builder.addFieldInt32(4, limitWeightThresholdValue, 0);
}

static addOverWeightThresholdValue(builder:flatbuffers.Builder, overWeightThresholdValue:number) {
  builder.addFieldInt32(5, overWeightThresholdValue, 0);
}

static addMaxAlchemyField(builder:flatbuffers.Builder, maxAlchemyField:number) {
  builder.addFieldInt32(6, maxAlchemyField, 0);
}

static addMaxAlchemyCount(builder:flatbuffers.Builder, maxAlchemyCount:number) {
  builder.addFieldInt32(7, maxAlchemyCount, 0);
}

static addFragmentBagWeightLimitTips(builder:flatbuffers.Builder, fragmentBagWeightLimitTipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, fragmentBagWeightLimitTipsOffset, 0);
}

static addFragmentBagWeightOverWeightTips(builder:flatbuffers.Builder, fragmentBagWeightOverWeightTipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, fragmentBagWeightOverWeightTipsOffset, 0);
}

static addWeightUpgradeToastFormat(builder:flatbuffers.Builder, weightUpgradeToastFormatOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, weightUpgradeToastFormatOffset, 0);
}

static endclz_Torappu_RoguelikeFragmentModuleConsts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_RoguelikeFragmentModuleConsts(builder:flatbuffers.Builder, weightStatusSafeDescOffset:flatbuffers.Offset, weightStatusLimitDescOffset:flatbuffers.Offset, weightStatusOverweightDescOffset:flatbuffers.Offset, charWeightSlot:number, limitWeightThresholdValue:number, overWeightThresholdValue:number, maxAlchemyField:number, maxAlchemyCount:number, fragmentBagWeightLimitTipsOffset:flatbuffers.Offset, fragmentBagWeightOverWeightTipsOffset:flatbuffers.Offset, weightUpgradeToastFormatOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_RoguelikeFragmentModuleConsts.startclz_Torappu_RoguelikeFragmentModuleConsts(builder);
  clz_Torappu_RoguelikeFragmentModuleConsts.addWeightStatusSafeDesc(builder, weightStatusSafeDescOffset);
  clz_Torappu_RoguelikeFragmentModuleConsts.addWeightStatusLimitDesc(builder, weightStatusLimitDescOffset);
  clz_Torappu_RoguelikeFragmentModuleConsts.addWeightStatusOverweightDesc(builder, weightStatusOverweightDescOffset);
  clz_Torappu_RoguelikeFragmentModuleConsts.addCharWeightSlot(builder, charWeightSlot);
  clz_Torappu_RoguelikeFragmentModuleConsts.addLimitWeightThresholdValue(builder, limitWeightThresholdValue);
  clz_Torappu_RoguelikeFragmentModuleConsts.addOverWeightThresholdValue(builder, overWeightThresholdValue);
  clz_Torappu_RoguelikeFragmentModuleConsts.addMaxAlchemyField(builder, maxAlchemyField);
  clz_Torappu_RoguelikeFragmentModuleConsts.addMaxAlchemyCount(builder, maxAlchemyCount);
  clz_Torappu_RoguelikeFragmentModuleConsts.addFragmentBagWeightLimitTips(builder, fragmentBagWeightLimitTipsOffset);
  clz_Torappu_RoguelikeFragmentModuleConsts.addFragmentBagWeightOverWeightTips(builder, fragmentBagWeightOverWeightTipsOffset);
  clz_Torappu_RoguelikeFragmentModuleConsts.addWeightUpgradeToastFormat(builder, weightUpgradeToastFormatOffset);
  return clz_Torappu_RoguelikeFragmentModuleConsts.endclz_Torappu_RoguelikeFragmentModuleConsts(builder);
}

unpack(): clz_Torappu_RoguelikeFragmentModuleConstsT {
  return new clz_Torappu_RoguelikeFragmentModuleConstsT(
    this.weightStatusSafeDesc(),
    this.weightStatusLimitDesc(),
    this.weightStatusOverweightDesc(),
    this.charWeightSlot(),
    this.limitWeightThresholdValue(),
    this.overWeightThresholdValue(),
    this.maxAlchemyField(),
    this.maxAlchemyCount(),
    this.fragmentBagWeightLimitTips(),
    this.fragmentBagWeightOverWeightTips(),
    this.weightUpgradeToastFormat()
  );
}


unpackTo(_o: clz_Torappu_RoguelikeFragmentModuleConstsT): void {
  _o.weightStatusSafeDesc = this.weightStatusSafeDesc();
  _o.weightStatusLimitDesc = this.weightStatusLimitDesc();
  _o.weightStatusOverweightDesc = this.weightStatusOverweightDesc();
  _o.charWeightSlot = this.charWeightSlot();
  _o.limitWeightThresholdValue = this.limitWeightThresholdValue();
  _o.overWeightThresholdValue = this.overWeightThresholdValue();
  _o.maxAlchemyField = this.maxAlchemyField();
  _o.maxAlchemyCount = this.maxAlchemyCount();
  _o.fragmentBagWeightLimitTips = this.fragmentBagWeightLimitTips();
  _o.fragmentBagWeightOverWeightTips = this.fragmentBagWeightOverWeightTips();
  _o.weightUpgradeToastFormat = this.weightUpgradeToastFormat();
}
}

export class clz_Torappu_RoguelikeFragmentModuleConstsT implements flatbuffers.IGeneratedObject {
constructor(
  public weightStatusSafeDesc: string|Uint8Array|null = null,
  public weightStatusLimitDesc: string|Uint8Array|null = null,
  public weightStatusOverweightDesc: string|Uint8Array|null = null,
  public charWeightSlot: number = 0,
  public limitWeightThresholdValue: number = 0,
  public overWeightThresholdValue: number = 0,
  public maxAlchemyField: number = 0,
  public maxAlchemyCount: number = 0,
  public fragmentBagWeightLimitTips: string|Uint8Array|null = null,
  public fragmentBagWeightOverWeightTips: string|Uint8Array|null = null,
  public weightUpgradeToastFormat: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const weightStatusSafeDesc = (this.weightStatusSafeDesc !== null ? builder.createString(this.weightStatusSafeDesc!) : 0);
  const weightStatusLimitDesc = (this.weightStatusLimitDesc !== null ? builder.createString(this.weightStatusLimitDesc!) : 0);
  const weightStatusOverweightDesc = (this.weightStatusOverweightDesc !== null ? builder.createString(this.weightStatusOverweightDesc!) : 0);
  const fragmentBagWeightLimitTips = (this.fragmentBagWeightLimitTips !== null ? builder.createString(this.fragmentBagWeightLimitTips!) : 0);
  const fragmentBagWeightOverWeightTips = (this.fragmentBagWeightOverWeightTips !== null ? builder.createString(this.fragmentBagWeightOverWeightTips!) : 0);
  const weightUpgradeToastFormat = (this.weightUpgradeToastFormat !== null ? builder.createString(this.weightUpgradeToastFormat!) : 0);

  return clz_Torappu_RoguelikeFragmentModuleConsts.createclz_Torappu_RoguelikeFragmentModuleConsts(builder,
    weightStatusSafeDesc,
    weightStatusLimitDesc,
    weightStatusOverweightDesc,
    this.charWeightSlot,
    this.limitWeightThresholdValue,
    this.overWeightThresholdValue,
    this.maxAlchemyField,
    this.maxAlchemyCount,
    fragmentBagWeightLimitTips,
    fragmentBagWeightOverWeightTips,
    weightUpgradeToastFormat
  );
}
}
