// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_RoguelikeCandleModuleConsts implements flatbuffers.IUnpackableObject<clz_Torappu_RoguelikeCandleModuleConstsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RoguelikeCandleModuleConsts {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RoguelikeCandleModuleConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeCandleModuleConsts):clz_Torappu_RoguelikeCandleModuleConsts {
  return (obj || new clz_Torappu_RoguelikeCandleModuleConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RoguelikeCandleModuleConsts(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RoguelikeCandleModuleConsts):clz_Torappu_RoguelikeCandleModuleConsts {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RoguelikeCandleModuleConsts()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

candleHolderBuffId():string|null
candleHolderBuffId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
candleHolderBuffId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_RoguelikeCandleModuleConsts(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCandleHolderBuffId(builder:flatbuffers.Builder, candleHolderBuffIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, candleHolderBuffIdOffset, 0);
}

static endclz_Torappu_RoguelikeCandleModuleConsts(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_RoguelikeCandleModuleConsts(builder:flatbuffers.Builder, candleHolderBuffIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_RoguelikeCandleModuleConsts.startclz_Torappu_RoguelikeCandleModuleConsts(builder);
  clz_Torappu_RoguelikeCandleModuleConsts.addCandleHolderBuffId(builder, candleHolderBuffIdOffset);
  return clz_Torappu_RoguelikeCandleModuleConsts.endclz_Torappu_RoguelikeCandleModuleConsts(builder);
}

unpack(): clz_Torappu_RoguelikeCandleModuleConstsT {
  return new clz_Torappu_RoguelikeCandleModuleConstsT(
    this.candleHolderBuffId()
  );
}


unpackTo(_o: clz_Torappu_RoguelikeCandleModuleConstsT): void {
  _o.candleHolderBuffId = this.candleHolderBuffId();
}
}

export class clz_Torappu_RoguelikeCandleModuleConstsT implements flatbuffers.IGeneratedObject {
constructor(
  public candleHolderBuffId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const candleHolderBuffId = (this.candleHolderBuffId !== null ? builder.createString(this.candleHolderBuffId!) : 0);

  return clz_Torappu_RoguelikeCandleModuleConsts.createclz_Torappu_RoguelikeCandleModuleConsts(builder,
    candleHolderBuffId
  );
}
}
