// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_SpecialOperatorDetailUniEquipNodeData implements flatbuffers.IUnpackableObject<clz_Torappu_SpecialOperatorDetailUniEquipNodeDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SpecialOperatorDetailUniEquipNodeData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SpecialOperatorDetailUniEquipNodeData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SpecialOperatorDetailUniEquipNodeData):clz_Torappu_SpecialOperatorDetailUniEquipNodeData {
  return (obj || new clz_Torappu_SpecialOperatorDetailUniEquipNodeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SpecialOperatorDetailUniEquipNodeData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SpecialOperatorDetailUniEquipNodeData):clz_Torappu_SpecialOperatorDetailUniEquipNodeData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SpecialOperatorDetailUniEquipNodeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

nodeId():string|null
nodeId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
nodeId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

uniEquipId():string|null
uniEquipId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uniEquipId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

equipLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addNodeId(builder:flatbuffers.Builder, nodeIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nodeIdOffset, 0);
}

static addUniEquipId(builder:flatbuffers.Builder, uniEquipIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, uniEquipIdOffset, 0);
}

static addEquipLevel(builder:flatbuffers.Builder, equipLevel:number) {
  builder.addFieldInt32(2, equipLevel, 0);
}

static endclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder:flatbuffers.Builder, nodeIdOffset:flatbuffers.Offset, uniEquipIdOffset:flatbuffers.Offset, equipLevel:number):flatbuffers.Offset {
  clz_Torappu_SpecialOperatorDetailUniEquipNodeData.startclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder);
  clz_Torappu_SpecialOperatorDetailUniEquipNodeData.addNodeId(builder, nodeIdOffset);
  clz_Torappu_SpecialOperatorDetailUniEquipNodeData.addUniEquipId(builder, uniEquipIdOffset);
  clz_Torappu_SpecialOperatorDetailUniEquipNodeData.addEquipLevel(builder, equipLevel);
  return clz_Torappu_SpecialOperatorDetailUniEquipNodeData.endclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder);
}

unpack(): clz_Torappu_SpecialOperatorDetailUniEquipNodeDataT {
  return new clz_Torappu_SpecialOperatorDetailUniEquipNodeDataT(
    this.nodeId(),
    this.uniEquipId(),
    this.equipLevel()
  );
}


unpackTo(_o: clz_Torappu_SpecialOperatorDetailUniEquipNodeDataT): void {
  _o.nodeId = this.nodeId();
  _o.uniEquipId = this.uniEquipId();
  _o.equipLevel = this.equipLevel();
}
}

export class clz_Torappu_SpecialOperatorDetailUniEquipNodeDataT implements flatbuffers.IGeneratedObject {
constructor(
  public nodeId: string|Uint8Array|null = null,
  public uniEquipId: string|Uint8Array|null = null,
  public equipLevel: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const nodeId = (this.nodeId !== null ? builder.createString(this.nodeId!) : 0);
  const uniEquipId = (this.uniEquipId !== null ? builder.createString(this.uniEquipId!) : 0);

  return clz_Torappu_SpecialOperatorDetailUniEquipNodeData.createclz_Torappu_SpecialOperatorDetailUniEquipNodeData(builder,
    nodeId,
    uniEquipId,
    this.equipLevel
  );
}
}
