// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_SandboxV2QuestLineType } from './enum--torappu-sandbox-v2-quest-line-type.js';
import { enum__Torappu_SandboxV2QuestRouteType } from './enum--torappu-sandbox-v2-quest-route-type.js';


export class clz_Torappu_SandboxV2QuestData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxV2QuestDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxV2QuestData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxV2QuestData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2QuestData):clz_Torappu_SandboxV2QuestData {
  return (obj || new clz_Torappu_SandboxV2QuestData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxV2QuestData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2QuestData):clz_Torappu_SandboxV2QuestData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxV2QuestData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

questId():string|null
questId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

questLine():string|null
questLine(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questLine(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

questTitle():string|null
questTitle(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questTitle(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

questDesc():string|null
questDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

questTargetDesc():string|null
questTargetDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questTargetDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

isDisplay():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

questRouteType():enum__Torappu_SandboxV2QuestRouteType {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_SandboxV2QuestRouteType.NONE;
}

questLineType():enum__Torappu_SandboxV2QuestLineType {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_SandboxV2QuestLineType.NONE;
}

questRouteParam():string|null
questRouteParam(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questRouteParam(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

showProgressIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_SandboxV2QuestData(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addQuestId(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, questIdOffset, 0);
}

static addQuestLine(builder:flatbuffers.Builder, questLineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, questLineOffset, 0);
}

static addQuestTitle(builder:flatbuffers.Builder, questTitleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, questTitleOffset, 0);
}

static addQuestDesc(builder:flatbuffers.Builder, questDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, questDescOffset, 0);
}

static addQuestTargetDesc(builder:flatbuffers.Builder, questTargetDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, questTargetDescOffset, 0);
}

static addIsDisplay(builder:flatbuffers.Builder, isDisplay:boolean) {
  builder.addFieldInt8(5, +isDisplay, +false);
}

static addQuestRouteType(builder:flatbuffers.Builder, questRouteType:enum__Torappu_SandboxV2QuestRouteType) {
  builder.addFieldInt32(6, questRouteType, enum__Torappu_SandboxV2QuestRouteType.NONE);
}

static addQuestLineType(builder:flatbuffers.Builder, questLineType:enum__Torappu_SandboxV2QuestLineType) {
  builder.addFieldInt32(7, questLineType, enum__Torappu_SandboxV2QuestLineType.NONE);
}

static addQuestRouteParam(builder:flatbuffers.Builder, questRouteParamOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, questRouteParamOffset, 0);
}

static addShowProgressIndex(builder:flatbuffers.Builder, showProgressIndex:number) {
  builder.addFieldInt32(9, showProgressIndex, 0);
}

static endclz_Torappu_SandboxV2QuestData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxV2QuestData(builder:flatbuffers.Builder, questIdOffset:flatbuffers.Offset, questLineOffset:flatbuffers.Offset, questTitleOffset:flatbuffers.Offset, questDescOffset:flatbuffers.Offset, questTargetDescOffset:flatbuffers.Offset, isDisplay:boolean, questRouteType:enum__Torappu_SandboxV2QuestRouteType, questLineType:enum__Torappu_SandboxV2QuestLineType, questRouteParamOffset:flatbuffers.Offset, showProgressIndex:number):flatbuffers.Offset {
  clz_Torappu_SandboxV2QuestData.startclz_Torappu_SandboxV2QuestData(builder);
  clz_Torappu_SandboxV2QuestData.addQuestId(builder, questIdOffset);
  clz_Torappu_SandboxV2QuestData.addQuestLine(builder, questLineOffset);
  clz_Torappu_SandboxV2QuestData.addQuestTitle(builder, questTitleOffset);
  clz_Torappu_SandboxV2QuestData.addQuestDesc(builder, questDescOffset);
  clz_Torappu_SandboxV2QuestData.addQuestTargetDesc(builder, questTargetDescOffset);
  clz_Torappu_SandboxV2QuestData.addIsDisplay(builder, isDisplay);
  clz_Torappu_SandboxV2QuestData.addQuestRouteType(builder, questRouteType);
  clz_Torappu_SandboxV2QuestData.addQuestLineType(builder, questLineType);
  clz_Torappu_SandboxV2QuestData.addQuestRouteParam(builder, questRouteParamOffset);
  clz_Torappu_SandboxV2QuestData.addShowProgressIndex(builder, showProgressIndex);
  return clz_Torappu_SandboxV2QuestData.endclz_Torappu_SandboxV2QuestData(builder);
}

unpack(): clz_Torappu_SandboxV2QuestDataT {
  return new clz_Torappu_SandboxV2QuestDataT(
    this.questId(),
    this.questLine(),
    this.questTitle(),
    this.questDesc(),
    this.questTargetDesc(),
    this.isDisplay(),
    this.questRouteType(),
    this.questLineType(),
    this.questRouteParam(),
    this.showProgressIndex()
  );
}


unpackTo(_o: clz_Torappu_SandboxV2QuestDataT): void {
  _o.questId = this.questId();
  _o.questLine = this.questLine();
  _o.questTitle = this.questTitle();
  _o.questDesc = this.questDesc();
  _o.questTargetDesc = this.questTargetDesc();
  _o.isDisplay = this.isDisplay();
  _o.questRouteType = this.questRouteType();
  _o.questLineType = this.questLineType();
  _o.questRouteParam = this.questRouteParam();
  _o.showProgressIndex = this.showProgressIndex();
}
}

export class clz_Torappu_SandboxV2QuestDataT implements flatbuffers.IGeneratedObject {
constructor(
  public questId: string|Uint8Array|null = null,
  public questLine: string|Uint8Array|null = null,
  public questTitle: string|Uint8Array|null = null,
  public questDesc: string|Uint8Array|null = null,
  public questTargetDesc: string|Uint8Array|null = null,
  public isDisplay: boolean = false,
  public questRouteType: enum__Torappu_SandboxV2QuestRouteType = enum__Torappu_SandboxV2QuestRouteType.NONE,
  public questLineType: enum__Torappu_SandboxV2QuestLineType = enum__Torappu_SandboxV2QuestLineType.NONE,
  public questRouteParam: string|Uint8Array|null = null,
  public showProgressIndex: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const questId = (this.questId !== null ? builder.createString(this.questId!) : 0);
  const questLine = (this.questLine !== null ? builder.createString(this.questLine!) : 0);
  const questTitle = (this.questTitle !== null ? builder.createString(this.questTitle!) : 0);
  const questDesc = (this.questDesc !== null ? builder.createString(this.questDesc!) : 0);
  const questTargetDesc = (this.questTargetDesc !== null ? builder.createString(this.questTargetDesc!) : 0);
  const questRouteParam = (this.questRouteParam !== null ? builder.createString(this.questRouteParam!) : 0);

  return clz_Torappu_SandboxV2QuestData.createclz_Torappu_SandboxV2QuestData(builder,
    questId,
    questLine,
    questTitle,
    questDesc,
    questTargetDesc,
    this.isDisplay,
    this.questRouteType,
    this.questLineType,
    questRouteParam,
    this.showProgressIndex
  );
}
}
