// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_Act7FunConstData, clz_Torappu_Act7FunConstDataT } from './clz-torappu-act7-fun-const-data.js';
import { dict__string__clz_Torappu_Act7FunCharAnimData, dict__string__clz_Torappu_Act7FunCharAnimDataT } from './dict--string--clz-torappu-act7-fun-char-anim-data.js';
import { dict__string__clz_Torappu_Act7FunEasterEggData, dict__string__clz_Torappu_Act7FunEasterEggDataT } from './dict--string--clz-torappu-act7-fun-easter-egg-data.js';
import { dict__string__clz_Torappu_Act7FunSpineGroupData, dict__string__clz_Torappu_Act7FunSpineGroupDataT } from './dict--string--clz-torappu-act7-fun-spine-group-data.js';
import { dict__string__clz_Torappu_Act7FunStageAdditionData, dict__string__clz_Torappu_Act7FunStageAdditionDataT } from './dict--string--clz-torappu-act7-fun-stage-addition-data.js';


export class clz_Torappu_Act7FunData implements flatbuffers.IUnpackableObject<clz_Torappu_Act7FunDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act7FunData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act7FunData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act7FunData):clz_Torappu_Act7FunData {
  return (obj || new clz_Torappu_Act7FunData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act7FunData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act7FunData):clz_Torappu_Act7FunData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act7FunData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stageAdditionMap(index: number, obj?:dict__string__clz_Torappu_Act7FunStageAdditionData):dict__string__clz_Torappu_Act7FunStageAdditionData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__string__clz_Torappu_Act7FunStageAdditionData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stageAdditionMapLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

easterEggData(index: number, obj?:dict__string__clz_Torappu_Act7FunEasterEggData):dict__string__clz_Torappu_Act7FunEasterEggData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new dict__string__clz_Torappu_Act7FunEasterEggData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

easterEggDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spineGroupData(index: number, obj?:dict__string__clz_Torappu_Act7FunSpineGroupData):dict__string__clz_Torappu_Act7FunSpineGroupData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new dict__string__clz_Torappu_Act7FunSpineGroupData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

spineGroupDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

charAnimData(index: number, obj?:dict__string__clz_Torappu_Act7FunCharAnimData):dict__string__clz_Torappu_Act7FunCharAnimData|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new dict__string__clz_Torappu_Act7FunCharAnimData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

charAnimDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stageRewardList(index: number):string
stageRewardList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
stageRewardList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

stageRewardListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

constData(obj?:clz_Torappu_Act7FunConstData):clz_Torappu_Act7FunConstData|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new clz_Torappu_Act7FunConstData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startclz_Torappu_Act7FunData(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addStageAdditionMap(builder:flatbuffers.Builder, stageAdditionMapOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stageAdditionMapOffset, 0);
}

static createStageAdditionMapVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageAdditionMapVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEasterEggData(builder:flatbuffers.Builder, easterEggDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, easterEggDataOffset, 0);
}

static createEasterEggDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEasterEggDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSpineGroupData(builder:flatbuffers.Builder, spineGroupDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, spineGroupDataOffset, 0);
}

static createSpineGroupDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSpineGroupDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCharAnimData(builder:flatbuffers.Builder, charAnimDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, charAnimDataOffset, 0);
}

static createCharAnimDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCharAnimDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStageRewardList(builder:flatbuffers.Builder, stageRewardListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, stageRewardListOffset, 0);
}

static createStageRewardListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageRewardListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConstData(builder:flatbuffers.Builder, constDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, constDataOffset, 0);
}

static endclz_Torappu_Act7FunData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): clz_Torappu_Act7FunDataT {
  return new clz_Torappu_Act7FunDataT(
    this.bb!.createObjList<dict__string__clz_Torappu_Act7FunStageAdditionData, dict__string__clz_Torappu_Act7FunStageAdditionDataT>(this.stageAdditionMap.bind(this), this.stageAdditionMapLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_Act7FunEasterEggData, dict__string__clz_Torappu_Act7FunEasterEggDataT>(this.easterEggData.bind(this), this.easterEggDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_Act7FunSpineGroupData, dict__string__clz_Torappu_Act7FunSpineGroupDataT>(this.spineGroupData.bind(this), this.spineGroupDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_Act7FunCharAnimData, dict__string__clz_Torappu_Act7FunCharAnimDataT>(this.charAnimData.bind(this), this.charAnimDataLength()),
    this.bb!.createScalarList<string>(this.stageRewardList.bind(this), this.stageRewardListLength()),
    (this.constData() !== null ? this.constData()!.unpack() : null)
  );
}


unpackTo(_o: clz_Torappu_Act7FunDataT): void {
  _o.stageAdditionMap = this.bb!.createObjList<dict__string__clz_Torappu_Act7FunStageAdditionData, dict__string__clz_Torappu_Act7FunStageAdditionDataT>(this.stageAdditionMap.bind(this), this.stageAdditionMapLength());
  _o.easterEggData = this.bb!.createObjList<dict__string__clz_Torappu_Act7FunEasterEggData, dict__string__clz_Torappu_Act7FunEasterEggDataT>(this.easterEggData.bind(this), this.easterEggDataLength());
  _o.spineGroupData = this.bb!.createObjList<dict__string__clz_Torappu_Act7FunSpineGroupData, dict__string__clz_Torappu_Act7FunSpineGroupDataT>(this.spineGroupData.bind(this), this.spineGroupDataLength());
  _o.charAnimData = this.bb!.createObjList<dict__string__clz_Torappu_Act7FunCharAnimData, dict__string__clz_Torappu_Act7FunCharAnimDataT>(this.charAnimData.bind(this), this.charAnimDataLength());
  _o.stageRewardList = this.bb!.createScalarList<string>(this.stageRewardList.bind(this), this.stageRewardListLength());
  _o.constData = (this.constData() !== null ? this.constData()!.unpack() : null);
}
}

export class clz_Torappu_Act7FunDataT implements flatbuffers.IGeneratedObject {
constructor(
  public stageAdditionMap: (dict__string__clz_Torappu_Act7FunStageAdditionDataT)[] = [],
  public easterEggData: (dict__string__clz_Torappu_Act7FunEasterEggDataT)[] = [],
  public spineGroupData: (dict__string__clz_Torappu_Act7FunSpineGroupDataT)[] = [],
  public charAnimData: (dict__string__clz_Torappu_Act7FunCharAnimDataT)[] = [],
  public stageRewardList: (string)[] = [],
  public constData: clz_Torappu_Act7FunConstDataT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const stageAdditionMap = clz_Torappu_Act7FunData.createStageAdditionMapVector(builder, builder.createObjectOffsetList(this.stageAdditionMap));
  const easterEggData = clz_Torappu_Act7FunData.createEasterEggDataVector(builder, builder.createObjectOffsetList(this.easterEggData));
  const spineGroupData = clz_Torappu_Act7FunData.createSpineGroupDataVector(builder, builder.createObjectOffsetList(this.spineGroupData));
  const charAnimData = clz_Torappu_Act7FunData.createCharAnimDataVector(builder, builder.createObjectOffsetList(this.charAnimData));
  const stageRewardList = clz_Torappu_Act7FunData.createStageRewardListVector(builder, builder.createObjectOffsetList(this.stageRewardList));
  const constData = (this.constData !== null ? this.constData!.pack(builder) : 0);

  clz_Torappu_Act7FunData.startclz_Torappu_Act7FunData(builder);
  clz_Torappu_Act7FunData.addStageAdditionMap(builder, stageAdditionMap);
  clz_Torappu_Act7FunData.addEasterEggData(builder, easterEggData);
  clz_Torappu_Act7FunData.addSpineGroupData(builder, spineGroupData);
  clz_Torappu_Act7FunData.addCharAnimData(builder, charAnimData);
  clz_Torappu_Act7FunData.addStageRewardList(builder, stageRewardList);
  clz_Torappu_Act7FunData.addConstData(builder, constData);

  return clz_Torappu_Act7FunData.endclz_Torappu_Act7FunData(builder);
}
}
