// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_ItemBundle, clz_Torappu_ItemBundleT } from './clz-torappu-item-bundle.js';


export class clz_Torappu_Act25SideData_ConstData implements flatbuffers.IUnpackableObject<clz_Torappu_Act25SideData_ConstDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act25SideData_ConstData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act25SideData_ConstData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act25SideData_ConstData):clz_Torappu_Act25SideData_ConstData {
  return (obj || new clz_Torappu_Act25SideData_ConstData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act25SideData_ConstData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act25SideData_ConstData):clz_Torappu_Act25SideData_ConstData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act25SideData_ConstData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

getDailyCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

costName():string|null
costName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
costName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

costDesc():string|null
costDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
costDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

costLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

rewardLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

researchUnlockText():string|null
researchUnlockText(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
researchUnlockText(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

harvestReward(obj?:clz_Torappu_ItemBundle):clz_Torappu_ItemBundle|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new clz_Torappu_ItemBundle()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

costCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

costCountLimit():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

basicProgress():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

harvestDesc():string|null
harvestDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
harvestDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_Act25SideData_ConstData(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addGetDailyCount(builder:flatbuffers.Builder, getDailyCount:number) {
  builder.addFieldInt32(0, getDailyCount, 0);
}

static addCostName(builder:flatbuffers.Builder, costNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, costNameOffset, 0);
}

static addCostDesc(builder:flatbuffers.Builder, costDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, costDescOffset, 0);
}

static addCostLimit(builder:flatbuffers.Builder, costLimit:number) {
  builder.addFieldInt32(3, costLimit, 0);
}

static addRewardLimit(builder:flatbuffers.Builder, rewardLimit:number) {
  builder.addFieldInt32(4, rewardLimit, 0);
}

static addResearchUnlockText(builder:flatbuffers.Builder, researchUnlockTextOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, researchUnlockTextOffset, 0);
}

static addHarvestReward(builder:flatbuffers.Builder, harvestRewardOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, harvestRewardOffset, 0);
}

static addCostCount(builder:flatbuffers.Builder, costCount:number) {
  builder.addFieldInt32(7, costCount, 0);
}

static addCostCountLimit(builder:flatbuffers.Builder, costCountLimit:number) {
  builder.addFieldInt32(8, costCountLimit, 0);
}

static addBasicProgress(builder:flatbuffers.Builder, basicProgress:number) {
  builder.addFieldInt32(9, basicProgress, 0);
}

static addHarvestDesc(builder:flatbuffers.Builder, harvestDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, harvestDescOffset, 0);
}

static endclz_Torappu_Act25SideData_ConstData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): clz_Torappu_Act25SideData_ConstDataT {
  return new clz_Torappu_Act25SideData_ConstDataT(
    this.getDailyCount(),
    this.costName(),
    this.costDesc(),
    this.costLimit(),
    this.rewardLimit(),
    this.researchUnlockText(),
    (this.harvestReward() !== null ? this.harvestReward()!.unpack() : null),
    this.costCount(),
    this.costCountLimit(),
    this.basicProgress(),
    this.harvestDesc()
  );
}


unpackTo(_o: clz_Torappu_Act25SideData_ConstDataT): void {
  _o.getDailyCount = this.getDailyCount();
  _o.costName = this.costName();
  _o.costDesc = this.costDesc();
  _o.costLimit = this.costLimit();
  _o.rewardLimit = this.rewardLimit();
  _o.researchUnlockText = this.researchUnlockText();
  _o.harvestReward = (this.harvestReward() !== null ? this.harvestReward()!.unpack() : null);
  _o.costCount = this.costCount();
  _o.costCountLimit = this.costCountLimit();
  _o.basicProgress = this.basicProgress();
  _o.harvestDesc = this.harvestDesc();
}
}

export class clz_Torappu_Act25SideData_ConstDataT implements flatbuffers.IGeneratedObject {
constructor(
  public getDailyCount: number = 0,
  public costName: string|Uint8Array|null = null,
  public costDesc: string|Uint8Array|null = null,
  public costLimit: number = 0,
  public rewardLimit: number = 0,
  public researchUnlockText: string|Uint8Array|null = null,
  public harvestReward: clz_Torappu_ItemBundleT|null = null,
  public costCount: number = 0,
  public costCountLimit: number = 0,
  public basicProgress: number = 0,
  public harvestDesc: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const costName = (this.costName !== null ? builder.createString(this.costName!) : 0);
  const costDesc = (this.costDesc !== null ? builder.createString(this.costDesc!) : 0);
  const researchUnlockText = (this.researchUnlockText !== null ? builder.createString(this.researchUnlockText!) : 0);
  const harvestReward = (this.harvestReward !== null ? this.harvestReward!.pack(builder) : 0);
  const harvestDesc = (this.harvestDesc !== null ? builder.createString(this.harvestDesc!) : 0);

  clz_Torappu_Act25SideData_ConstData.startclz_Torappu_Act25SideData_ConstData(builder);
  clz_Torappu_Act25SideData_ConstData.addGetDailyCount(builder, this.getDailyCount);
  clz_Torappu_Act25SideData_ConstData.addCostName(builder, costName);
  clz_Torappu_Act25SideData_ConstData.addCostDesc(builder, costDesc);
  clz_Torappu_Act25SideData_ConstData.addCostLimit(builder, this.costLimit);
  clz_Torappu_Act25SideData_ConstData.addRewardLimit(builder, this.rewardLimit);
  clz_Torappu_Act25SideData_ConstData.addResearchUnlockText(builder, researchUnlockText);
  clz_Torappu_Act25SideData_ConstData.addHarvestReward(builder, harvestReward);
  clz_Torappu_Act25SideData_ConstData.addCostCount(builder, this.costCount);
  clz_Torappu_Act25SideData_ConstData.addCostCountLimit(builder, this.costCountLimit);
  clz_Torappu_Act25SideData_ConstData.addBasicProgress(builder, this.basicProgress);
  clz_Torappu_Act25SideData_ConstData.addHarvestDesc(builder, harvestDesc);

  return clz_Torappu_Act25SideData_ConstData.endclz_Torappu_Act25SideData_ConstData(builder);
}
}
