// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_SandboxRewardItemConfigData, clz_Torappu_SandboxRewardItemConfigDataT } from './clz-torappu-sandbox-reward-item-config-data.js';


export class clz_Torappu_SandboxRewardData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxRewardDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxRewardData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxRewardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxRewardData):clz_Torappu_SandboxRewardData {
  return (obj || new clz_Torappu_SandboxRewardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxRewardData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxRewardData):clz_Torappu_SandboxRewardData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxRewardData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rewardList(index: number, obj?:clz_Torappu_SandboxRewardItemConfigData):clz_Torappu_SandboxRewardItemConfigData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new clz_Torappu_SandboxRewardItemConfigData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rewardListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_SandboxRewardData(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRewardList(builder:flatbuffers.Builder, rewardListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, rewardListOffset, 0);
}

static createRewardListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRewardListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_SandboxRewardData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxRewardData(builder:flatbuffers.Builder, rewardListOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_SandboxRewardData.startclz_Torappu_SandboxRewardData(builder);
  clz_Torappu_SandboxRewardData.addRewardList(builder, rewardListOffset);
  return clz_Torappu_SandboxRewardData.endclz_Torappu_SandboxRewardData(builder);
}

unpack(): clz_Torappu_SandboxRewardDataT {
  return new clz_Torappu_SandboxRewardDataT(
    this.bb!.createObjList<clz_Torappu_SandboxRewardItemConfigData, clz_Torappu_SandboxRewardItemConfigDataT>(this.rewardList.bind(this), this.rewardListLength())
  );
}


unpackTo(_o: clz_Torappu_SandboxRewardDataT): void {
  _o.rewardList = this.bb!.createObjList<clz_Torappu_SandboxRewardItemConfigData, clz_Torappu_SandboxRewardItemConfigDataT>(this.rewardList.bind(this), this.rewardListLength());
}
}

export class clz_Torappu_SandboxRewardDataT implements flatbuffers.IGeneratedObject {
constructor(
  public rewardList: (clz_Torappu_SandboxRewardItemConfigDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const rewardList = clz_Torappu_SandboxRewardData.createRewardListVector(builder, builder.createObjectOffsetList(this.rewardList));

  return clz_Torappu_SandboxRewardData.createclz_Torappu_SandboxRewardData(builder,
    rewardList
  );
}
}
