// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_SandboxV3ItemRandomPoolData_Item, clz_Torappu_SandboxV3ItemRandomPoolData_ItemT } from './clz-torappu-sandbox-v3-item-random-pool-data-item.js';


export class clz_Torappu_SandboxV3ItemRandomPoolData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxV3ItemRandomPoolDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxV3ItemRandomPoolData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxV3ItemRandomPoolData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV3ItemRandomPoolData):clz_Torappu_SandboxV3ItemRandomPoolData {
  return (obj || new clz_Torappu_SandboxV3ItemRandomPoolData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxV3ItemRandomPoolData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV3ItemRandomPoolData):clz_Torappu_SandboxV3ItemRandomPoolData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxV3ItemRandomPoolData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

normalItemList(index: number, obj?:clz_Torappu_SandboxV3ItemRandomPoolData_Item):clz_Torappu_SandboxV3ItemRandomPoolData_Item|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new clz_Torappu_SandboxV3ItemRandomPoolData_Item()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

normalItemListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

guaranteeItemList(index: number, obj?:clz_Torappu_SandboxV3ItemRandomPoolData_Item):clz_Torappu_SandboxV3ItemRandomPoolData_Item|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_SandboxV3ItemRandomPoolData_Item()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

guaranteeItemListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_SandboxV3ItemRandomPoolData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addNormalItemList(builder:flatbuffers.Builder, normalItemListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, normalItemListOffset, 0);
}

static createNormalItemListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNormalItemListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addGuaranteeItemList(builder:flatbuffers.Builder, guaranteeItemListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, guaranteeItemListOffset, 0);
}

static createGuaranteeItemListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGuaranteeItemListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_SandboxV3ItemRandomPoolData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxV3ItemRandomPoolData(builder:flatbuffers.Builder, normalItemListOffset:flatbuffers.Offset, guaranteeItemListOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_SandboxV3ItemRandomPoolData.startclz_Torappu_SandboxV3ItemRandomPoolData(builder);
  clz_Torappu_SandboxV3ItemRandomPoolData.addNormalItemList(builder, normalItemListOffset);
  clz_Torappu_SandboxV3ItemRandomPoolData.addGuaranteeItemList(builder, guaranteeItemListOffset);
  return clz_Torappu_SandboxV3ItemRandomPoolData.endclz_Torappu_SandboxV3ItemRandomPoolData(builder);
}

unpack(): clz_Torappu_SandboxV3ItemRandomPoolDataT {
  return new clz_Torappu_SandboxV3ItemRandomPoolDataT(
    this.bb!.createObjList<clz_Torappu_SandboxV3ItemRandomPoolData_Item, clz_Torappu_SandboxV3ItemRandomPoolData_ItemT>(this.normalItemList.bind(this), this.normalItemListLength()),
    this.bb!.createObjList<clz_Torappu_SandboxV3ItemRandomPoolData_Item, clz_Torappu_SandboxV3ItemRandomPoolData_ItemT>(this.guaranteeItemList.bind(this), this.guaranteeItemListLength())
  );
}


unpackTo(_o: clz_Torappu_SandboxV3ItemRandomPoolDataT): void {
  _o.normalItemList = this.bb!.createObjList<clz_Torappu_SandboxV3ItemRandomPoolData_Item, clz_Torappu_SandboxV3ItemRandomPoolData_ItemT>(this.normalItemList.bind(this), this.normalItemListLength());
  _o.guaranteeItemList = this.bb!.createObjList<clz_Torappu_SandboxV3ItemRandomPoolData_Item, clz_Torappu_SandboxV3ItemRandomPoolData_ItemT>(this.guaranteeItemList.bind(this), this.guaranteeItemListLength());
}
}

export class clz_Torappu_SandboxV3ItemRandomPoolDataT implements flatbuffers.IGeneratedObject {
constructor(
  public normalItemList: (clz_Torappu_SandboxV3ItemRandomPoolData_ItemT)[] = [],
  public guaranteeItemList: (clz_Torappu_SandboxV3ItemRandomPoolData_ItemT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const normalItemList = clz_Torappu_SandboxV3ItemRandomPoolData.createNormalItemListVector(builder, builder.createObjectOffsetList(this.normalItemList));
  const guaranteeItemList = clz_Torappu_SandboxV3ItemRandomPoolData.createGuaranteeItemListVector(builder, builder.createObjectOffsetList(this.guaranteeItemList));

  return clz_Torappu_SandboxV3ItemRandomPoolData.createclz_Torappu_SandboxV3ItemRandomPoolData(builder,
    normalItemList,
    guaranteeItemList
  );
}
}
