// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_ActivityYear5GeneralConstData implements flatbuffers.IUnpackableObject<clz_Torappu_ActivityYear5GeneralConstDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ActivityYear5GeneralConstData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ActivityYear5GeneralConstData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityYear5GeneralConstData):clz_Torappu_ActivityYear5GeneralConstData {
  return (obj || new clz_Torappu_ActivityYear5GeneralConstData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ActivityYear5GeneralConstData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityYear5GeneralConstData):clz_Torappu_ActivityYear5GeneralConstData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ActivityYear5GeneralConstData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

rewPoint():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

rewMainDesc():string|null
rewMainDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rewMainDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

rewApDesc():string|null
rewApDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rewApDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

rewEndDesc():string|null
rewEndDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rewEndDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

actPrimaryDesc():string|null
actPrimaryDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actPrimaryDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

actEntryDesc():string|null
actEntryDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actEntryDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

actSecondaryDesc():string|null
actSecondaryDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actSecondaryDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

actRewardDesc():string|null
actRewardDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
actRewardDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

missionArchiveTopicId():string|null
missionArchiveTopicId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
missionArchiveTopicId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

missionArchiveUnlockDesc():string|null
missionArchiveUnlockDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
missionArchiveUnlockDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_ActivityYear5GeneralConstData(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addRewPoint(builder:flatbuffers.Builder, rewPoint:number) {
  builder.addFieldInt32(0, rewPoint, 0);
}

static addRewMainDesc(builder:flatbuffers.Builder, rewMainDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, rewMainDescOffset, 0);
}

static addRewApDesc(builder:flatbuffers.Builder, rewApDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, rewApDescOffset, 0);
}

static addRewEndDesc(builder:flatbuffers.Builder, rewEndDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, rewEndDescOffset, 0);
}

static addActPrimaryDesc(builder:flatbuffers.Builder, actPrimaryDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, actPrimaryDescOffset, 0);
}

static addActEntryDesc(builder:flatbuffers.Builder, actEntryDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, actEntryDescOffset, 0);
}

static addActSecondaryDesc(builder:flatbuffers.Builder, actSecondaryDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, actSecondaryDescOffset, 0);
}

static addActRewardDesc(builder:flatbuffers.Builder, actRewardDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, actRewardDescOffset, 0);
}

static addMissionArchiveTopicId(builder:flatbuffers.Builder, missionArchiveTopicIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, missionArchiveTopicIdOffset, 0);
}

static addMissionArchiveUnlockDesc(builder:flatbuffers.Builder, missionArchiveUnlockDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, missionArchiveUnlockDescOffset, 0);
}

static endclz_Torappu_ActivityYear5GeneralConstData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ActivityYear5GeneralConstData(builder:flatbuffers.Builder, rewPoint:number, rewMainDescOffset:flatbuffers.Offset, rewApDescOffset:flatbuffers.Offset, rewEndDescOffset:flatbuffers.Offset, actPrimaryDescOffset:flatbuffers.Offset, actEntryDescOffset:flatbuffers.Offset, actSecondaryDescOffset:flatbuffers.Offset, actRewardDescOffset:flatbuffers.Offset, missionArchiveTopicIdOffset:flatbuffers.Offset, missionArchiveUnlockDescOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ActivityYear5GeneralConstData.startclz_Torappu_ActivityYear5GeneralConstData(builder);
  clz_Torappu_ActivityYear5GeneralConstData.addRewPoint(builder, rewPoint);
  clz_Torappu_ActivityYear5GeneralConstData.addRewMainDesc(builder, rewMainDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addRewApDesc(builder, rewApDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addRewEndDesc(builder, rewEndDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addActPrimaryDesc(builder, actPrimaryDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addActEntryDesc(builder, actEntryDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addActSecondaryDesc(builder, actSecondaryDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addActRewardDesc(builder, actRewardDescOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addMissionArchiveTopicId(builder, missionArchiveTopicIdOffset);
  clz_Torappu_ActivityYear5GeneralConstData.addMissionArchiveUnlockDesc(builder, missionArchiveUnlockDescOffset);
  return clz_Torappu_ActivityYear5GeneralConstData.endclz_Torappu_ActivityYear5GeneralConstData(builder);
}

unpack(): clz_Torappu_ActivityYear5GeneralConstDataT {
  return new clz_Torappu_ActivityYear5GeneralConstDataT(
    this.rewPoint(),
    this.rewMainDesc(),
    this.rewApDesc(),
    this.rewEndDesc(),
    this.actPrimaryDesc(),
    this.actEntryDesc(),
    this.actSecondaryDesc(),
    this.actRewardDesc(),
    this.missionArchiveTopicId(),
    this.missionArchiveUnlockDesc()
  );
}


unpackTo(_o: clz_Torappu_ActivityYear5GeneralConstDataT): void {
  _o.rewPoint = this.rewPoint();
  _o.rewMainDesc = this.rewMainDesc();
  _o.rewApDesc = this.rewApDesc();
  _o.rewEndDesc = this.rewEndDesc();
  _o.actPrimaryDesc = this.actPrimaryDesc();
  _o.actEntryDesc = this.actEntryDesc();
  _o.actSecondaryDesc = this.actSecondaryDesc();
  _o.actRewardDesc = this.actRewardDesc();
  _o.missionArchiveTopicId = this.missionArchiveTopicId();
  _o.missionArchiveUnlockDesc = this.missionArchiveUnlockDesc();
}
}

export class clz_Torappu_ActivityYear5GeneralConstDataT implements flatbuffers.IGeneratedObject {
constructor(
  public rewPoint: number = 0,
  public rewMainDesc: string|Uint8Array|null = null,
  public rewApDesc: string|Uint8Array|null = null,
  public rewEndDesc: string|Uint8Array|null = null,
  public actPrimaryDesc: string|Uint8Array|null = null,
  public actEntryDesc: string|Uint8Array|null = null,
  public actSecondaryDesc: string|Uint8Array|null = null,
  public actRewardDesc: string|Uint8Array|null = null,
  public missionArchiveTopicId: string|Uint8Array|null = null,
  public missionArchiveUnlockDesc: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const rewMainDesc = (this.rewMainDesc !== null ? builder.createString(this.rewMainDesc!) : 0);
  const rewApDesc = (this.rewApDesc !== null ? builder.createString(this.rewApDesc!) : 0);
  const rewEndDesc = (this.rewEndDesc !== null ? builder.createString(this.rewEndDesc!) : 0);
  const actPrimaryDesc = (this.actPrimaryDesc !== null ? builder.createString(this.actPrimaryDesc!) : 0);
  const actEntryDesc = (this.actEntryDesc !== null ? builder.createString(this.actEntryDesc!) : 0);
  const actSecondaryDesc = (this.actSecondaryDesc !== null ? builder.createString(this.actSecondaryDesc!) : 0);
  const actRewardDesc = (this.actRewardDesc !== null ? builder.createString(this.actRewardDesc!) : 0);
  const missionArchiveTopicId = (this.missionArchiveTopicId !== null ? builder.createString(this.missionArchiveTopicId!) : 0);
  const missionArchiveUnlockDesc = (this.missionArchiveUnlockDesc !== null ? builder.createString(this.missionArchiveUnlockDesc!) : 0);

  return clz_Torappu_ActivityYear5GeneralConstData.createclz_Torappu_ActivityYear5GeneralConstData(builder,
    this.rewPoint,
    rewMainDesc,
    rewApDesc,
    rewEndDesc,
    actPrimaryDesc,
    actEntryDesc,
    actSecondaryDesc,
    actRewardDesc,
    missionArchiveTopicId,
    missionArchiveUnlockDesc
  );
}
}
