// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act1VHalfIdleCharRankData_CharRankData implements flatbuffers.IUnpackableObject<clz_Torappu_Act1VHalfIdleCharRankData_CharRankDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act1VHalfIdleCharRankData_CharRankData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act1VHalfIdleCharRankData_CharRankData):clz_Torappu_Act1VHalfIdleCharRankData_CharRankData {
  return (obj || new clz_Torappu_Act1VHalfIdleCharRankData_CharRankData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act1VHalfIdleCharRankData_CharRankData):clz_Torappu_Act1VHalfIdleCharRankData_CharRankData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act1VHalfIdleCharRankData_CharRankData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

accumulatedExp():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

exp():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(0, level, 0);
}

static addAccumulatedExp(builder:flatbuffers.Builder, accumulatedExp:number) {
  builder.addFieldInt32(1, accumulatedExp, 0);
}

static addExp(builder:flatbuffers.Builder, exp:number) {
  builder.addFieldInt32(2, exp, 0);
}

static endclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder:flatbuffers.Builder, level:number, accumulatedExp:number, exp:number):flatbuffers.Offset {
  clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.startclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder);
  clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.addLevel(builder, level);
  clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.addAccumulatedExp(builder, accumulatedExp);
  clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.addExp(builder, exp);
  return clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.endclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder);
}

unpack(): clz_Torappu_Act1VHalfIdleCharRankData_CharRankDataT {
  return new clz_Torappu_Act1VHalfIdleCharRankData_CharRankDataT(
    this.level(),
    this.accumulatedExp(),
    this.exp()
  );
}


unpackTo(_o: clz_Torappu_Act1VHalfIdleCharRankData_CharRankDataT): void {
  _o.level = this.level();
  _o.accumulatedExp = this.accumulatedExp();
  _o.exp = this.exp();
}
}

export class clz_Torappu_Act1VHalfIdleCharRankData_CharRankDataT implements flatbuffers.IGeneratedObject {
constructor(
  public level: number = 0,
  public accumulatedExp: number = 0,
  public exp: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return clz_Torappu_Act1VHalfIdleCharRankData_CharRankData.createclz_Torappu_Act1VHalfIdleCharRankData_CharRankData(builder,
    this.level,
    this.accumulatedExp,
    this.exp
  );
}
}
