// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_MissionDisplayRewards, clz_Torappu_MissionDisplayRewardsT } from './clz-torappu-mission-display-rewards.js';
import { enum__Torappu_MissionType } from './enum--torappu-mission-type.js';


export class clz_Torappu_ActivityTable_TrapMissionData implements flatbuffers.IUnpackableObject<clz_Torappu_ActivityTable_TrapMissionDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_ActivityTable_TrapMissionData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_ActivityTable_TrapMissionData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityTable_TrapMissionData):clz_Torappu_ActivityTable_TrapMissionData {
  return (obj || new clz_Torappu_ActivityTable_TrapMissionData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_ActivityTable_TrapMissionData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_ActivityTable_TrapMissionData):clz_Torappu_ActivityTable_TrapMissionData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_ActivityTable_TrapMissionData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

description():string|null
description(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
description(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

type():enum__Torappu_MissionType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_MissionType.UNKNOWN;
}

rewards(index: number, obj?:clz_Torappu_MissionDisplayRewards):clz_Torappu_MissionDisplayRewards|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new clz_Torappu_MissionDisplayRewards()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

rewardsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_ActivityTable_TrapMissionData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addDescription(builder:flatbuffers.Builder, descriptionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, descriptionOffset, 0);
}

static addType(builder:flatbuffers.Builder, type:enum__Torappu_MissionType) {
  builder.addFieldInt32(2, type, enum__Torappu_MissionType.UNKNOWN);
}

static addRewards(builder:flatbuffers.Builder, rewardsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, rewardsOffset, 0);
}

static createRewardsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRewardsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_ActivityTable_TrapMissionData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_ActivityTable_TrapMissionData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, descriptionOffset:flatbuffers.Offset, type:enum__Torappu_MissionType, rewardsOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_ActivityTable_TrapMissionData.startclz_Torappu_ActivityTable_TrapMissionData(builder);
  clz_Torappu_ActivityTable_TrapMissionData.addId(builder, idOffset);
  clz_Torappu_ActivityTable_TrapMissionData.addDescription(builder, descriptionOffset);
  clz_Torappu_ActivityTable_TrapMissionData.addType(builder, type);
  clz_Torappu_ActivityTable_TrapMissionData.addRewards(builder, rewardsOffset);
  return clz_Torappu_ActivityTable_TrapMissionData.endclz_Torappu_ActivityTable_TrapMissionData(builder);
}

unpack(): clz_Torappu_ActivityTable_TrapMissionDataT {
  return new clz_Torappu_ActivityTable_TrapMissionDataT(
    this.id(),
    this.description(),
    this.type(),
    this.bb!.createObjList<clz_Torappu_MissionDisplayRewards, clz_Torappu_MissionDisplayRewardsT>(this.rewards.bind(this), this.rewardsLength())
  );
}


unpackTo(_o: clz_Torappu_ActivityTable_TrapMissionDataT): void {
  _o.id = this.id();
  _o.description = this.description();
  _o.type = this.type();
  _o.rewards = this.bb!.createObjList<clz_Torappu_MissionDisplayRewards, clz_Torappu_MissionDisplayRewardsT>(this.rewards.bind(this), this.rewardsLength());
}
}

export class clz_Torappu_ActivityTable_TrapMissionDataT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public description: string|Uint8Array|null = null,
  public type: enum__Torappu_MissionType = enum__Torappu_MissionType.UNKNOWN,
  public rewards: (clz_Torappu_MissionDisplayRewardsT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const description = (this.description !== null ? builder.createString(this.description!) : 0);
  const rewards = clz_Torappu_ActivityTable_TrapMissionData.createRewardsVector(builder, builder.createObjectOffsetList(this.rewards));

  return clz_Torappu_ActivityTable_TrapMissionData.createclz_Torappu_ActivityTable_TrapMissionData(builder,
    id,
    description,
    this.type,
    rewards
  );
}
}
