// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_SandboxV2RiftMainTargetType } from './enum--torappu-sandbox-v2-rift-main-target-type.js';


export class clz_Torappu_SandboxV2RiftMainTargetData implements flatbuffers.IUnpackableObject<clz_Torappu_SandboxV2RiftMainTargetDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_SandboxV2RiftMainTargetData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_SandboxV2RiftMainTargetData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2RiftMainTargetData):clz_Torappu_SandboxV2RiftMainTargetData {
  return (obj || new clz_Torappu_SandboxV2RiftMainTargetData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_SandboxV2RiftMainTargetData(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_SandboxV2RiftMainTargetData):clz_Torappu_SandboxV2RiftMainTargetData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_SandboxV2RiftMainTargetData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

desc():string|null
desc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
desc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

storyDesc():string|null
storyDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
storyDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

targetDayCount():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

targetType():enum__Torappu_SandboxV2RiftMainTargetType {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_SandboxV2RiftMainTargetType.NONE;
}

questIconId():string|null
questIconId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questIconId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

questIconName():string|null
questIconName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
questIconName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_SandboxV2RiftMainTargetData(builder:flatbuffers.Builder) {
  builder.startObject(8);
}

static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, titleOffset, 0);
}

static addDesc(builder:flatbuffers.Builder, descOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, descOffset, 0);
}

static addStoryDesc(builder:flatbuffers.Builder, storyDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, storyDescOffset, 0);
}

static addTargetDayCount(builder:flatbuffers.Builder, targetDayCount:number) {
  builder.addFieldInt32(4, targetDayCount, 0);
}

static addTargetType(builder:flatbuffers.Builder, targetType:enum__Torappu_SandboxV2RiftMainTargetType) {
  builder.addFieldInt32(5, targetType, enum__Torappu_SandboxV2RiftMainTargetType.NONE);
}

static addQuestIconId(builder:flatbuffers.Builder, questIconIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, questIconIdOffset, 0);
}

static addQuestIconName(builder:flatbuffers.Builder, questIconNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, questIconNameOffset, 0);
}

static endclz_Torappu_SandboxV2RiftMainTargetData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_SandboxV2RiftMainTargetData(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, titleOffset:flatbuffers.Offset, descOffset:flatbuffers.Offset, storyDescOffset:flatbuffers.Offset, targetDayCount:number, targetType:enum__Torappu_SandboxV2RiftMainTargetType, questIconIdOffset:flatbuffers.Offset, questIconNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_SandboxV2RiftMainTargetData.startclz_Torappu_SandboxV2RiftMainTargetData(builder);
  clz_Torappu_SandboxV2RiftMainTargetData.addId(builder, idOffset);
  clz_Torappu_SandboxV2RiftMainTargetData.addTitle(builder, titleOffset);
  clz_Torappu_SandboxV2RiftMainTargetData.addDesc(builder, descOffset);
  clz_Torappu_SandboxV2RiftMainTargetData.addStoryDesc(builder, storyDescOffset);
  clz_Torappu_SandboxV2RiftMainTargetData.addTargetDayCount(builder, targetDayCount);
  clz_Torappu_SandboxV2RiftMainTargetData.addTargetType(builder, targetType);
  clz_Torappu_SandboxV2RiftMainTargetData.addQuestIconId(builder, questIconIdOffset);
  clz_Torappu_SandboxV2RiftMainTargetData.addQuestIconName(builder, questIconNameOffset);
  return clz_Torappu_SandboxV2RiftMainTargetData.endclz_Torappu_SandboxV2RiftMainTargetData(builder);
}

unpack(): clz_Torappu_SandboxV2RiftMainTargetDataT {
  return new clz_Torappu_SandboxV2RiftMainTargetDataT(
    this.id(),
    this.title(),
    this.desc(),
    this.storyDesc(),
    this.targetDayCount(),
    this.targetType(),
    this.questIconId(),
    this.questIconName()
  );
}


unpackTo(_o: clz_Torappu_SandboxV2RiftMainTargetDataT): void {
  _o.id = this.id();
  _o.title = this.title();
  _o.desc = this.desc();
  _o.storyDesc = this.storyDesc();
  _o.targetDayCount = this.targetDayCount();
  _o.targetType = this.targetType();
  _o.questIconId = this.questIconId();
  _o.questIconName = this.questIconName();
}
}

export class clz_Torappu_SandboxV2RiftMainTargetDataT implements flatbuffers.IGeneratedObject {
constructor(
  public id: string|Uint8Array|null = null,
  public title: string|Uint8Array|null = null,
  public desc: string|Uint8Array|null = null,
  public storyDesc: string|Uint8Array|null = null,
  public targetDayCount: number = 0,
  public targetType: enum__Torappu_SandboxV2RiftMainTargetType = enum__Torappu_SandboxV2RiftMainTargetType.NONE,
  public questIconId: string|Uint8Array|null = null,
  public questIconName: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const id = (this.id !== null ? builder.createString(this.id!) : 0);
  const title = (this.title !== null ? builder.createString(this.title!) : 0);
  const desc = (this.desc !== null ? builder.createString(this.desc!) : 0);
  const storyDesc = (this.storyDesc !== null ? builder.createString(this.storyDesc!) : 0);
  const questIconId = (this.questIconId !== null ? builder.createString(this.questIconId!) : 0);
  const questIconName = (this.questIconName !== null ? builder.createString(this.questIconName!) : 0);

  return clz_Torappu_SandboxV2RiftMainTargetData.createclz_Torappu_SandboxV2RiftMainTargetData(builder,
    id,
    title,
    desc,
    storyDesc,
    this.targetDayCount,
    this.targetType,
    questIconId,
    questIconName
  );
}
}
