// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_StorylineConstData, clz_Torappu_StorylineConstDataT } from './clz-torappu-storyline-const-data.js';
import { dict__string__clz_Torappu_ActCustomStageData, dict__string__clz_Torappu_ActCustomStageDataT } from './dict--string--clz-torappu-act-custom-stage-data.js';
import { dict__string__clz_Torappu_ApProtectZoneInfo, dict__string__clz_Torappu_ApProtectZoneInfoT } from './dict--string--clz-torappu-ap-protect-zone-info.js';
import { dict__string__clz_Torappu_ConditionalDropInfo, dict__string__clz_Torappu_ConditionalDropInfoT } from './dict--string--clz-torappu-conditional-drop-info.js';
import { dict__string__clz_Torappu_MapThemeData, dict__string__clz_Torappu_MapThemeDataT } from './dict--string--clz-torappu-map-theme-data.js';
import { dict__string__clz_Torappu_OverrideDropInfo, dict__string__clz_Torappu_OverrideDropInfoT } from './dict--string--clz-torappu-override-drop-info.js';
import { dict__string__clz_Torappu_OverrideUnlockInfo, dict__string__clz_Torappu_OverrideUnlockInfoT } from './dict--string--clz-torappu-override-unlock-info.js';
import { dict__string__clz_Torappu_RecordRewardServerData, dict__string__clz_Torappu_RecordRewardServerDataT } from './dict--string--clz-torappu-record-reward-server-data.js';
import { dict__string__clz_Torappu_RuneStageGroupData, dict__string__clz_Torappu_RuneStageGroupDataT } from './dict--string--clz-torappu-rune-stage-group-data.js';
import { dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo, dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfoT } from './dict--string--clz-torappu-six-star-linked-stage-compatible-info.js';
import { dict__string__clz_Torappu_SixStarMilestoneGroupData, dict__string__clz_Torappu_SixStarMilestoneGroupDataT } from './dict--string--clz-torappu-six-star-milestone-group-data.js';
import { dict__string__clz_Torappu_SixStarRuneData, dict__string__clz_Torappu_SixStarRuneDataT } from './dict--string--clz-torappu-six-star-rune-data.js';
import { dict__string__clz_Torappu_SpecialBattleFinishStageData, dict__string__clz_Torappu_SpecialBattleFinishStageDataT } from './dict--string--clz-torappu-special-battle-finish-stage-data.js';
import { dict__string__clz_Torappu_StageData, dict__string__clz_Torappu_StageDataT } from './dict--string--clz-torappu-stage-data.js';
import { dict__string__clz_Torappu_StageDiffGroupTable, dict__string__clz_Torappu_StageDiffGroupTableT } from './dict--string--clz-torappu-stage-diff-group-table.js';
import { dict__string__clz_Torappu_StageFogInfo, dict__string__clz_Torappu_StageFogInfoT } from './dict--string--clz-torappu-stage-fog-info.js';
import { dict__string__clz_Torappu_StageStartCond, dict__string__clz_Torappu_StageStartCondT } from './dict--string--clz-torappu-stage-start-cond.js';
import { dict__string__clz_Torappu_StageValidInfo, dict__string__clz_Torappu_StageValidInfoT } from './dict--string--clz-torappu-stage-valid-info.js';
import { dict__string__clz_Torappu_StorylineData, dict__string__clz_Torappu_StorylineDataT } from './dict--string--clz-torappu-storyline-data.js';
import { dict__string__clz_Torappu_StorylineStorySetData, dict__string__clz_Torappu_StorylineStorySetDataT } from './dict--string--clz-torappu-storyline-story-set-data.js';
import { dict__string__clz_Torappu_StorylineTagData, dict__string__clz_Torappu_StorylineTagDataT } from './dict--string--clz-torappu-storyline-tag-data.js';
import { dict__string__clz_Torappu_TileAppendInfo, dict__string__clz_Torappu_TileAppendInfoT } from './dict--string--clz-torappu-tile-append-info.js';
import { dict__string__clz_Torappu_TimelyDropInfo, dict__string__clz_Torappu_TimelyDropInfoT } from './dict--string--clz-torappu-timely-drop-info.js';
import { dict__string__clz_Torappu_TimelyDropTimeInfo, dict__string__clz_Torappu_TimelyDropTimeInfoT } from './dict--string--clz-torappu-timely-drop-time-info.js';
import { dict__string__clz_Torappu_WeeklyForceOpenTable, dict__string__clz_Torappu_WeeklyForceOpenTableT } from './dict--string--clz-torappu-weekly-force-open-table.js';
import { dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup, dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroupT } from './dict--string--list-dict--enum--torappu-stage-diff-group--clz-torappu-story-stage-show-group.js';
import { dict__string__list_string, dict__string__list_stringT } from './dict--string--list-string.js';


export class clz_Torappu_StageTable implements flatbuffers.IUnpackableObject<clz_Torappu_StageTableT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_StageTable {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_StageTable(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_StageTable):clz_Torappu_StageTable {
  return (obj || new clz_Torappu_StageTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_StageTable(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_StageTable):clz_Torappu_StageTable {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_StageTable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

stages(index: number, obj?:dict__string__clz_Torappu_StageData):dict__string__clz_Torappu_StageData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new dict__string__clz_Torappu_StageData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stagesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

runeStageGroups(index: number, obj?:dict__string__clz_Torappu_RuneStageGroupData):dict__string__clz_Torappu_RuneStageGroupData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new dict__string__clz_Torappu_RuneStageGroupData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

runeStageGroupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

mapThemes(index: number, obj?:dict__string__clz_Torappu_MapThemeData):dict__string__clz_Torappu_MapThemeData|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new dict__string__clz_Torappu_MapThemeData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

mapThemesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

tileInfo(index: number, obj?:dict__string__clz_Torappu_TileAppendInfo):dict__string__clz_Torappu_TileAppendInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new dict__string__clz_Torappu_TileAppendInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

tileInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

forceOpenTable(index: number, obj?:dict__string__clz_Torappu_WeeklyForceOpenTable):dict__string__clz_Torappu_WeeklyForceOpenTable|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new dict__string__clz_Torappu_WeeklyForceOpenTable()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

forceOpenTableLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

timelyStageDropInfo(index: number, obj?:dict__string__clz_Torappu_TimelyDropTimeInfo):dict__string__clz_Torappu_TimelyDropTimeInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new dict__string__clz_Torappu_TimelyDropTimeInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

timelyStageDropInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

overrideDropInfo(index: number, obj?:dict__string__clz_Torappu_OverrideDropInfo):dict__string__clz_Torappu_OverrideDropInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new dict__string__clz_Torappu_OverrideDropInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

overrideDropInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

overrideUnlockInfo(index: number, obj?:dict__string__clz_Torappu_OverrideUnlockInfo):dict__string__clz_Torappu_OverrideUnlockInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new dict__string__clz_Torappu_OverrideUnlockInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

overrideUnlockInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

timelyTable(index: number, obj?:dict__string__clz_Torappu_TimelyDropInfo):dict__string__clz_Torappu_TimelyDropInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new dict__string__clz_Torappu_TimelyDropInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

timelyTableLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stageValidInfo(index: number, obj?:dict__string__clz_Torappu_StageValidInfo):dict__string__clz_Torappu_StageValidInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new dict__string__clz_Torappu_StageValidInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stageValidInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stageFogInfo(index: number, obj?:dict__string__clz_Torappu_StageFogInfo):dict__string__clz_Torappu_StageFogInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new dict__string__clz_Torappu_StageFogInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stageFogInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

stageStartConds(index: number, obj?:dict__string__clz_Torappu_StageStartCond):dict__string__clz_Torappu_StageStartCond|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new dict__string__clz_Torappu_StageStartCond()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

stageStartCondsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

diffGroupTable(index: number, obj?:dict__string__clz_Torappu_StageDiffGroupTable):dict__string__clz_Torappu_StageDiffGroupTable|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? (obj || new dict__string__clz_Torappu_StageDiffGroupTable()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

diffGroupTableLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storyStageShowGroup(index: number, obj?:dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup):dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup|null {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? (obj || new dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

storyStageShowGroupLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

specialBattleFinishStageData(index: number, obj?:dict__string__clz_Torappu_SpecialBattleFinishStageData):dict__string__clz_Torappu_SpecialBattleFinishStageData|null {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? (obj || new dict__string__clz_Torappu_SpecialBattleFinishStageData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

specialBattleFinishStageDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

recordRewardData(index: number, obj?:dict__string__clz_Torappu_RecordRewardServerData):dict__string__clz_Torappu_RecordRewardServerData|null {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? (obj || new dict__string__clz_Torappu_RecordRewardServerData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

recordRewardDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

apProtectZoneInfo(index: number, obj?:dict__string__clz_Torappu_ApProtectZoneInfo):dict__string__clz_Torappu_ApProtectZoneInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? (obj || new dict__string__clz_Torappu_ApProtectZoneInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

apProtectZoneInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

antiSpoilerDict(index: number, obj?:dict__string__list_string):dict__string__list_string|null {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? (obj || new dict__string__list_string()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

antiSpoilerDictLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

actCustomStageDatas(index: number, obj?:dict__string__clz_Torappu_ActCustomStageData):dict__string__clz_Torappu_ActCustomStageData|null {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? (obj || new dict__string__clz_Torappu_ActCustomStageData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

actCustomStageDatasLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

spNormalStageIdFor4StarList(index: number):string
spNormalStageIdFor4StarList(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
spNormalStageIdFor4StarList(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

spNormalStageIdFor4StarListLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storylines(index: number, obj?:dict__string__clz_Torappu_StorylineData):dict__string__clz_Torappu_StorylineData|null {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? (obj || new dict__string__clz_Torappu_StorylineData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

storylinesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storylineStorySets(index: number, obj?:dict__string__clz_Torappu_StorylineStorySetData):dict__string__clz_Torappu_StorylineStorySetData|null {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? (obj || new dict__string__clz_Torappu_StorylineStorySetData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

storylineStorySetsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storylineTags(index: number, obj?:dict__string__clz_Torappu_StorylineTagData):dict__string__clz_Torappu_StorylineTagData|null {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? (obj || new dict__string__clz_Torappu_StorylineTagData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

storylineTagsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

storylineConst(obj?:clz_Torappu_StorylineConstData):clz_Torappu_StorylineConstData|null {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? (obj || new clz_Torappu_StorylineConstData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

sixStarRuneData(index: number, obj?:dict__string__clz_Torappu_SixStarRuneData):dict__string__clz_Torappu_SixStarRuneData|null {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? (obj || new dict__string__clz_Torappu_SixStarRuneData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

sixStarRuneDataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

sixStarMilestoneInfo(index: number, obj?:dict__string__clz_Torappu_SixStarMilestoneGroupData):dict__string__clz_Torappu_SixStarMilestoneGroupData|null {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? (obj || new dict__string__clz_Torappu_SixStarMilestoneGroupData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

sixStarMilestoneInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

sixStarCompatibleInfo(index: number, obj?:dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo):dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? (obj || new dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

sixStarCompatibleInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

conditionalDropInfo(index: number, obj?:dict__string__clz_Torappu_ConditionalDropInfo):dict__string__clz_Torappu_ConditionalDropInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? (obj || new dict__string__clz_Torappu_ConditionalDropInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

conditionalDropInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startclz_Torappu_StageTable(builder:flatbuffers.Builder) {
  builder.startObject(28);
}

static addStages(builder:flatbuffers.Builder, stagesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, stagesOffset, 0);
}

static createStagesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStagesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRuneStageGroups(builder:flatbuffers.Builder, runeStageGroupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, runeStageGroupsOffset, 0);
}

static createRuneStageGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRuneStageGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addMapThemes(builder:flatbuffers.Builder, mapThemesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, mapThemesOffset, 0);
}

static createMapThemesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMapThemesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTileInfo(builder:flatbuffers.Builder, tileInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, tileInfoOffset, 0);
}

static createTileInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTileInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addForceOpenTable(builder:flatbuffers.Builder, forceOpenTableOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, forceOpenTableOffset, 0);
}

static createForceOpenTableVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startForceOpenTableVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTimelyStageDropInfo(builder:flatbuffers.Builder, timelyStageDropInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, timelyStageDropInfoOffset, 0);
}

static createTimelyStageDropInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTimelyStageDropInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOverrideDropInfo(builder:flatbuffers.Builder, overrideDropInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, overrideDropInfoOffset, 0);
}

static createOverrideDropInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOverrideDropInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOverrideUnlockInfo(builder:flatbuffers.Builder, overrideUnlockInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, overrideUnlockInfoOffset, 0);
}

static createOverrideUnlockInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOverrideUnlockInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addTimelyTable(builder:flatbuffers.Builder, timelyTableOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, timelyTableOffset, 0);
}

static createTimelyTableVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startTimelyTableVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStageValidInfo(builder:flatbuffers.Builder, stageValidInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, stageValidInfoOffset, 0);
}

static createStageValidInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageValidInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStageFogInfo(builder:flatbuffers.Builder, stageFogInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, stageFogInfoOffset, 0);
}

static createStageFogInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageFogInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStageStartConds(builder:flatbuffers.Builder, stageStartCondsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, stageStartCondsOffset, 0);
}

static createStageStartCondsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStageStartCondsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addDiffGroupTable(builder:flatbuffers.Builder, diffGroupTableOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, diffGroupTableOffset, 0);
}

static createDiffGroupTableVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startDiffGroupTableVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStoryStageShowGroup(builder:flatbuffers.Builder, storyStageShowGroupOffset:flatbuffers.Offset) {
  builder.addFieldOffset(13, storyStageShowGroupOffset, 0);
}

static createStoryStageShowGroupVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStoryStageShowGroupVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSpecialBattleFinishStageData(builder:flatbuffers.Builder, specialBattleFinishStageDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(14, specialBattleFinishStageDataOffset, 0);
}

static createSpecialBattleFinishStageDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSpecialBattleFinishStageDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRecordRewardData(builder:flatbuffers.Builder, recordRewardDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(15, recordRewardDataOffset, 0);
}

static createRecordRewardDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRecordRewardDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addApProtectZoneInfo(builder:flatbuffers.Builder, apProtectZoneInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(16, apProtectZoneInfoOffset, 0);
}

static createApProtectZoneInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startApProtectZoneInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addAntiSpoilerDict(builder:flatbuffers.Builder, antiSpoilerDictOffset:flatbuffers.Offset) {
  builder.addFieldOffset(17, antiSpoilerDictOffset, 0);
}

static createAntiSpoilerDictVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAntiSpoilerDictVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addActCustomStageDatas(builder:flatbuffers.Builder, actCustomStageDatasOffset:flatbuffers.Offset) {
  builder.addFieldOffset(18, actCustomStageDatasOffset, 0);
}

static createActCustomStageDatasVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startActCustomStageDatasVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSpNormalStageIdFor4StarList(builder:flatbuffers.Builder, spNormalStageIdFor4StarListOffset:flatbuffers.Offset) {
  builder.addFieldOffset(19, spNormalStageIdFor4StarListOffset, 0);
}

static createSpNormalStageIdFor4StarListVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSpNormalStageIdFor4StarListVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStorylines(builder:flatbuffers.Builder, storylinesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(20, storylinesOffset, 0);
}

static createStorylinesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStorylinesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStorylineStorySets(builder:flatbuffers.Builder, storylineStorySetsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(21, storylineStorySetsOffset, 0);
}

static createStorylineStorySetsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStorylineStorySetsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStorylineTags(builder:flatbuffers.Builder, storylineTagsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(22, storylineTagsOffset, 0);
}

static createStorylineTagsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startStorylineTagsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addStorylineConst(builder:flatbuffers.Builder, storylineConstOffset:flatbuffers.Offset) {
  builder.addFieldOffset(23, storylineConstOffset, 0);
}

static addSixStarRuneData(builder:flatbuffers.Builder, sixStarRuneDataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(24, sixStarRuneDataOffset, 0);
}

static createSixStarRuneDataVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSixStarRuneDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSixStarMilestoneInfo(builder:flatbuffers.Builder, sixStarMilestoneInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(25, sixStarMilestoneInfoOffset, 0);
}

static createSixStarMilestoneInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSixStarMilestoneInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSixStarCompatibleInfo(builder:flatbuffers.Builder, sixStarCompatibleInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(26, sixStarCompatibleInfoOffset, 0);
}

static createSixStarCompatibleInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startSixStarCompatibleInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConditionalDropInfo(builder:flatbuffers.Builder, conditionalDropInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(27, conditionalDropInfoOffset, 0);
}

static createConditionalDropInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startConditionalDropInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endclz_Torappu_StageTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishclz_Torappu_StageTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedclz_Torappu_StageTableBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}


unpack(): clz_Torappu_StageTableT {
  return new clz_Torappu_StageTableT(
    this.bb!.createObjList<dict__string__clz_Torappu_StageData, dict__string__clz_Torappu_StageDataT>(this.stages.bind(this), this.stagesLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_RuneStageGroupData, dict__string__clz_Torappu_RuneStageGroupDataT>(this.runeStageGroups.bind(this), this.runeStageGroupsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_MapThemeData, dict__string__clz_Torappu_MapThemeDataT>(this.mapThemes.bind(this), this.mapThemesLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_TileAppendInfo, dict__string__clz_Torappu_TileAppendInfoT>(this.tileInfo.bind(this), this.tileInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_WeeklyForceOpenTable, dict__string__clz_Torappu_WeeklyForceOpenTableT>(this.forceOpenTable.bind(this), this.forceOpenTableLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_TimelyDropTimeInfo, dict__string__clz_Torappu_TimelyDropTimeInfoT>(this.timelyStageDropInfo.bind(this), this.timelyStageDropInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_OverrideDropInfo, dict__string__clz_Torappu_OverrideDropInfoT>(this.overrideDropInfo.bind(this), this.overrideDropInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_OverrideUnlockInfo, dict__string__clz_Torappu_OverrideUnlockInfoT>(this.overrideUnlockInfo.bind(this), this.overrideUnlockInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_TimelyDropInfo, dict__string__clz_Torappu_TimelyDropInfoT>(this.timelyTable.bind(this), this.timelyTableLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StageValidInfo, dict__string__clz_Torappu_StageValidInfoT>(this.stageValidInfo.bind(this), this.stageValidInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StageFogInfo, dict__string__clz_Torappu_StageFogInfoT>(this.stageFogInfo.bind(this), this.stageFogInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StageStartCond, dict__string__clz_Torappu_StageStartCondT>(this.stageStartConds.bind(this), this.stageStartCondsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StageDiffGroupTable, dict__string__clz_Torappu_StageDiffGroupTableT>(this.diffGroupTable.bind(this), this.diffGroupTableLength()),
    this.bb!.createObjList<dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup, dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroupT>(this.storyStageShowGroup.bind(this), this.storyStageShowGroupLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_SpecialBattleFinishStageData, dict__string__clz_Torappu_SpecialBattleFinishStageDataT>(this.specialBattleFinishStageData.bind(this), this.specialBattleFinishStageDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_RecordRewardServerData, dict__string__clz_Torappu_RecordRewardServerDataT>(this.recordRewardData.bind(this), this.recordRewardDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_ApProtectZoneInfo, dict__string__clz_Torappu_ApProtectZoneInfoT>(this.apProtectZoneInfo.bind(this), this.apProtectZoneInfoLength()),
    this.bb!.createObjList<dict__string__list_string, dict__string__list_stringT>(this.antiSpoilerDict.bind(this), this.antiSpoilerDictLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_ActCustomStageData, dict__string__clz_Torappu_ActCustomStageDataT>(this.actCustomStageDatas.bind(this), this.actCustomStageDatasLength()),
    this.bb!.createScalarList<string>(this.spNormalStageIdFor4StarList.bind(this), this.spNormalStageIdFor4StarListLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StorylineData, dict__string__clz_Torappu_StorylineDataT>(this.storylines.bind(this), this.storylinesLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StorylineStorySetData, dict__string__clz_Torappu_StorylineStorySetDataT>(this.storylineStorySets.bind(this), this.storylineStorySetsLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_StorylineTagData, dict__string__clz_Torappu_StorylineTagDataT>(this.storylineTags.bind(this), this.storylineTagsLength()),
    (this.storylineConst() !== null ? this.storylineConst()!.unpack() : null),
    this.bb!.createObjList<dict__string__clz_Torappu_SixStarRuneData, dict__string__clz_Torappu_SixStarRuneDataT>(this.sixStarRuneData.bind(this), this.sixStarRuneDataLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_SixStarMilestoneGroupData, dict__string__clz_Torappu_SixStarMilestoneGroupDataT>(this.sixStarMilestoneInfo.bind(this), this.sixStarMilestoneInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo, dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfoT>(this.sixStarCompatibleInfo.bind(this), this.sixStarCompatibleInfoLength()),
    this.bb!.createObjList<dict__string__clz_Torappu_ConditionalDropInfo, dict__string__clz_Torappu_ConditionalDropInfoT>(this.conditionalDropInfo.bind(this), this.conditionalDropInfoLength())
  );
}


unpackTo(_o: clz_Torappu_StageTableT): void {
  _o.stages = this.bb!.createObjList<dict__string__clz_Torappu_StageData, dict__string__clz_Torappu_StageDataT>(this.stages.bind(this), this.stagesLength());
  _o.runeStageGroups = this.bb!.createObjList<dict__string__clz_Torappu_RuneStageGroupData, dict__string__clz_Torappu_RuneStageGroupDataT>(this.runeStageGroups.bind(this), this.runeStageGroupsLength());
  _o.mapThemes = this.bb!.createObjList<dict__string__clz_Torappu_MapThemeData, dict__string__clz_Torappu_MapThemeDataT>(this.mapThemes.bind(this), this.mapThemesLength());
  _o.tileInfo = this.bb!.createObjList<dict__string__clz_Torappu_TileAppendInfo, dict__string__clz_Torappu_TileAppendInfoT>(this.tileInfo.bind(this), this.tileInfoLength());
  _o.forceOpenTable = this.bb!.createObjList<dict__string__clz_Torappu_WeeklyForceOpenTable, dict__string__clz_Torappu_WeeklyForceOpenTableT>(this.forceOpenTable.bind(this), this.forceOpenTableLength());
  _o.timelyStageDropInfo = this.bb!.createObjList<dict__string__clz_Torappu_TimelyDropTimeInfo, dict__string__clz_Torappu_TimelyDropTimeInfoT>(this.timelyStageDropInfo.bind(this), this.timelyStageDropInfoLength());
  _o.overrideDropInfo = this.bb!.createObjList<dict__string__clz_Torappu_OverrideDropInfo, dict__string__clz_Torappu_OverrideDropInfoT>(this.overrideDropInfo.bind(this), this.overrideDropInfoLength());
  _o.overrideUnlockInfo = this.bb!.createObjList<dict__string__clz_Torappu_OverrideUnlockInfo, dict__string__clz_Torappu_OverrideUnlockInfoT>(this.overrideUnlockInfo.bind(this), this.overrideUnlockInfoLength());
  _o.timelyTable = this.bb!.createObjList<dict__string__clz_Torappu_TimelyDropInfo, dict__string__clz_Torappu_TimelyDropInfoT>(this.timelyTable.bind(this), this.timelyTableLength());
  _o.stageValidInfo = this.bb!.createObjList<dict__string__clz_Torappu_StageValidInfo, dict__string__clz_Torappu_StageValidInfoT>(this.stageValidInfo.bind(this), this.stageValidInfoLength());
  _o.stageFogInfo = this.bb!.createObjList<dict__string__clz_Torappu_StageFogInfo, dict__string__clz_Torappu_StageFogInfoT>(this.stageFogInfo.bind(this), this.stageFogInfoLength());
  _o.stageStartConds = this.bb!.createObjList<dict__string__clz_Torappu_StageStartCond, dict__string__clz_Torappu_StageStartCondT>(this.stageStartConds.bind(this), this.stageStartCondsLength());
  _o.diffGroupTable = this.bb!.createObjList<dict__string__clz_Torappu_StageDiffGroupTable, dict__string__clz_Torappu_StageDiffGroupTableT>(this.diffGroupTable.bind(this), this.diffGroupTableLength());
  _o.storyStageShowGroup = this.bb!.createObjList<dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroup, dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroupT>(this.storyStageShowGroup.bind(this), this.storyStageShowGroupLength());
  _o.specialBattleFinishStageData = this.bb!.createObjList<dict__string__clz_Torappu_SpecialBattleFinishStageData, dict__string__clz_Torappu_SpecialBattleFinishStageDataT>(this.specialBattleFinishStageData.bind(this), this.specialBattleFinishStageDataLength());
  _o.recordRewardData = this.bb!.createObjList<dict__string__clz_Torappu_RecordRewardServerData, dict__string__clz_Torappu_RecordRewardServerDataT>(this.recordRewardData.bind(this), this.recordRewardDataLength());
  _o.apProtectZoneInfo = this.bb!.createObjList<dict__string__clz_Torappu_ApProtectZoneInfo, dict__string__clz_Torappu_ApProtectZoneInfoT>(this.apProtectZoneInfo.bind(this), this.apProtectZoneInfoLength());
  _o.antiSpoilerDict = this.bb!.createObjList<dict__string__list_string, dict__string__list_stringT>(this.antiSpoilerDict.bind(this), this.antiSpoilerDictLength());
  _o.actCustomStageDatas = this.bb!.createObjList<dict__string__clz_Torappu_ActCustomStageData, dict__string__clz_Torappu_ActCustomStageDataT>(this.actCustomStageDatas.bind(this), this.actCustomStageDatasLength());
  _o.spNormalStageIdFor4StarList = this.bb!.createScalarList<string>(this.spNormalStageIdFor4StarList.bind(this), this.spNormalStageIdFor4StarListLength());
  _o.storylines = this.bb!.createObjList<dict__string__clz_Torappu_StorylineData, dict__string__clz_Torappu_StorylineDataT>(this.storylines.bind(this), this.storylinesLength());
  _o.storylineStorySets = this.bb!.createObjList<dict__string__clz_Torappu_StorylineStorySetData, dict__string__clz_Torappu_StorylineStorySetDataT>(this.storylineStorySets.bind(this), this.storylineStorySetsLength());
  _o.storylineTags = this.bb!.createObjList<dict__string__clz_Torappu_StorylineTagData, dict__string__clz_Torappu_StorylineTagDataT>(this.storylineTags.bind(this), this.storylineTagsLength());
  _o.storylineConst = (this.storylineConst() !== null ? this.storylineConst()!.unpack() : null);
  _o.sixStarRuneData = this.bb!.createObjList<dict__string__clz_Torappu_SixStarRuneData, dict__string__clz_Torappu_SixStarRuneDataT>(this.sixStarRuneData.bind(this), this.sixStarRuneDataLength());
  _o.sixStarMilestoneInfo = this.bb!.createObjList<dict__string__clz_Torappu_SixStarMilestoneGroupData, dict__string__clz_Torappu_SixStarMilestoneGroupDataT>(this.sixStarMilestoneInfo.bind(this), this.sixStarMilestoneInfoLength());
  _o.sixStarCompatibleInfo = this.bb!.createObjList<dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfo, dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfoT>(this.sixStarCompatibleInfo.bind(this), this.sixStarCompatibleInfoLength());
  _o.conditionalDropInfo = this.bb!.createObjList<dict__string__clz_Torappu_ConditionalDropInfo, dict__string__clz_Torappu_ConditionalDropInfoT>(this.conditionalDropInfo.bind(this), this.conditionalDropInfoLength());
}
}

export class clz_Torappu_StageTableT implements flatbuffers.IGeneratedObject {
constructor(
  public stages: (dict__string__clz_Torappu_StageDataT)[] = [],
  public runeStageGroups: (dict__string__clz_Torappu_RuneStageGroupDataT)[] = [],
  public mapThemes: (dict__string__clz_Torappu_MapThemeDataT)[] = [],
  public tileInfo: (dict__string__clz_Torappu_TileAppendInfoT)[] = [],
  public forceOpenTable: (dict__string__clz_Torappu_WeeklyForceOpenTableT)[] = [],
  public timelyStageDropInfo: (dict__string__clz_Torappu_TimelyDropTimeInfoT)[] = [],
  public overrideDropInfo: (dict__string__clz_Torappu_OverrideDropInfoT)[] = [],
  public overrideUnlockInfo: (dict__string__clz_Torappu_OverrideUnlockInfoT)[] = [],
  public timelyTable: (dict__string__clz_Torappu_TimelyDropInfoT)[] = [],
  public stageValidInfo: (dict__string__clz_Torappu_StageValidInfoT)[] = [],
  public stageFogInfo: (dict__string__clz_Torappu_StageFogInfoT)[] = [],
  public stageStartConds: (dict__string__clz_Torappu_StageStartCondT)[] = [],
  public diffGroupTable: (dict__string__clz_Torappu_StageDiffGroupTableT)[] = [],
  public storyStageShowGroup: (dict__string__list_dict__enum__Torappu_StageDiffGroup__clz_Torappu_StoryStageShowGroupT)[] = [],
  public specialBattleFinishStageData: (dict__string__clz_Torappu_SpecialBattleFinishStageDataT)[] = [],
  public recordRewardData: (dict__string__clz_Torappu_RecordRewardServerDataT)[] = [],
  public apProtectZoneInfo: (dict__string__clz_Torappu_ApProtectZoneInfoT)[] = [],
  public antiSpoilerDict: (dict__string__list_stringT)[] = [],
  public actCustomStageDatas: (dict__string__clz_Torappu_ActCustomStageDataT)[] = [],
  public spNormalStageIdFor4StarList: (string)[] = [],
  public storylines: (dict__string__clz_Torappu_StorylineDataT)[] = [],
  public storylineStorySets: (dict__string__clz_Torappu_StorylineStorySetDataT)[] = [],
  public storylineTags: (dict__string__clz_Torappu_StorylineTagDataT)[] = [],
  public storylineConst: clz_Torappu_StorylineConstDataT|null = null,
  public sixStarRuneData: (dict__string__clz_Torappu_SixStarRuneDataT)[] = [],
  public sixStarMilestoneInfo: (dict__string__clz_Torappu_SixStarMilestoneGroupDataT)[] = [],
  public sixStarCompatibleInfo: (dict__string__clz_Torappu_SixStarLinkedStageCompatibleInfoT)[] = [],
  public conditionalDropInfo: (dict__string__clz_Torappu_ConditionalDropInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const stages = clz_Torappu_StageTable.createStagesVector(builder, builder.createObjectOffsetList(this.stages));
  const runeStageGroups = clz_Torappu_StageTable.createRuneStageGroupsVector(builder, builder.createObjectOffsetList(this.runeStageGroups));
  const mapThemes = clz_Torappu_StageTable.createMapThemesVector(builder, builder.createObjectOffsetList(this.mapThemes));
  const tileInfo = clz_Torappu_StageTable.createTileInfoVector(builder, builder.createObjectOffsetList(this.tileInfo));
  const forceOpenTable = clz_Torappu_StageTable.createForceOpenTableVector(builder, builder.createObjectOffsetList(this.forceOpenTable));
  const timelyStageDropInfo = clz_Torappu_StageTable.createTimelyStageDropInfoVector(builder, builder.createObjectOffsetList(this.timelyStageDropInfo));
  const overrideDropInfo = clz_Torappu_StageTable.createOverrideDropInfoVector(builder, builder.createObjectOffsetList(this.overrideDropInfo));
  const overrideUnlockInfo = clz_Torappu_StageTable.createOverrideUnlockInfoVector(builder, builder.createObjectOffsetList(this.overrideUnlockInfo));
  const timelyTable = clz_Torappu_StageTable.createTimelyTableVector(builder, builder.createObjectOffsetList(this.timelyTable));
  const stageValidInfo = clz_Torappu_StageTable.createStageValidInfoVector(builder, builder.createObjectOffsetList(this.stageValidInfo));
  const stageFogInfo = clz_Torappu_StageTable.createStageFogInfoVector(builder, builder.createObjectOffsetList(this.stageFogInfo));
  const stageStartConds = clz_Torappu_StageTable.createStageStartCondsVector(builder, builder.createObjectOffsetList(this.stageStartConds));
  const diffGroupTable = clz_Torappu_StageTable.createDiffGroupTableVector(builder, builder.createObjectOffsetList(this.diffGroupTable));
  const storyStageShowGroup = clz_Torappu_StageTable.createStoryStageShowGroupVector(builder, builder.createObjectOffsetList(this.storyStageShowGroup));
  const specialBattleFinishStageData = clz_Torappu_StageTable.createSpecialBattleFinishStageDataVector(builder, builder.createObjectOffsetList(this.specialBattleFinishStageData));
  const recordRewardData = clz_Torappu_StageTable.createRecordRewardDataVector(builder, builder.createObjectOffsetList(this.recordRewardData));
  const apProtectZoneInfo = clz_Torappu_StageTable.createApProtectZoneInfoVector(builder, builder.createObjectOffsetList(this.apProtectZoneInfo));
  const antiSpoilerDict = clz_Torappu_StageTable.createAntiSpoilerDictVector(builder, builder.createObjectOffsetList(this.antiSpoilerDict));
  const actCustomStageDatas = clz_Torappu_StageTable.createActCustomStageDatasVector(builder, builder.createObjectOffsetList(this.actCustomStageDatas));
  const spNormalStageIdFor4StarList = clz_Torappu_StageTable.createSpNormalStageIdFor4StarListVector(builder, builder.createObjectOffsetList(this.spNormalStageIdFor4StarList));
  const storylines = clz_Torappu_StageTable.createStorylinesVector(builder, builder.createObjectOffsetList(this.storylines));
  const storylineStorySets = clz_Torappu_StageTable.createStorylineStorySetsVector(builder, builder.createObjectOffsetList(this.storylineStorySets));
  const storylineTags = clz_Torappu_StageTable.createStorylineTagsVector(builder, builder.createObjectOffsetList(this.storylineTags));
  const storylineConst = (this.storylineConst !== null ? this.storylineConst!.pack(builder) : 0);
  const sixStarRuneData = clz_Torappu_StageTable.createSixStarRuneDataVector(builder, builder.createObjectOffsetList(this.sixStarRuneData));
  const sixStarMilestoneInfo = clz_Torappu_StageTable.createSixStarMilestoneInfoVector(builder, builder.createObjectOffsetList(this.sixStarMilestoneInfo));
  const sixStarCompatibleInfo = clz_Torappu_StageTable.createSixStarCompatibleInfoVector(builder, builder.createObjectOffsetList(this.sixStarCompatibleInfo));
  const conditionalDropInfo = clz_Torappu_StageTable.createConditionalDropInfoVector(builder, builder.createObjectOffsetList(this.conditionalDropInfo));

  clz_Torappu_StageTable.startclz_Torappu_StageTable(builder);
  clz_Torappu_StageTable.addStages(builder, stages);
  clz_Torappu_StageTable.addRuneStageGroups(builder, runeStageGroups);
  clz_Torappu_StageTable.addMapThemes(builder, mapThemes);
  clz_Torappu_StageTable.addTileInfo(builder, tileInfo);
  clz_Torappu_StageTable.addForceOpenTable(builder, forceOpenTable);
  clz_Torappu_StageTable.addTimelyStageDropInfo(builder, timelyStageDropInfo);
  clz_Torappu_StageTable.addOverrideDropInfo(builder, overrideDropInfo);
  clz_Torappu_StageTable.addOverrideUnlockInfo(builder, overrideUnlockInfo);
  clz_Torappu_StageTable.addTimelyTable(builder, timelyTable);
  clz_Torappu_StageTable.addStageValidInfo(builder, stageValidInfo);
  clz_Torappu_StageTable.addStageFogInfo(builder, stageFogInfo);
  clz_Torappu_StageTable.addStageStartConds(builder, stageStartConds);
  clz_Torappu_StageTable.addDiffGroupTable(builder, diffGroupTable);
  clz_Torappu_StageTable.addStoryStageShowGroup(builder, storyStageShowGroup);
  clz_Torappu_StageTable.addSpecialBattleFinishStageData(builder, specialBattleFinishStageData);
  clz_Torappu_StageTable.addRecordRewardData(builder, recordRewardData);
  clz_Torappu_StageTable.addApProtectZoneInfo(builder, apProtectZoneInfo);
  clz_Torappu_StageTable.addAntiSpoilerDict(builder, antiSpoilerDict);
  clz_Torappu_StageTable.addActCustomStageDatas(builder, actCustomStageDatas);
  clz_Torappu_StageTable.addSpNormalStageIdFor4StarList(builder, spNormalStageIdFor4StarList);
  clz_Torappu_StageTable.addStorylines(builder, storylines);
  clz_Torappu_StageTable.addStorylineStorySets(builder, storylineStorySets);
  clz_Torappu_StageTable.addStorylineTags(builder, storylineTags);
  clz_Torappu_StageTable.addStorylineConst(builder, storylineConst);
  clz_Torappu_StageTable.addSixStarRuneData(builder, sixStarRuneData);
  clz_Torappu_StageTable.addSixStarMilestoneInfo(builder, sixStarMilestoneInfo);
  clz_Torappu_StageTable.addSixStarCompatibleInfo(builder, sixStarCompatibleInfo);
  clz_Torappu_StageTable.addConditionalDropInfo(builder, conditionalDropInfo);

  return clz_Torappu_StageTable.endclz_Torappu_StageTable(builder);
}
}
