// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo implements flatbuffers.IUnpackableObject<clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo):clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo {
  return (obj || new clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo):clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

itemName():string|null
itemName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
itemName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

level():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addItemName(builder:flatbuffers.Builder, itemNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, itemNameOffset, 0);
}

static addLevel(builder:flatbuffers.Builder, level:number) {
  builder.addFieldInt32(1, level, 0);
}

static endclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder:flatbuffers.Builder, itemNameOffset:flatbuffers.Offset, level:number):flatbuffers.Offset {
  clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo.startclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder);
  clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo.addItemName(builder, itemNameOffset);
  clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo.addLevel(builder, level);
  return clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo.endclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder);
}

unpack(): clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfoT {
  return new clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfoT(
    this.itemName(),
    this.level()
  );
}


unpackTo(_o: clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfoT): void {
  _o.itemName = this.itemName();
  _o.level = this.level();
}
}

export class clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public itemName: string|Uint8Array|null = null,
  public level: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const itemName = (this.itemName !== null ? builder.createString(this.itemName!) : 0);

  return clz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo.createclz_Torappu_Act35SideData_Act35SideMileStoneGrandRewardInfo(builder,
    itemName,
    this.level
  );
}
}
