// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_RoguelikeTopicDisplayItem, clz_Torappu_RoguelikeTopicDisplayItemT } from './clz-torappu-roguelike-topic-display-item.js';
import { enum__Torappu_RL02DevelopmentEffectType } from './enum--torappu-rl02-development-effect-type.js';
import { enum__Torappu_RL02DevelopmentNodeType } from './enum--torappu-rl02-development-node-type.js';


export class clz_Torappu_RL02Development implements flatbuffers.IUnpackableObject<clz_Torappu_RL02DevelopmentT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):clz_Torappu_RL02Development {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsclz_Torappu_RL02Development(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RL02Development):clz_Torappu_RL02Development {
  return (obj || new clz_Torappu_RL02Development()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsclz_Torappu_RL02Development(bb:flatbuffers.ByteBuffer, obj?:clz_Torappu_RL02Development):clz_Torappu_RL02Development {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new clz_Torappu_RL02Development()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

buffId():string|null
buffId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
buffId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

nodeType():enum__Torappu_RL02DevelopmentNodeType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_RL02DevelopmentNodeType.NONE;
}

frontNodeId(index: number):string
frontNodeId(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
frontNodeId(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

frontNodeIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

nextNodeId(index: number):string
nextNodeId(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
nextNodeId(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

nextNodeIdLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

positionP():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

positionR():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

tokenCost():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

buffName():string|null
buffName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
buffName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

buffIconId():string|null
buffIconId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
buffIconId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

effectType():enum__Torappu_RL02DevelopmentEffectType {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_RL02DevelopmentEffectType.BUFF;
}

rawDesc():string|null
rawDesc(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
rawDesc(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

buffDisplayInfo(index: number, obj?:clz_Torappu_RoguelikeTopicDisplayItem):clz_Torappu_RoguelikeTopicDisplayItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new clz_Torappu_RoguelikeTopicDisplayItem()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

buffDisplayInfoLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

enrollId():string|null
enrollId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
enrollId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startclz_Torappu_RL02Development(builder:flatbuffers.Builder) {
  builder.startObject(13);
}

static addBuffId(builder:flatbuffers.Builder, buffIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, buffIdOffset, 0);
}

static addNodeType(builder:flatbuffers.Builder, nodeType:enum__Torappu_RL02DevelopmentNodeType) {
  builder.addFieldInt32(1, nodeType, enum__Torappu_RL02DevelopmentNodeType.NONE);
}

static addFrontNodeId(builder:flatbuffers.Builder, frontNodeIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, frontNodeIdOffset, 0);
}

static createFrontNodeIdVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startFrontNodeIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addNextNodeId(builder:flatbuffers.Builder, nextNodeIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, nextNodeIdOffset, 0);
}

static createNextNodeIdVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startNextNodeIdVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addPositionP(builder:flatbuffers.Builder, positionP:number) {
  builder.addFieldInt32(4, positionP, 0);
}

static addPositionR(builder:flatbuffers.Builder, positionR:number) {
  builder.addFieldInt32(5, positionR, 0);
}

static addTokenCost(builder:flatbuffers.Builder, tokenCost:number) {
  builder.addFieldInt32(6, tokenCost, 0);
}

static addBuffName(builder:flatbuffers.Builder, buffNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, buffNameOffset, 0);
}

static addBuffIconId(builder:flatbuffers.Builder, buffIconIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, buffIconIdOffset, 0);
}

static addEffectType(builder:flatbuffers.Builder, effectType:enum__Torappu_RL02DevelopmentEffectType) {
  builder.addFieldInt32(9, effectType, enum__Torappu_RL02DevelopmentEffectType.BUFF);
}

static addRawDesc(builder:flatbuffers.Builder, rawDescOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, rawDescOffset, 0);
}

static addBuffDisplayInfo(builder:flatbuffers.Builder, buffDisplayInfoOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, buffDisplayInfoOffset, 0);
}

static createBuffDisplayInfoVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startBuffDisplayInfoVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addEnrollId(builder:flatbuffers.Builder, enrollIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(12, enrollIdOffset, 0);
}

static endclz_Torappu_RL02Development(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createclz_Torappu_RL02Development(builder:flatbuffers.Builder, buffIdOffset:flatbuffers.Offset, nodeType:enum__Torappu_RL02DevelopmentNodeType, frontNodeIdOffset:flatbuffers.Offset, nextNodeIdOffset:flatbuffers.Offset, positionP:number, positionR:number, tokenCost:number, buffNameOffset:flatbuffers.Offset, buffIconIdOffset:flatbuffers.Offset, effectType:enum__Torappu_RL02DevelopmentEffectType, rawDescOffset:flatbuffers.Offset, buffDisplayInfoOffset:flatbuffers.Offset, enrollIdOffset:flatbuffers.Offset):flatbuffers.Offset {
  clz_Torappu_RL02Development.startclz_Torappu_RL02Development(builder);
  clz_Torappu_RL02Development.addBuffId(builder, buffIdOffset);
  clz_Torappu_RL02Development.addNodeType(builder, nodeType);
  clz_Torappu_RL02Development.addFrontNodeId(builder, frontNodeIdOffset);
  clz_Torappu_RL02Development.addNextNodeId(builder, nextNodeIdOffset);
  clz_Torappu_RL02Development.addPositionP(builder, positionP);
  clz_Torappu_RL02Development.addPositionR(builder, positionR);
  clz_Torappu_RL02Development.addTokenCost(builder, tokenCost);
  clz_Torappu_RL02Development.addBuffName(builder, buffNameOffset);
  clz_Torappu_RL02Development.addBuffIconId(builder, buffIconIdOffset);
  clz_Torappu_RL02Development.addEffectType(builder, effectType);
  clz_Torappu_RL02Development.addRawDesc(builder, rawDescOffset);
  clz_Torappu_RL02Development.addBuffDisplayInfo(builder, buffDisplayInfoOffset);
  clz_Torappu_RL02Development.addEnrollId(builder, enrollIdOffset);
  return clz_Torappu_RL02Development.endclz_Torappu_RL02Development(builder);
}

unpack(): clz_Torappu_RL02DevelopmentT {
  return new clz_Torappu_RL02DevelopmentT(
    this.buffId(),
    this.nodeType(),
    this.bb!.createScalarList<string>(this.frontNodeId.bind(this), this.frontNodeIdLength()),
    this.bb!.createScalarList<string>(this.nextNodeId.bind(this), this.nextNodeIdLength()),
    this.positionP(),
    this.positionR(),
    this.tokenCost(),
    this.buffName(),
    this.buffIconId(),
    this.effectType(),
    this.rawDesc(),
    this.bb!.createObjList<clz_Torappu_RoguelikeTopicDisplayItem, clz_Torappu_RoguelikeTopicDisplayItemT>(this.buffDisplayInfo.bind(this), this.buffDisplayInfoLength()),
    this.enrollId()
  );
}


unpackTo(_o: clz_Torappu_RL02DevelopmentT): void {
  _o.buffId = this.buffId();
  _o.nodeType = this.nodeType();
  _o.frontNodeId = this.bb!.createScalarList<string>(this.frontNodeId.bind(this), this.frontNodeIdLength());
  _o.nextNodeId = this.bb!.createScalarList<string>(this.nextNodeId.bind(this), this.nextNodeIdLength());
  _o.positionP = this.positionP();
  _o.positionR = this.positionR();
  _o.tokenCost = this.tokenCost();
  _o.buffName = this.buffName();
  _o.buffIconId = this.buffIconId();
  _o.effectType = this.effectType();
  _o.rawDesc = this.rawDesc();
  _o.buffDisplayInfo = this.bb!.createObjList<clz_Torappu_RoguelikeTopicDisplayItem, clz_Torappu_RoguelikeTopicDisplayItemT>(this.buffDisplayInfo.bind(this), this.buffDisplayInfoLength());
  _o.enrollId = this.enrollId();
}
}

export class clz_Torappu_RL02DevelopmentT implements flatbuffers.IGeneratedObject {
constructor(
  public buffId: string|Uint8Array|null = null,
  public nodeType: enum__Torappu_RL02DevelopmentNodeType = enum__Torappu_RL02DevelopmentNodeType.NONE,
  public frontNodeId: (string)[] = [],
  public nextNodeId: (string)[] = [],
  public positionP: number = 0,
  public positionR: number = 0,
  public tokenCost: number = 0,
  public buffName: string|Uint8Array|null = null,
  public buffIconId: string|Uint8Array|null = null,
  public effectType: enum__Torappu_RL02DevelopmentEffectType = enum__Torappu_RL02DevelopmentEffectType.BUFF,
  public rawDesc: string|Uint8Array|null = null,
  public buffDisplayInfo: (clz_Torappu_RoguelikeTopicDisplayItemT)[] = [],
  public enrollId: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const buffId = (this.buffId !== null ? builder.createString(this.buffId!) : 0);
  const frontNodeId = clz_Torappu_RL02Development.createFrontNodeIdVector(builder, builder.createObjectOffsetList(this.frontNodeId));
  const nextNodeId = clz_Torappu_RL02Development.createNextNodeIdVector(builder, builder.createObjectOffsetList(this.nextNodeId));
  const buffName = (this.buffName !== null ? builder.createString(this.buffName!) : 0);
  const buffIconId = (this.buffIconId !== null ? builder.createString(this.buffIconId!) : 0);
  const rawDesc = (this.rawDesc !== null ? builder.createString(this.rawDesc!) : 0);
  const buffDisplayInfo = clz_Torappu_RL02Development.createBuffDisplayInfoVector(builder, builder.createObjectOffsetList(this.buffDisplayInfo));
  const enrollId = (this.enrollId !== null ? builder.createString(this.enrollId!) : 0);

  return clz_Torappu_RL02Development.createclz_Torappu_RL02Development(builder,
    buffId,
    this.nodeType,
    frontNodeId,
    nextNodeId,
    this.positionP,
    this.positionR,
    this.tokenCost,
    buffName,
    buffIconId,
    this.effectType,
    rawDesc,
    buffDisplayInfo,
    enrollId
  );
}
}
