// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_Act17sideData_TechTreeData, clz_Torappu_Act17sideData_TechTreeDataT } from './clz-torappu-act17side-data-tech-tree-data.js';


export class dict__string__clz_Torappu_Act17sideData_TechTreeData implements flatbuffers.IUnpackableObject<dict__string__clz_Torappu_Act17sideData_TechTreeDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):dict__string__clz_Torappu_Act17sideData_TechTreeData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdict__string__clz_Torappu_Act17sideData_TechTreeData(bb:flatbuffers.ByteBuffer, obj?:dict__string__clz_Torappu_Act17sideData_TechTreeData):dict__string__clz_Torappu_Act17sideData_TechTreeData {
  return (obj || new dict__string__clz_Torappu_Act17sideData_TechTreeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdict__string__clz_Torappu_Act17sideData_TechTreeData(bb:flatbuffers.ByteBuffer, obj?:dict__string__clz_Torappu_Act17sideData_TechTreeData):dict__string__clz_Torappu_Act17sideData_TechTreeData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new dict__string__clz_Torappu_Act17sideData_TechTreeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value(obj?:clz_Torappu_Act17sideData_TechTreeData):clz_Torappu_Act17sideData_TechTreeData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_Act17sideData_TechTreeData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startdict__string__clz_Torappu_Act17sideData_TechTreeData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static enddict__string__clz_Torappu_Act17sideData_TechTreeData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  return offset;
}


unpack(): dict__string__clz_Torappu_Act17sideData_TechTreeDataT {
  return new dict__string__clz_Torappu_Act17sideData_TechTreeDataT(
    this.key(),
    (this.value() !== null ? this.value()!.unpack() : null)
  );
}


unpackTo(_o: dict__string__clz_Torappu_Act17sideData_TechTreeDataT): void {
  _o.key = this.key();
  _o.value = (this.value() !== null ? this.value()!.unpack() : null);
}
}

export class dict__string__clz_Torappu_Act17sideData_TechTreeDataT implements flatbuffers.IGeneratedObject {
constructor(
  public key: string|Uint8Array|null = null,
  public value: clz_Torappu_Act17sideData_TechTreeDataT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);
  const value = (this.value !== null ? this.value!.pack(builder) : 0);

  dict__string__clz_Torappu_Act17sideData_TechTreeData.startdict__string__clz_Torappu_Act17sideData_TechTreeData(builder);
  dict__string__clz_Torappu_Act17sideData_TechTreeData.addKey(builder, key);
  dict__string__clz_Torappu_Act17sideData_TechTreeData.addValue(builder, value);

  return dict__string__clz_Torappu_Act17sideData_TechTreeData.enddict__string__clz_Torappu_Act17sideData_TechTreeData(builder);
}
}
