// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_AutoChessData_AutoChessBossInfoData, clz_Torappu_AutoChessData_AutoChessBossInfoDataT } from './clz-torappu-auto-chess-data-auto-chess-boss-info-data.js';


export class dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData implements flatbuffers.IUnpackableObject<dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(bb:flatbuffers.ByteBuffer, obj?:dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData):dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData {
  return (obj || new dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(bb:flatbuffers.ByteBuffer, obj?:dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData):dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value(obj?:clz_Torappu_AutoChessData_AutoChessBossInfoData):clz_Torappu_AutoChessData_AutoChessBossInfoData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_AutoChessData_AutoChessBossInfoData()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startdict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static enddict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  return offset;
}


unpack(): dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoDataT {
  return new dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoDataT(
    this.key(),
    (this.value() !== null ? this.value()!.unpack() : null)
  );
}


unpackTo(_o: dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoDataT): void {
  _o.key = this.key();
  _o.value = (this.value() !== null ? this.value()!.unpack() : null);
}
}

export class dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoDataT implements flatbuffers.IGeneratedObject {
constructor(
  public key: string|Uint8Array|null = null,
  public value: clz_Torappu_AutoChessData_AutoChessBossInfoDataT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);
  const value = (this.value !== null ? this.value!.pack(builder) : 0);

  dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData.startdict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(builder);
  dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData.addKey(builder, key);
  dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData.addValue(builder, value);

  return dict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData.enddict__string__clz_Torappu_AutoChessData_AutoChessBossInfoData(builder);
}
}
