// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_HomeMultiFormTimeRuleData, clz_Torappu_HomeMultiFormTimeRuleDataT } from './clz-torappu-home-multi-form-time-rule-data.js';


export class dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData implements flatbuffers.IUnpackableObject<dict__string__list_clz_Torappu_HomeMultiFormTimeRuleDataT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(bb:flatbuffers.ByteBuffer, obj?:dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData):dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData {
  return (obj || new dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(bb:flatbuffers.ByteBuffer, obj?:dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData):dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value(index: number, obj?:clz_Torappu_HomeMultiFormTimeRuleData):clz_Torappu_HomeMultiFormTimeRuleData|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_HomeMultiFormTimeRuleData()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static enddict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // key
  return offset;
}

static createdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.startdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder);
  dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.addKey(builder, keyOffset);
  dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.addValue(builder, valueOffset);
  return dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.enddict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder);
}

unpack(): dict__string__list_clz_Torappu_HomeMultiFormTimeRuleDataT {
  return new dict__string__list_clz_Torappu_HomeMultiFormTimeRuleDataT(
    this.key(),
    this.bb!.createObjList<clz_Torappu_HomeMultiFormTimeRuleData, clz_Torappu_HomeMultiFormTimeRuleDataT>(this.value.bind(this), this.valueLength())
  );
}


unpackTo(_o: dict__string__list_clz_Torappu_HomeMultiFormTimeRuleDataT): void {
  _o.key = this.key();
  _o.value = this.bb!.createObjList<clz_Torappu_HomeMultiFormTimeRuleData, clz_Torappu_HomeMultiFormTimeRuleDataT>(this.value.bind(this), this.valueLength());
}
}

export class dict__string__list_clz_Torappu_HomeMultiFormTimeRuleDataT implements flatbuffers.IGeneratedObject {
constructor(
  public key: string|Uint8Array|null = null,
  public value: (clz_Torappu_HomeMultiFormTimeRuleDataT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const key = (this.key !== null ? builder.createString(this.key!) : 0);
  const value = dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.createValueVector(builder, builder.createObjectOffsetList(this.value));

  return dict__string__list_clz_Torappu_HomeMultiFormTimeRuleData.createdict__string__list_clz_Torappu_HomeMultiFormTimeRuleData(builder,
    key,
    value
  );
}
}
