// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { clz_Torappu_RoguelikeChaosPredefineLevelInfo, clz_Torappu_RoguelikeChaosPredefineLevelInfoT } from './clz-torappu-roguelike-chaos-predefine-level-info.js';


export class dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo implements flatbuffers.IUnpackableObject<dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(bb:flatbuffers.ByteBuffer, obj?:dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo):dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo {
  return (obj || new dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(bb:flatbuffers.ByteBuffer, obj?:dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo):dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

value(obj?:clz_Torappu_RoguelikeChaosPredefineLevelInfo):clz_Torappu_RoguelikeChaosPredefineLevelInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new clz_Torappu_RoguelikeChaosPredefineLevelInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startdict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, key:number) {
  builder.addFieldInt32(0, key, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static enddict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfoT {
  return new dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfoT(
    this.key(),
    (this.value() !== null ? this.value()!.unpack() : null)
  );
}


unpackTo(_o: dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfoT): void {
  _o.key = this.key();
  _o.value = (this.value() !== null ? this.value()!.unpack() : null);
}
}

export class dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public key: number = 0,
  public value: clz_Torappu_RoguelikeChaosPredefineLevelInfoT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = (this.value !== null ? this.value!.pack(builder) : 0);

  dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo.startdict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(builder);
  dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo.addKey(builder, this.key);
  dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo.addValue(builder, value);

  return dict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo.enddict__int__clz_Torappu_RoguelikeChaosPredefineLevelInfo(builder);
}
}
