// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { enum__Torappu_RoguelikeTotemColorType } from './enum--torappu-roguelike-totem-color-type.js';


export class dict__enum__Torappu_RoguelikeTotemColorType__string implements flatbuffers.IUnpackableObject<dict__enum__Torappu_RoguelikeTotemColorType__stringT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):dict__enum__Torappu_RoguelikeTotemColorType__string {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsdict__enum__Torappu_RoguelikeTotemColorType__string(bb:flatbuffers.ByteBuffer, obj?:dict__enum__Torappu_RoguelikeTotemColorType__string):dict__enum__Torappu_RoguelikeTotemColorType__string {
  return (obj || new dict__enum__Torappu_RoguelikeTotemColorType__string()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsdict__enum__Torappu_RoguelikeTotemColorType__string(bb:flatbuffers.ByteBuffer, obj?:dict__enum__Torappu_RoguelikeTotemColorType__string):dict__enum__Torappu_RoguelikeTotemColorType__string {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new dict__enum__Torappu_RoguelikeTotemColorType__string()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():enum__Torappu_RoguelikeTotemColorType {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : enum__Torappu_RoguelikeTotemColorType.NONE;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startdict__enum__Torappu_RoguelikeTotemColorType__string(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addKey(builder:flatbuffers.Builder, key:enum__Torappu_RoguelikeTotemColorType) {
  builder.addFieldInt32(0, key, enum__Torappu_RoguelikeTotemColorType.NONE);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static enddict__enum__Torappu_RoguelikeTotemColorType__string(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createdict__enum__Torappu_RoguelikeTotemColorType__string(builder:flatbuffers.Builder, key:enum__Torappu_RoguelikeTotemColorType, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  dict__enum__Torappu_RoguelikeTotemColorType__string.startdict__enum__Torappu_RoguelikeTotemColorType__string(builder);
  dict__enum__Torappu_RoguelikeTotemColorType__string.addKey(builder, key);
  dict__enum__Torappu_RoguelikeTotemColorType__string.addValue(builder, valueOffset);
  return dict__enum__Torappu_RoguelikeTotemColorType__string.enddict__enum__Torappu_RoguelikeTotemColorType__string(builder);
}

unpack(): dict__enum__Torappu_RoguelikeTotemColorType__stringT {
  return new dict__enum__Torappu_RoguelikeTotemColorType__stringT(
    this.key(),
    this.value()
  );
}


unpackTo(_o: dict__enum__Torappu_RoguelikeTotemColorType__stringT): void {
  _o.key = this.key();
  _o.value = this.value();
}
}

export class dict__enum__Torappu_RoguelikeTotemColorType__stringT implements flatbuffers.IGeneratedObject {
constructor(
  public key: enum__Torappu_RoguelikeTotemColorType = enum__Torappu_RoguelikeTotemColorType.NONE,
  public value: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const value = (this.value !== null ? builder.createString(this.value!) : 0);

  return dict__enum__Torappu_RoguelikeTotemColorType__string.createdict__enum__Torappu_RoguelikeTotemColorType__string(builder,
    this.key,
    value
  );
}
}
