// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_Act29SideData_Act29SideInvestType {
  MAJOR = 0,
  RARE = 1,
  NORMAL = 2
}
