// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_ActivityCompleteType {
  SPECIAL = 0,
  CAN_COMPLETE = 1,
  CANNOT_COMPLETE = 2
}
