// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_Act24SideData_MeldingGoodGachaType {
  NONE = 0,
  LIMITED = 1,
  UNLIMITED = 2
}
