// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_ActivityDisplayType {
  NONE = 0,
  SIDESTORY = 1,
  BRANCHLINE = 2,
  MINISTORY = 3
}
