// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_PlayerStageState {
  UNLOCKED = 0,
  PLAYED = 1,
  PASS = 2,
  COMPLETE = 3
}
