// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum enum__Torappu_ActArchiveCopperType {
  ERR_ZERO = 0,
  LUCK = 1,
  COPPER = 2,
  GILD = 3
}
